// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.restheart/{defaults,vars}/*.yml
// Per-role variable context: 7 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  restheart_bind_host: string;
  restheart_bind_port: number;
  restheart_home: string;
  restheart_host: string;
  restheart_nginxsite_name: string;
  restheart_port: string;
  restheart_user: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
