// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.restheart/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  restheart_bind_port: unknown;
  restheart_home: unknown;
  restheart_port: unknown;
  restheart_user: unknown;
}

export const { V, tmpl } = context<
  Vars & Globals & BuiltinVars & ParamVars
>();
