// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.cpauth/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  cpauth_bind_addr: Tmpl;
  cpauth_home: string;
  cpauth_host: Tmpl;
  cpauth_mailing_pass: Tmpl;
  cpauth_mailing_smtp: Tmpl;
  cpauth_masteradmin_pass: Tmpl;
  cpauth_oauth_conf: Tmpl;
  cpauth_port: number;
  cpauth_user: string;
  cpauth_user_secret_salt: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const cpauth_bind_addr = vref("cpauth_bind_addr");
export const cpauth_home = vref("cpauth_home");
export const cpauth_host = vref("cpauth_host");
export const cpauth_mailing_pass = vref("cpauth_mailing_pass");
export const cpauth_mailing_smtp = vref("cpauth_mailing_smtp");
export const cpauth_masteradmin_pass = vref("cpauth_masteradmin_pass");
export const cpauth_oauth_conf = vref("cpauth_oauth_conf");
export const cpauth_port = vref("cpauth_port");
export const cpauth_user = vref("cpauth_user");
export const cpauth_user_secret_salt = vref("cpauth_user_secret_salt");
