// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.cpauth/{defaults,vars}/*.yml
// Per-role variable context: 10 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  cpauth_bind_addr: string;
  cpauth_home: string;
  cpauth_host: string;
  cpauth_mailing_pass: string;
  cpauth_mailing_smtp: string;
  cpauth_masteradmin_pass: string;
  cpauth_oauth_conf: string;
  cpauth_port: number;
  cpauth_user: string;
  cpauth_user_secret_salt: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
