// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.docker2/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  docker_periodic_cleanup: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  BuiltinVars
>();
