// Auto-generated by gen-data.ts from ../devops/roles/icos.python3/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "python3_version_list": [],
} satisfies VarsFile;
