// Auto-generated by gen-data.ts from ../devops/roles/icos.python3/defaults/main.yml
import { type Vars } from "../../../../roles/icos.python3/_ctx.ts";

export default {
  "python3_version_list": []
} satisfies Vars;
