all:
  # GLOBAL VARS
  vars:
    nginx_testing_users: "{{ vault_nginx_testing_users }}"

    # root_keys is what each VM needs to override.
    root_keys: "{{ vault_root_keys }}"

    # The keys used by lxd_guest when provisioning the vm
    lxd_guest_root_keys: "{{ root_keys }}"

    # The keys installed by lxd_vm when creating the VM, necessary to even
    # connect to the vm using ansible.
    lxd_vm_root_keys: "{{ root_keys }}"

    ansible_user: root
    quince_ext_port: 60522

    icos1_ip: 130.235.74.215
    fsicos1_ip: 194.47.223.133
    fsicos2_ip: 194.47.223.139
    fsicos3_ip: 194.47.223.137
    fsicos4_ip: 130.235.98.147
    cdb_ip: 130.235.99.237

    # The connection information for the rdflog database, we keep it here since
    # it's shared between several roles.
    rdflog_db_pass: "{{ vault_rdflog_db_pass }}"

    registry_domain: registry.icos-cp.eu

  hosts:
    fsicos4:
      external_ip: 130.235.98.147

  children:
    # ALIASES
    # We create a child group, even though it only contains a single
    # server. That way ansible will pick up host_vars correctly.
    staging_server:
      hosts:
        fsicos2.lunarc.lu.se:
    postgis_server:
      hosts:
        fsicos2.lunarc.lu.se:

    # PHYSICAL SERVERS
    physical_servers:
      vars:
        iptables_forward: true
      hosts:
        fsicos4:
          firewall_enabled: false
        cdb.nateko.lu.se:
        icos1:
          ansible_port: 60022
        fsicos2.lunarc.lu.se:
          root_keys: "{{ vault_fsicos2_root_keys }}"
          ansible_port: 60022
        fsicos3.lunarc.lu.se:

    fsicos4_vms:
      vars:
        ansible_user: debian
        ansible_become: yes
        ansible_host: fsicos4.icos-cp.eu
        root_keys: "{{ vault_fsicos4_vms_root_keys }}"
      hosts:
        cupcake:
          ansible_port: 60603
          user_conf: "{{ vault_cupcake_user_conf }}"
        pancake:
          ansible_port: 60605
          ansible_user: root
          user_conf: "{{ vault_pancake_user_conf }}"
        fsicos4-stiltcluster:
          ansible_port: 60601
        fdp:
          ansible_port: 60606
          ansible_user: fdp


    # CDB VMS
    cdb_vms:
      vars:
        ansible_host: cdb.nateko.lu.se
      hosts:
        pgrep2:
          ansible_port: 60550

    # FSICOS2 VMS
    fsicos2_vms:
      vars:
          ansible_host: fsicos2.lunarc.lu.se
      hosts:
        build:
          ansible_port: 60525
        staging:
          ansible_port: 60520
        erddap:
          ansible_port: 60580
          root_keys: "{{ vault_erddap_root_keys }}"
        flexextract:
          ansible_port: 60526
          user_conf: "{{ vault_flexextract_user_conf }}"
        postgis:
          ansible_port: 60590
          user_conf: "{{ vault_postgis_user_conf }}"
        # quince was the first, quince2 was a storage migration gone bad,
        # quince3 is the new VM.
        quince3:
          ansible_port: 60600
          quince_jdk_version: 17
          user_conf: "{{ vault_quince3_user_conf }}"
        rspamd:
          ansible_port: 60585
        wordpress:
          ansible_port: 60552
        cities:
          ansible_port: 60565

    # FSICOS3 VMS
    fsicos3_vms:
      vars:
        ansible_host: fsicos3.lunarc.lu.se
      hosts:
        amalthea:
          ansible_port: 60560
        callisto:
          ansible_port: 60510
          docker_prevent_upgrade: True
        exploredata:
          ansible_port: 60555
          docker_prevent_upgrade: True
          root_keys: "{{ vault_exploredata_root_keys }}"
        flexpart:
          ansible_port: 60530
          docker_prevent_upgrade: True
        ganymede:
          ansible_port: 60540
          docker_prevent_upgrade: True
          python3_version_list:
            - "3.10"
            - "3.11"
        jupyter:
          root_keys: "{{ vault_jupyter_root_keys }}"
          ansible_port: 60535
          docker_prevent_upgrade: True
          bbclient_name: jupyter
          jupyter_backup_enable: true
          python3_version_list:
            - "3.10"
            - "3.11"
        molefractions:
          ansible_port: 60515
        registry:
          ansible_port: 60545
        pgrep1:
          ansible_port: 60570
        ctehires:
          ansible_port: 60575
        dokku:
          root_keys: "{{ vault_dokku_root_keys }}"
          ansible_port: 60595
