stiltcluster_hosts:
  vars:
    stiltcluster_hostname: "{{ inventory_hostname }}.nebula"
    stiltcluster_stiltweb_hostname: fsicos2.nebula
    stiltcluster_fetch_host: fsicos2
    stiltcluster_fetch_path: /home/stiltcluster/stiltcluster.jar

  hosts:
    fsicos4-stiltcluster:
      stilt_input_dir: /data/stilt/Input
      stiltcluster_maxcores: 50

    # fsicos2:
    #   stilt_input_dir: /disk/data/stilt/Input
    #   stiltcluster_maxcores: 12

    icos1:
      stilt_input_dir: /data/stilt/Input
      stilt_input_mount: True
      # The machine has 24
      stiltcluster_maxcores: 20

    # fsicos3:
    #   stiltrun_user: stiltcluster
    #   stiltcluster_docker: false
    #   stiltcluster_maxcores: 40
    #   stilt_input_dir: /data/stilt_legacy/Input
