// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.script_exporter/{defaults,vars}/*.yml
// Per-role variable context: 8 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  sexp_arch: string;
  sexp_arch_map: Record<string, unknown>;
  sexp_config_file: string;
  sexp_home: string;
  sexp_listen: string;
  sexp_scripts_enable: unknown[];
  sexp_scripts_repo: string;
  sexp_scripts_venv: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
