// Auto-generated by gen-data.ts from ../devops/roles/icos.certbot2/defaults/main.yml
import { certbot_name } from "../../../../lib/sharedvars.ts";
import { tmpl } from "../../../../lib/template.ts";
import { V, type Vars } from "../../../../roles/icos.certbot2/_ctx.ts";

export default {
  "certbot_bin": "certbot",
  "certbot_email": "carbon.admin@nateko.lu.se",
  "certbot_site_path": tmpl`/etc/letsencrypt/live/${certbot_name}`,
  "certbot_cert_path": tmpl`${V.certbot_site_path}/fullchain.pem`,
  "certbot_key_path": tmpl`${V.certbot_site_path}/privkey.pem`,
  "certbot_nginx_conf": tmpl`ssl_certificate ${V.certbot_cert_path};
ssl_certificate_key ${V.certbot_key_path};
`
} satisfies Vars;
