// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.virtuoso/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  virtuoso_bind_host: string;
  virtuoso_home: string;
  virtuoso_host: string;
  virtuoso_http_port: number;
  virtuoso_port: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
