// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.virtuoso/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  virtuoso_bind_host: string;
  virtuoso_home: Tmpl;
  virtuoso_host: Tmpl;
  virtuoso_http_port: number;
  virtuoso_port: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const virtuoso_bind_host = vref("virtuoso_bind_host");
export const virtuoso_home = vref("virtuoso_home");
export const virtuoso_host = vref("virtuoso_host");
export const virtuoso_http_port = vref("virtuoso_http_port");
export const virtuoso_port = vref("virtuoso_port");
