// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.virtuoso/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  virtuoso_bind_host: unknown;
  virtuoso_home: unknown;
  virtuoso_host: unknown;
  virtuoso_http_port: unknown;
  virtuoso_port: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & BuiltinVars
>();
