// Auto-generated by gen-data.ts from ../devops/roles/icos.timer2/defaults/main.yml
import type { Vars } from "../../../../roles/icos.timer2/_ctx.ts";
import { context } from "../../../../lib/context.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";

interface Self {
  _timer_sysd_service: unknown;
  _timer_sysd_timer: unknown;
  timer_dest: unknown;
  timer_home: unknown;
  timer_state: unknown;
}
const { V, tmpl } = context<Self & ParamVars>();

export default {
  "timer_home": "/etc/systemd/system",
  "timer_dest": tmpl`${V.timer_home}/${V.timer_name}`,
  "_timer_sysd_timer": tmpl`${V.timer_home}/${V.timer_name}.timer`,
  "_timer_sysd_service": tmpl`${V.timer_home}/${V.timer_name}.service`,
  "timer_state": "started",
} satisfies Vars;
