// Auto-generated by gen-data.ts from ../devops/roles/icos.timer2/defaults/main.yml
import { timer_name } from "../../../../lib/paramvars.ts";
import { tmpl } from "../../../../lib/template.ts";
import { V, type Vars } from "../../../../roles/icos.timer2/_ctx.ts";

export default {
  "timer_home": "/etc/systemd/system",
  "timer_dest": tmpl`${V.timer_home}/${timer_name}`,
  "_timer_sysd_timer": tmpl`${V.timer_home}/${timer_name}.timer`,
  "_timer_sysd_service": tmpl`${V.timer_home}/${timer_name}.service`,
  "timer_state": "started"
} satisfies Vars;
