// Auto-generated by gen-data.ts from ../devops/roles/icos.nginxauth/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "nginxauth_title": "Login required",
  "nginxauth_file": "/etc/nginx/auth/{{ nginxauth_name }}",
  "nginxauth_conf":
    'auth_basic "{{ nginxauth_title }}";\nauth_basic_user_file {{ nginxauth_file }};\n',
} satisfies VarsFile;
