// Auto-generated by gen-data.ts from ../devops/roles/icos.nginxauth/defaults/main.yml
import type { Vars } from "../../../../roles/icos.nginxauth/_ctx.ts";
import { context } from "../../../../lib/context.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  nginxauth_title: unknown;
  nginxauth_file: unknown;
  nginxauth_conf: unknown;
}
const { V, tmpl } = context<Self & AllVars>();

export default {
  "nginxauth_title": "Login required",
  "nginxauth_file": tmpl`/etc/nginx/auth/${V.nginxauth_name}`,
  "nginxauth_conf": tmpl`auth_basic "${V.nginxauth_title}";
auth_basic_user_file ${V.nginxauth_file};
`,
} satisfies Vars;
