// Auto-generated by gen-data.ts from ../devops/roles/icos.nginxauth/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "nginxauth_title": "Login required",
  "nginxauth_file": tmpl`/etc/nginx/auth/${expr("nginxauth_name")}`,
  "nginxauth_conf": tmpl`auth_basic "${expr("nginxauth_title")}";
auth_basic_user_file ${expr("nginxauth_file")};
`,
} satisfies VarsFile;
