// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.pve_guest/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  upgrade_everything: boolean;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const upgrade_everything = vref("upgrade_everything");
