// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.pve_guest/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  upgrade_everything: boolean;
}

export const { V, tmpl } = context<
  Vars & BuiltinVars
>();
