- name: Install python3-click
  apt:
    name: python3-click

- name: Create coldbackup helper scripts
  template:
    src: "{{ item }}"
    dest: "{{ bbclient_bin_dir }}"
    mode: +x
  loop:
    - bbclient-coldbackup
    - bbclient-coldrestore

- name: Add coldbackup systemd timer
  include_role:
    name: icos.timer
  vars:
    timer_home: "{{ bbclient_home }}"
    timer_exec: "{{ bbclient_bin_dir }}/bbclient-coldbackup"
    timer_name: "bbclient-{{ bbclient_name }}-coldbackup"
    timer_conf: |
      OnCalendar={{ bbclient_coldbackup_hour }}:{{ bbclient_coldbackup_minute }}
    timer_envs:
      - PYTHONUNBUFFERED=1
