- name: Setup local ssh directory
  tags: bbclient_ssh
  import_tasks: ssh.yml
  become: yes
  become_user: "{{ bbclient_user }}"

- name: Install bbclient shell-scripts
  tags: bbclient_scripts
  import_tasks: scripts.yml
  become: yes
  become_user: "{{ bbclient_user }}"

- import_tasks: repos.yml
  tags: bbclient_repos

- name: Create patterns.lst
  copy:
    dest: "{{ bbclient_patterns_path }}"
    content: "{{ bbclient_patterns }}"

- import_tasks: coldbackup.yml
  become: yes
  become_user: "{{ bbclient_user }}"
  tags: bbclient_coldbackup
  when: bbclient_coldbackup is defined

- name: Install bbclient backup script
  include_role: name=icos.timer
  vars:
    timer_home: "{{ bbclient_home }}/timer"
    timer_name: "bbclient-{{ bbclient_name }}"
    timer_conf: "{{ bbclient_timer_conf }}"
    timer_content: "{{ bbclient_timer_content }}"
  tags: bbclient_timer
  when:
    - bbclient_timer_content is defined

- import_tasks: just.yml
  tags: bbclient_just
