- name: Create new repo file
  copy:
    dest: "{{ bbclient_repo_file }}"
    content: |
      # Be aware that the "hostnames" in this file are then transformed by the
      # ssh config at {{ bbclient_ssh_config }}
      {% for br in bbclient_remotes %}
      {{ br }}:repos/{{ bbclient_name }}.repo
      {% endfor %}

- include_tasks: single_repo.yml
  loop: "{{ bbclient_remotes }}"
  loop_control:
    loop_var: bbclient_remote

- name: Run bbclient-all info to verify access
  command: "{{ bbclient_all }} info"
  environment:
    BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK: y
  changed_when: no
