- name: Create bin directory
  file:
    path: "{{ bbclient_bin_dir }}"
    state: directory

- name: Install borg wrapper that contains our ssh info
  copy:
    mode: +x
    dest: "{{ bbclient_wrapper }}"
    content: |
      #!/bin/bash
      export BORG_RSH="{{ bbclient_ssh_bin }}"
      export BORG_BASE_DIR="{{ bbclient_borg_dir }}"
      exec {{ borg_bin }} "$@"

- name: Create helper scripts
  template:
    src: "{{ item }}"
    dest: "{{ bbclient_bin_dir }}"
    mode: +x
  loop:
    - bbclient
    - bbclient-all
