// Auto-generated by gen-data.ts from ../devops/roles/icos.nebula/defaults/main.yml
import type { Vars } from "../../../../roles/icos.nebula/_ctx.ts";
import type { Restated } from "../../../../lib/data.ts";
import { hostvar } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { SharedVars } from "../../../../lib/sharedvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";

interface Self {
  nebula_bin_dir: unknown;
  nebula_ca_path: unknown;
  nebula_cert_min_days: unknown;
  nebula_domain: unknown;
  nebula_etc_dir: unknown;
  nebula_fw_enable: unknown;
  nebula_hostname: unknown;
  nebula_hosts_enable: unknown;
  nebula_is_lighthouse: unknown;
  nebula_resolve_enable: unknown;
  nebula_resolve_servers: unknown;
  nebula_resolve_test: unknown;
  nebula_resolve_type: unknown;
  nebula_ssh_key: unknown;
  nebula_ssh_port: unknown;
  nebula_stats_enable: unknown;
  nebula_stats_port: unknown;
  nebula_upgrade: unknown;
  nebula_url_map: unknown;
  nebula_user: unknown;
  nebula_version: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & SharedVars & ParamVars
>();

export default {
  "nebula_is_lighthouse": false,
  "nebula_interface": "nebula",
  "nebula_domain": "nebula",
  "nebula_cert_copy": V.nebula_cert_sign,
  "nebula_etc_dir": "/etc/nebula",
  "nebula_bin_dir": "/usr/local/bin",
  "nebula_user": "nebula",
  "nebula_port": 4242,
  "nebula_hosts_block": null,
  "nebula_hosts_enable": true,
  "nebula_fw_enable": true,
  "nebula_hostname": V.inventory_hostname_short,
  "nebula_upgrade": V.upgrade_everything.default(false).bool(),
  "nebula_ca_path": tmpl`${V.nebula_cert_files}/ca.crt`,
  "nebula_cert_min_days": 90,
  "nebula_stats_enable": false,
  "nebula_stats_port": 2735,
  "nebula_resolve_enable": false,
  "nebula_resolve_type": "probe",
  "nebula_resolve_servers": null,
  "nebula_resolve_test": null,
  "nebula_ssh_enable": false,
  "nebula_ssh_key": tmpl`${V.nebula_etc_dir}/admin`,
  "nebula_ssh_port": 2346,
  "nebula_version": hostvar("localhost").nebula_version,
  "nebula_url_map": {
    "armv6l":
      tmpl`https://github.com/slackhq/nebula/releases/download/v${V.nebula_version}/nebula-linux-arm-6.tar.gz`,
    "armv7l":
      tmpl`https://github.com/slackhq/nebula/releases/download/v${V.nebula_version}/nebula-linux-arm-7.tar.gz`,
    "x86_64":
      tmpl`https://github.com/slackhq/nebula/releases/download/v${V.nebula_version}/nebula-linux-amd64.tar.gz`,
    "aarch64":
      tmpl`https://github.com/slackhq/nebula/releases/download/v${V.nebula_version}/nebula-linux-arm64.tar.gz`,
  },
} satisfies
  & Vars
  & Restated<
    Globals,
    | "nebula_interface"
    | "nebula_cert_copy"
    | "nebula_port"
    | "nebula_hosts_block"
    | "nebula_ssh_enable"
  >;
