# icos play cpdata cpdata_deploy -ecpdata_jar_file=/tmp/cpdata.jar
# icos play cpdata cpdata_config
#
# Everything that mentions "netcdf" has to do with https://data.icos-cp.eu/netcdf/

- hosts: fsicos2
  roles:
    - role: icos.certbot2
      tags: cert
      certbot_name: "{{ cpdata_cert_name }}"
      certbot_domains: "{{ cpdata_domains }}"

    - role: icos.nginxsite
      tags: nginx
      nginxsite_name: cpdata
      nginxsite_file: roles/icos.cpdata/templates/cpdata.conf

    - role: icos.cpdata
      tags: cpdata
      cpdata_netcdf_folder: /disk/data/common/netcdf/dataDemo

    - role: icos.dataold
      tags: dataold

