- hosts: core_server
  tags: server
  pre_tasks:
    - name: Check that meta may be deployed to this inventory
      assert:
        that: meta_deploy_permitted
      tags:
        - always

  tasks:
    - name: Setup cpmeta proxy
      tags: proxy
      import_role:
        name: icos.cpmeta
        tasks_from: proxy.yml

- hosts: core_host
  tags: host
  pre_tasks:
    - name: Check that meta may be deployed to this inventory
      assert:
        that: meta_deploy_permitted
      tags:
        - always

    - name: Setup java
      tags:
        - java
        - cpmeta_setup
      import_role:
        name: icos.java

  roles:
    - role: icos.cpmeta
