- hosts: core_server
  tags: server
  tasks:
    - name: Setup cpmeta proxy
      tags: proxy
      import_role:
        name: icos.cpmeta
        tasks_from: proxy.yml

- hosts: core_host
  tags: host
  pre_tasks:
    - name: Setup java
      tags:
        - java
        - cpmeta_setup
      import_role:
        name: icos.java

  roles:
    - role: icos.cpmeta
