# This playbook contains various domains.

- hosts: fsicos2
  roles:
    # ICOS RI
    - role: icos.certbot2
      tags: icos-ri
      certbot_name: icos-ri.eu
      certbot_domains:
        - icos-ri.eu
        - www.icos-ri.eu
        - conference.icos-ri.eu

    - role: icos.nginxsite
      tags: icos-ri
      nginxsite_name: icos-ri
      nginxsite_file: files/domains/icos-ri.conf

    # ICOS CITIES
    - role: icos.certbot2
      tags: icos-cities
      certbot_name: icos-cities
      certbot_domains:
        - paul.icos-cp.eu
        - paul.icos-ri.eu
        - icos-cities.eu
        - www.icos-cities.eu

    - role: icos.nginxsite
      tags: icos-cities
      vars:
        nginxsite_name: icos-cities
        nginxsite_file: files/domains/icos-cities.conf

