#!/usr/bin/env -S just --unstable --justfile

set positional-arguments
set shell := ['/bin/bash', '-cu']

editor := env_var_or_default("EDITOR", "emacsclient --no-wait")
export ANSIBLE_INVENTORY := "inventory.inventory"


# META
@_default:
    just --unstable --list --unsorted --justfile {{justfile()}}

# have to use a shim in order to get working directory right
@_install dest="~/.local/bin/icos":
    #!/usr/bin/bash
    set -Eueo pipefail
    cat > {{dest}} <<EOF
    #!/usr/bin/bash
    set -Eueo pipefail
    cd {{ justfile_directory() }}
    just --unstable "\$@"
    EOF
    chmod +x {{dest}}



# RECIPIES
# run a playbook
play playbook *args:
    ansible-playbook {{playbook}}.yml {{args}}

# run the install playbook
install *args:
    ansible-playbook install.yml {{args}}

# install and upgrade_everything
upgrade *args:
    ansible-playbook install.yml -eupgrade_everything=1 {{args}}

# show facts about a host
facts host:
    ansible {{host}} -m setup

# edit the vault
vault:
    EDITOR=emacsclient ansible-vault edit group_vars/all/vault.yml
