# Build mailman images
#   icos play mailman mailman_build
#
# Copy build files but do not build nor start containers.
#   icos play mailman mailman_build -edocker_do_build=False
#
# Redeploy backup scripts
#   icos play mailman bbclient
#
# Redeploy proxy configuration
#   icos play mailman proxy

- hosts: fsicos2
  vars:
    mailman_rest_pass: "{{ vault_mailman_rest_pass }}"
    mailman_rest_allow_deny: "{{ vault_mailman_rest_allow_deny }}"
    mailman_domains:
      - 'lists.icos-ri.eu'
      - 'lists.eric-forum.eu'
      - 'lists.icos-cities.eu'
      - 'lists.kadi-project.eu'

  roles:
    - role: icos.mailman
      tags: mailman

    - role: icos.bbclient2
      tags: bbclient
      vars:
        bbclient_name: mailman
        bbclient_user: root
        bbclient_home: "{{ mailman_home }}/bbclient"
        bbclient_coldbackup: "{{ mailman_home }}"
        bbclient_remotes:
          - fsicos2
          - icos1

  tasks:
    - name: Install proxy for mailman
      tags: proxy
      import_role:
        name: icos.mailman
        tasks_from: proxy
