- hosts: fsicos2
  roles:
    - role: icos.nexus
      tags: nexus
    
    - role: icos.bbclient2
      tags: bbclient
      bbclient_name: nexus
      bbclient_user: root
      bbclient_home: "{{ nexus_home }}/bbclient"
      bbclient_coldbackup: "{{ nexus_home }}"
