# Provision physical hosts with vmagent and node_exporter.
#
# upgrade to latest vmagent:
# icos play vmagent vmagent -evmagent_upgrade=1 -D


- hosts: vmagent_hosts
  roles:
    - role: icos.vmagent
      tags: vmagent

    - role: icos.node_exporter
      tags: node

    - role: icos.script_exporter
      tags: script
      sexp_exporters:
        - smartmon
