- hosts: fsicos4
  roles:
    - role: icos.caddy
      tags: caddy
      caddy_name: fdpdemo
      caddy_conf: |
        fdpdemo.envri.eu {
            reverse_proxy 10.10.10.236:80
        }

- hosts: fdp
  roles:
    - role: icos.fairdatapoint
      tags: fairdatapoint