- hosts: fsicos4
  roles:
    - role: icos.pve_server
      tags: pve_server

    - role: icos.caddy
      tags: caddy
      caddy_name: flexextract
      caddy_conf: |
        flexextract.icos-cp.eu {
            handle /meteo/latest* {
                root * /mnt/icos1/pool/flexextract/meteo
                uri strip_prefix /meteo
                header Access-Control-Allow-Origin *
                file_server browse
            }

            handle /heatmap* {
                root * /tank/flexextract
                file_server browse
            }

            handle {
                respond 403
            }
        }

  tasks:
    - name: Synchronize VM SSH port forwarding
      tags: guest
      command: icos-auto-dnat run
      register: _flexextract_auto_dnat
      changed_when: >-
        'adding port' in _flexextract_auto_dnat.stdout or
        'removing rule' in _flexextract_auto_dnat.stdout


- hosts: flexextract
  roles:
    - role: icos.pve_guest
      tags: guest

    - role: icos.utils
      tags: utils

    - role: icos.python3
      tags: python3

    - role: icos.docker2
      tags: docker

    - role: icos.flexextract
      tags: flexextract
      flexextract_src_dir: /tmp/docker_flexextract_7.1.0
      flexextract_download_host: /data/flexextract4

    - role: icos.sshlogin
      tags: sshlogin
      sshlogin_dst: flexpart
      sshlogin_src_user: root
      sshlogin_dst_user: ubuntu
