- hosts: fsicos2
  vars:
    wordpress_domains:
      - www.ingos-infrastructure.eu
      - eric-forum.eu
      - www.eric-forum.eu
      - www.icos-summerschool.eu
      - www.envriplus.eu
      - ggmt2022.online
      - www.ggmt2022.online
      - avengers-project.eu
      - www.avengers-project.eu
      - george-project.eu
      - www.george-project.eu
      - kadi-project.eu
      - www.kadi-project.eu
      - global-ecosystem-ri.org
      - www.global-ecosystem-ri.org
  roles:
    - role: icos.lxd_vm
      tags: lxd
      lxd_vm_name: wordpress
      lxd_vm_root_size: "500GB"
      lxd_vm_config:
        limits.cpu: "4"
        limits.memory: "8GB"

    - role: icos.certbot2
      tags: cert
      certbot_name: wordpress
      certbot_domains: "{{ wordpress_domains }}"

    - role: icos.nginxsite
      tags: nginx
      nginxsite_name: wordpress
      nginxsite_file: files/wordpress.conf


- hosts: wordpress
  roles:
    - role: icos.lxd_guest
      tags: guest

  tasks:
    - name: Print wp-config warning
      debug:
        msg: |
          # Don't forget to add the following in your wp-config.php, after the
          # WP_DEBUG line. Otherwise you'll get redirect loops.
          if ( $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
          {
              $_SERVER['HTTPS']       = 'on';
              $_SERVER['SERVER_PORT'] = 443;
          }
