// Auto-generated by gen-data.ts from ../devops/cities.inventory/core.yml
import type { Inventory } from "../../lib/data.ts";
import { expr, tmpl } from "../../lib/ansible.ts";

export default {
  "all": {
    "vars": {
      "cpmeta_cities_domain": "citymeta.icos-cp.eu",
      "cpauth_cities_domain": "cityauth.icos-cp.eu",
      "cpdata_cities_domain": "citydata.icos-cp.eu",
      "cities_lxd_ip": "10.189.225.41",
      "rdflog_postgres_version": 15,
      "cpmeta_domains": [
        expr("cpmeta_cities_domain"),
      ],
      "cpdata_domains": [
        expr("cpdata_cities_domain"),
      ],
      "postgis_dbs": [
        expr("postgis_cities_db_name"),
      ],
      "restheart_dbs": [
        expr("restheart_cities_db_name"),
      ],
      "cpmeta_bbclient_name": "citymeta",
      "restheart_bbclient_name": "cityrestheart",
      "postgis_bbclient_name": "citypostgis",
      "rdflog_bbclient_name": "cityrdflog",
      "cities_datafast_path": "/data_fast",
      "cpmeta_rdfstorage_path": tmpl`${
        expr("cities_datafast_path")
      }/rdfStorage`,
      "showUnderConstruction": "false",
      "showCarbonBadge": "true",
    },
    "children": {
      "core_host": {
        "hosts": {
          "cities": null,
        },
        "vars": {
          "coreapp_bind_addr": "0.0.0.0",
          "restheart_bind_host": "0.0.0.0",
          "restheart_backup_enable": true,
          "rdflog_backup_enable": true,
          "rdflog_postgres_version": 15,
          "cpmeta_filestorage_target": tmpl`${expr("cpmeta_home")}/filestorage`,
          "cpmeta_backup_enable": true,
          "cpmeta_config_files": [
            "application_production.conf",
            "application_cities_amendment.conf",
            "application_cities_sensitive.conf",
          ],
          "cpdata_filestorage_target": "/data/dataAppStorage/",
          "cpdata_b2safe_dry_run": false,
          "cpdata_config_files": [
            "application_production.conf",
          ],
          "postgis_db_port": 5438,
          "postgis_hostname": "127.0.0.1",
          "postgis_backup_enable": true,
          "data_envries": [
            {
              "name": "ICOSCities",
              "restheart_url": tmpl`http://127.0.0.1:${
                expr("restheart_bind_port")
              }/${expr("restheart_cities_db_name")}`,
              "postgis_db_name": expr("postgis_cities_db_name"),
            },
          ],
        },
      },
      "core_server": {
        "hosts": {
          "fsicos2": null,
        },
        "vars": {
          "coreapp_httpproxy_host": "cities.lxd",
          "coreapp_host_ip": expr("cities_lxd_ip"),
          "cpmeta_nginxsite_name": "cpmeta-cities",
          "cpmeta_certbot_name": "cpmeta-cities",
          "cpdata_certbot_name": "cpdata-cities",
          "cpdata_nginxsite_name": "cpdata-cities",
          "restheart_host": "cities.lxd",
          "restheart_nginxsite_name": "restheart-cities",
          "restheart_certbot_name": "restheart-cities",
          "restheart_basic_auth": expr("city_restheart_basic_auth"),
          "restheart_domains": [
            expr("restheart_cities_domain"),
          ],
        },
      },
    },
  },
} satisfies Inventory;
