// Auto-generated by gen-data.ts from ../devops/roles/icos.registry/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  registry_home: unknown;
  registry_htpasswd_file: unknown;
  registry_users: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "registry_home": "/docker/registry",
  "registry_htpasswd_file": tmpl`${V.registry_home}/volumes/auth/htpasswd`,
  "registry_users": [],
} satisfies VarsFile;
