// Auto-generated by gen-data.ts from ../devops/roles/icos.registry/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "registry_home": "/docker/registry",
  "registry_htpasswd_file": "{{ registry_home }}/volumes/auth/htpasswd",
  "registry_users": [],
} satisfies VarsFile;
