// Auto-generated by gen-data.ts from ../devops/roles/icos.registry/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";

interface Self {
  registry_home: unknown;
  registry_htpasswd_file: unknown;
  registry_users: unknown;
}
const { V, tmpl } = context<Self>();

export default {
  "registry_home": "/docker/registry",
  "registry_htpasswd_file": tmpl`${V.registry_home}/volumes/auth/htpasswd`,
  "registry_users": [],
} satisfies VarsFile;
