// Auto-generated by gen-data.ts from ../devops/roles/icos.virtuoso/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";

interface Self {
  virtuoso_home: unknown;
  virtuoso_bind_host: unknown;
  virtuoso_http_port: unknown;
  virtuoso_host: unknown;
  virtuoso_port: unknown;
}
const { V, tmpl } = context<Self & ParamVars & VaultVars>();

export default {
  "virtuoso_home": tmpl`${V.docker_compose_home.default("/docker")}/virtuoso`,
  "virtuoso_bind_host": "127.0.0.1",
  "virtuoso_http_port": 8890,
  "virtuoso_host": V.virtuoso_bind_host,
  "virtuoso_port": V.virtuoso_http_port,
  "virtuoso_dba_pass": V.vault_virtuoso_dba_pass,
} satisfies VarsFile;
