// Auto-generated by gen-data.ts from ../devops/roles/icos.virtuoso/defaults/main.yml
import { type Restated } from "../../../../lib/data.ts";
import { type Globals } from "../../../../lib/globals.ts";
import { docker_compose_home } from "../../../../lib/paramvars.ts";
import { tmpl } from "../../../../lib/template.ts";
import { vault_virtuoso_dba_pass } from "../../../../lib/vaultvars.ts";
import { V, type Vars } from "../../../../roles/icos.virtuoso/_ctx.ts";

export default {
  "virtuoso_home": tmpl`${docker_compose_home.default("/docker")}/virtuoso`,
  "virtuoso_bind_host": "127.0.0.1",
  "virtuoso_http_port": 8890,
  "virtuoso_host": V.virtuoso_bind_host,
  "virtuoso_port": V.virtuoso_http_port,
  "virtuoso_dba_pass": vault_virtuoso_dba_pass
} satisfies Vars & Restated<Globals, "virtuoso_dba_pass">;
