// Auto-generated by gen-data.ts from ../devops/roles/icos.virtuoso/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  virtuoso_home: string;
  virtuoso_bind_host: string;
  virtuoso_http_port: string;
  virtuoso_host: string;
  virtuoso_port: string;
}
const { V, expr, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "virtuoso_home": tmpl`${
    expr("docker_compose_home | default('/docker')")
  }/virtuoso`,
  "virtuoso_bind_host": "127.0.0.1",
  "virtuoso_http_port": 8890,
  "virtuoso_host": V.virtuoso_bind_host,
  "virtuoso_port": V.virtuoso_http_port,
  "virtuoso_dba_pass": expr("vault_virtuoso_dba_pass"),
} satisfies VarsFile;
