// Auto-generated by gen-data.ts from ../devops/roles/icos.postgis/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "postgis_backup_enable": false,
  "postgis_home": "/docker/postgis",
  "postgresql_postgis_enable": true,
  "postgis_db_name": "postgres",
  "postgis_db_user": "postgres",
  "postgis_db_pass": tmpl("{{ postgis_admin_pass }}"),
  "postgis_postgres_version": 15,
  "postgis_package": "postgresql-15-postgis-3",
  "postgis_db_users": [
    {
      "username": "reader",
      "password": tmpl("{{ postgis_reader_pass }}"),
    },
    {
      "username": "writer",
      "password": tmpl("{{ postgis_writer_pass }}"),
    },
  ],
  "postgis_dbs": [
    tmpl("{{ postgis_icos_db_name }}"),
    tmpl("{{ postgis_sites_db_name }}"),
    tmpl("{{ postgis_cities_db_name }}"),
  ],
} satisfies VarsFile;
