// Auto-generated by gen-data.ts from ../devops/roles/icos.postgis/defaults/main.yml
import { type Restated } from "../../../../lib/data.ts";
import { type Globals, postgis_admin_pass, postgis_cities_db_name, postgis_icos_db_name, postgis_reader_pass, postgis_sites_db_name, postgis_writer_pass } from "../../../../lib/globals.ts";
import { type Vars } from "../../../../roles/icos.postgis/_ctx.ts";

export default {
  "postgis_backup_enable": false,
  "postgis_home": "/docker/postgis",
  "postgresql_postgis_enable": true,
  "postgis_db_name": "postgres",
  "postgis_db_user": "postgres",
  "postgis_db_pass": postgis_admin_pass,
  "postgis_postgres_version": 15,
  "postgis_package": "postgresql-15-postgis-3",
  "postgis_db_users": [
    {
      "username": "reader",
      "password": postgis_reader_pass
    },
    {
      "username": "writer",
      "password": postgis_writer_pass
    }
  ],
  "postgis_dbs": [
    postgis_icos_db_name,
    postgis_sites_db_name,
    postgis_cities_db_name
  ]
} satisfies Vars & Restated<Globals, "postgis_backup_enable" | "postgis_dbs">;
