// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.plausible/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  plausible_backup_enabled: boolean;
  plausible_domain: string;
  plausible_google_client_id: Tmpl;
  plausible_google_client_secret: Tmpl;
  plausible_home: string;
  plausible_mailer_email: Tmpl;
  plausible_port: number;
  plausible_postgres_password: Tmpl;
  plausible_secret: Tmpl;
  plausible_totp_key: Tmpl;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
