// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.plausible/{defaults,vars}/*.yml
// Per-role variable context: 10 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  plausible_backup_enabled: boolean;
  plausible_domain: string;
  plausible_google_client_id: string;
  plausible_google_client_secret: string;
  plausible_home: string;
  plausible_mailer_email: string;
  plausible_port: number;
  plausible_postgres_password: string;
  plausible_secret: string;
  plausible_totp_key: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
