// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.plausible/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  plausible_backup_enabled: boolean;
  plausible_domain: string;
  plausible_google_client_id: string;
  plausible_google_client_secret: string;
  plausible_home: string;
  plausible_mailer_email: string;
  plausible_port: number;
  plausible_postgres_password: string;
  plausible_secret: string;
  plausible_totp_key: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
