// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.flexpart/{defaults,vars}/*.yml
// Per-role variable context: 6 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  flexpart_container_prefix: string;
  flexpart_export_output_to: unknown;
  flexpart_image: string;
  flexpart_max_parallel: number;
  flexpart_output_directory: string;
  flexpart_user: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
