// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.flexpart/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  flexpart_container_prefix: string;
  flexpart_export_output_to: null;
  flexpart_image: string;
  flexpart_max_parallel: number;
  flexpart_output_directory: string;
  flexpart_user: string;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
