// Auto-generated by gen-data.ts from ../devops/roles/icos.matomo/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr } from "../../../../lib/ansible.ts";

export default {
  "matomo_home": "/opt/matomo",
  "matomo_port": 8702,
  "matomo_domain": "matomo.icos-cp.eu",
  "matomo_mysql_root_password": expr("vault_matomo_mysql_root_password"),
  "matomo_mysql_password": expr("vault_matomo_mysql_password"),
  "matomo_mysql_user": expr("vault_matomo_mysql_user"),
  "matomo_mysql_database_password": expr(
    "vault_matomo_mysql_database_password",
  ),
  "matomo_mysql_database_user": expr("vault_matomo_mysql_database_user"),
  "matomo_backup_enable": false,
} satisfies VarsFile;
