// Auto-generated by gen-data.ts from ../devops/roles/icos.matomo/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  matomo_home: unknown;
  matomo_port: unknown;
  matomo_domain: unknown;
  matomo_mysql_root_password: unknown;
  matomo_mysql_password: unknown;
  matomo_mysql_user: unknown;
  matomo_mysql_database_password: unknown;
  matomo_mysql_database_user: unknown;
  matomo_backup_enable: unknown;
}
const { V, expr } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "matomo_home": "/opt/matomo",
  "matomo_port": 8702,
  "matomo_domain": "matomo.icos-cp.eu",
  "matomo_mysql_root_password": V.vault_matomo_mysql_root_password,
  "matomo_mysql_password": V.vault_matomo_mysql_password,
  "matomo_mysql_user": V.vault_matomo_mysql_user,
  "matomo_mysql_database_password": expr(
    "vault_matomo_mysql_database_password",
  ),
  "matomo_mysql_database_user": V.vault_matomo_mysql_database_user,
  "matomo_backup_enable": false,
} satisfies VarsFile;
