// Auto-generated by gen-data.ts from ../devops/roles/icos.matomo/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "matomo_home": "/opt/matomo",
  "matomo_port": 8702,
  "matomo_domain": "matomo.icos-cp.eu",
  "matomo_mysql_root_password": tmpl("{{ vault_matomo_mysql_root_password }}"),
  "matomo_mysql_password": tmpl("{{ vault_matomo_mysql_password }}"),
  "matomo_mysql_user": tmpl("{{ vault_matomo_mysql_user }}"),
  "matomo_mysql_database_password": tmpl(
    "{{ vault_matomo_mysql_database_password }}",
  ),
  "matomo_mysql_database_user": tmpl("{{ vault_matomo_mysql_database_user }}"),
  "matomo_backup_enable": false,
} satisfies VarsFile;
