// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.zfsdocker/{defaults,vars}/*.yml
// Per-role variable context: 2 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { AllVars } from "../../lib/allvars.ts";

export interface Vars {
  zfsdocker_size: unknown;
  zfsdocker_zvol: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & AllVars
>();
