// Auto-generated by gen-data.ts from ../devops/roles/icos.restic/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, rawTmpl, tmpl } from "../../../../lib/ansible.ts";

export default {
  "restic_upgrade": expr("upgrade_everything | default(False) | bool"),
  "restic_architecture": expr(
    "fake_architecture | default(ansible_architecture)",
  ),
  "restic_version": expr("hostvars.localhost.restic_version"),
  "restic_url_map": {
    "armv6l": tmpl`https://github.com/restic/restic/releases/download/v${
      rawTmpl("{{restic_version}}")
    }/restic_${rawTmpl("{{restic_version}}")}_linux_arm.bz2`,
    "armv7l": tmpl`https://github.com/restic/restic/releases/download/v${
      rawTmpl("{{restic_version}}")
    }/restic_${rawTmpl("{{restic_version}}")}_linux_arm.bz2`,
    "aarch64": tmpl`https://github.com/restic/restic/releases/download/v${
      rawTmpl("{{restic_version}}")
    }/restic_${rawTmpl("{{restic_version}}")}_linux_arm64.bz2`,
    "x86_64": tmpl`https://github.com/restic/restic/releases/download/v${
      rawTmpl("{{restic_version}}")
    }/restic_${rawTmpl("{{restic_version}}")}_linux_amd64.bz2`,
  },
} satisfies VarsFile;
