- name: Create icos-auto-dnat source directory
  file:
    path: /opt/icos-auto-dnat
    state: directory

- name: Copy icos-auto-dnat source
  copy:
    src: "icos-auto-dnat/{{ item }}"
    dest: "/opt/icos-auto-dnat/{{ item }}"
  loop:
    - pyproject.toml
    - icos_auto_dnat.py
    - .gitignore
  register: _src

- name: Install icos-auto-dnat
  community.general.pipx:
    executable: pipx-global
    python: python3
    editable: true
    force: true
    name: "/opt/icos-auto-dnat/"
  when: _src.changed
  register: _pipx
  # pipx seems to always report changed when installing editable from file
  changed_when:
    - _pipx.changed | bool
    - _pipx.stdout | length > 0
    - _pipx.stdout.find('already seems to be installed') == -1

- name: Copy auto-dnat service files
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    lstrip_blocks: yes
  loop:
    - icos-auto-dnat.path
    - icos-auto-dnat.timer
    - icos-auto-dnat.service
  register: _systemd

- name: Reload systemd
  systemd:
    daemon-reload: yes
  when: _systemd.changed

- name: Start service
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: "{{ 'restarted' if _systemd.changed else 'started' }}"
  loop:
    - icos-auto-dnat.path
    - icos-auto-dnat.timer
