// Auto-generated by gen-data.ts from ../devops/roles/icos.filedrop/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "filedrop_port": 8039,
} satisfies VarsFile;
