// Auto-generated by gen-data.ts from ../devops/roles/icos.borg/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "borg_upgrade": expr("upgrade_everything | default(False) | bool"),
  "borg_version": expr("hostvars.localhost.borg_version"),
  "borg_url_map": {
    "x86_64": tmpl`https://github.com/borgbackup/borg/releases/download/${
      expr("borg_version")
    }/borg-linux-glibc${expr("borg_libc_version")}`,
  },
  "borg_bin": "/usr/local/bin/borg",
  "borg_libc_map": {
    "Ubuntu": {
      "22.04": "231",
      "24.04": "236",
    },
  },
  "borg_libc_version": expr(
    "borg_libc_map[ansible_distribution][ansible_distribution_version]",
  ),
} satisfies VarsFile;
