// Auto-generated by gen-data.ts from ../devops/roles/icos.borg/defaults/main.yml
import type { Vars } from "../../../../roles/icos.borg/_ctx.ts";
import type { Restated } from "../../../../lib/data.ts";
import { hostvar, jinja } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { SharedVars } from "../../../../lib/sharedvars.ts";

interface Self {
  borg_libc_map: unknown;
  borg_libc_version: unknown;
  borg_upgrade: unknown;
  borg_url_map: unknown;
  borg_version: unknown;
}
const { V, tmpl } = context<Self & Globals & BuiltinVars & SharedVars>();

export default {
  "borg_upgrade": V.upgrade_everything.default(false).bool(),
  "borg_version": hostvar("localhost").borg_version,
  "borg_url_map": {
    "x86_64":
      tmpl`https://github.com/borgbackup/borg/releases/download/${V.borg_version}/borg-linux-glibc${V.borg_libc_version}`,
  },
  "borg_bin": "/usr/local/bin/borg",
  "borg_libc_map": {
    "Ubuntu": {
      "22.04": "231",
      "24.04": "236",
    },
  },
  "borg_libc_version":
    jinja`{{ ${V.borg_libc_map}[${V.ansible_distribution}][${V.ansible_distribution_version}] }}`,
} satisfies Vars & Restated<Globals, "borg_bin">;
