// Auto-generated by gen-data.ts from ../devops/roles/icos.borg/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { hostvar } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  borg_upgrade: unknown;
  borg_version: unknown;
  borg_url_map: unknown;
  borg_libc_map: unknown;
  borg_libc_version: unknown;
}
const { V, expr, tmpl } = context<Self & AllVars>();

export default {
  "borg_upgrade": V.upgrade_everything.default(false).bool(),
  "borg_version": hostvar("localhost").borg_version,
  "borg_url_map": {
    "x86_64":
      tmpl`https://github.com/borgbackup/borg/releases/download/${V.borg_version}/borg-linux-glibc${V.borg_libc_version}`,
  },
  "borg_bin": "/usr/local/bin/borg",
  "borg_libc_map": {
    "Ubuntu": {
      "22.04": "231",
      "24.04": "236",
    },
  },
  "borg_libc_version": expr(
    "borg_libc_map[ansible_distribution][ansible_distribution_version]",
  ),
} satisfies VarsFile;
