// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.fairdolab/{defaults,vars}/*.yml
// Per-role variable context: 2 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  fairdolab_docker_listen: string;
  fairdolab_home: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
