// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.fairdolab/{defaults,vars}/*.yml
// Per-role variable context: 2 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";

export interface Vars {
  fairdolab_docker_listen: unknown;
  fairdolab_home: unknown;
}

export const { V } = context<
  Vars
>();
