// Auto-generated by gen-data.ts from ../devops/roles/icos.server/defaults/main.yml
import { type Vars } from "../../../../roles/icos.server/_ctx.ts";

export default {
  "fail2ban_config_files": [
    {
      "dest": "/etc/fail2ban/jail.d/sshd-allports.local",
      "content":
        "# Since we're running ssh on different ports that fail2ban is used to,\n# block all ports.\n[sshd]\nbanaction = iptables-allports\n",
    },
  ],
} satisfies Vars;
