// Auto-generated by gen-data.ts from ../devops/roles/icos.nginxforward/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "nginxforward_host": "127.0.0.1",
  "nginxforward_enable": true,
  "nginxforward_file": "nginxforward-default",
  "nginxforward_path_available":
    "/etc/nginx/sites-available/{{ nginxforward_name }}.conf",
  "nginxforward_path_enabled":
    "/etc/nginx/sites-enabled/{{ nginxforward_name }}.conf",
  "nginxforward_site_path": "/etc/letsencrypt/live/{{ nginxforward_cert }}",
  "nginxforward_cert_path": "{{ nginxforward_site_path }}/fullchain.pem",
  "nginxforward_key_path": "{{ nginxforward_site_path }}/privkey.pem",
  "nginxforward_cert_conf":
    "ssl_certificate {{ nginxforward_cert_path }};\nssl_certificate_key {{ nginxforward_key_path }};\n",
  "nginxforward_user_file": "/etc/nginx/passwords/{{ nginxforward_name }}.pass",
} satisfies VarsFile;
