// Auto-generated by gen-data.ts from ../devops/roles/icos.nginxforward/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  nginxforward_host: string;
  nginxforward_enable: string;
  nginxforward_file: string;
  nginxforward_path_available: string;
  nginxforward_path_enabled: string;
  nginxforward_site_path: string;
  nginxforward_cert_path: string;
  nginxforward_key_path: string;
  nginxforward_cert_conf: string;
  nginxforward_user_file: string;
}
const { V, expr, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "nginxforward_host": "127.0.0.1",
  "nginxforward_enable": true,
  "nginxforward_file": "nginxforward-default",
  "nginxforward_path_available": tmpl`/etc/nginx/sites-available/${
    expr("nginxforward_name")
  }.conf`,
  "nginxforward_path_enabled": tmpl`/etc/nginx/sites-enabled/${
    expr("nginxforward_name")
  }.conf`,
  "nginxforward_site_path": tmpl`/etc/letsencrypt/live/${
    expr("nginxforward_cert")
  }`,
  "nginxforward_cert_path": tmpl`${V.nginxforward_site_path}/fullchain.pem`,
  "nginxforward_key_path": tmpl`${V.nginxforward_site_path}/privkey.pem`,
  "nginxforward_cert_conf": tmpl`ssl_certificate ${V.nginxforward_cert_path};
ssl_certificate_key ${V.nginxforward_key_path};
`,
  "nginxforward_user_file": tmpl`/etc/nginx/passwords/${
    expr("nginxforward_name")
  }.pass`,
} satisfies VarsFile;
