# Directory on host where we'll store docker-compose.yml etc.
fdp_home: /fdpenvri

# The publicly reachable https domain we'll reverse proxy to docker.
fdp_domain: fdpdemo.envri.eu

# If enabled, turn the FDP into a FDP Index that can be contacted by and harvest metadata from other FDPs.
# Requires using the fairdatapoint-index-client Docker image.
index_enabled: false

# If enabled, ping the default FDP Index at https://home.fairdatapoint.org every 7 days.
ping_enabled: false
