// Auto-generated by gen-data.ts from ../devops/roles/icos.jbuild/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { hostvar } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  jbuild_registry: unknown;
  jbuild_edctl_host_name: unknown;
  jbuild_edctl_host_port: unknown;
  jbuild_jyctl_host_name: unknown;
  jbuild_jyctl_host_port: unknown;
  jbuild_rsync_host_name: unknown;
  jbuild_rsync_host_port: unknown;
  jbuild_rsync_user: unknown;
  jbuild_rrsync_bin: unknown;
}
const { V } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "jbuild_registry": {
    "url": "registry.icos-cp.eu",
    "username": "docker",
    "password": V.vault_registry_pass,
  },
  "jbuild_edctl_host_name": hostvar(V.jbuild_edctl_host).ansible_host,
  "jbuild_edctl_host_port": hostvar(V.jbuild_edctl_host).ansible_port,
  "jbuild_jyctl_host_name": hostvar(V.jbuild_jyctl_host).ansible_host,
  "jbuild_jyctl_host_port": hostvar(V.jbuild_jyctl_host).ansible_port,
  "jbuild_rsync_host_name": hostvar(V.jbuild_rsync_host).ansible_host,
  "jbuild_rsync_host_port": hostvar(V.jbuild_rsync_host).ansible_port,
  "jbuild_rsync_user": "project",
  "jbuild_rrsync_bin": "/usr/bin/rrsync",
} satisfies VarsFile;
