// Auto-generated by gen-data.ts from ../devops/roles/icos.jbuild/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "jbuild_registry": {
    "url": "registry.icos-cp.eu",
    "username": "docker",
    "password": tmpl("{{ vault_registry_pass }}"),
  },
  "jbuild_edctl_host_name": tmpl(
    "{{ hostvars[jbuild_edctl_host].ansible_host }}",
  ),
  "jbuild_edctl_host_port": tmpl(
    "{{ hostvars[jbuild_edctl_host].ansible_port }}",
  ),
  "jbuild_jyctl_host_name": tmpl(
    "{{ hostvars[jbuild_jyctl_host].ansible_host }}",
  ),
  "jbuild_jyctl_host_port": tmpl(
    "{{ hostvars[jbuild_jyctl_host].ansible_port }}",
  ),
  "jbuild_rsync_host_name": tmpl(
    "{{ hostvars[jbuild_rsync_host].ansible_host }}",
  ),
  "jbuild_rsync_host_port": tmpl(
    "{{ hostvars[jbuild_rsync_host].ansible_port }}",
  ),
  "jbuild_rsync_user": "project",
  "jbuild_rrsync_bin": "/usr/bin/rrsync",
} satisfies VarsFile;
