// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_vm/vars/ext4.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { jinja } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  lxd_vm_default_devices: unknown;
  lxd_vm_default_profiles: unknown;
  __base_config: unknown;
  __docker_config: unknown;
  lxd_vm_default_config: unknown;
}
const { V, tmpl } = context<Self & AllVars>();

export default {
  "lxd_vm_default_devices": {
    "root": {
      "path": "/",
      "type": "disk",
      "pool": V.lxd_vm_root_pool,
      "size": V.lxd_vm_root_size,
    },
  },
  "lxd_vm_default_profiles": [
    "default",
  ],
  "__base_config": {},
  "__docker_config":
    tmpl`${jinja`{% if ${V.lxd_vm_docker} -%}`} {"security.nesting": "true"} ${jinja`{% else %}`}{}${jinja`{% endif -%}`}`,
  "lxd_vm_default_config": V.__base_config.combine(V.__docker_config),
} satisfies VarsFile;
