// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_vm/vars/ext4.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, rawTmpl, tmpl } from "../../../../lib/ansible.ts";

export default {
  "lxd_vm_default_devices": {
    "root": {
      "path": "/",
      "type": "disk",
      "pool": expr("lxd_vm_root_pool"),
      "size": expr("lxd_vm_root_size"),
    },
  },
  "lxd_vm_default_profiles": [
    "default",
  ],
  "__base_config": {},
  "__docker_config": tmpl`${
    rawTmpl("{% if lxd_vm_docker -%}")
  } {"security.nesting": "true"} ${rawTmpl("{% else %}")}{}${
    rawTmpl("{% endif -%}")
  }`,
  "lxd_vm_default_config": expr("__base_config | combine(__docker_config)"),
} satisfies VarsFile;
