// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_vm/vars/ext4.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "lxd_vm_default_devices": {
    "root": {
      "path": "/",
      "type": "disk",
      "pool": "{{ lxd_vm_root_pool }}",
      "size": "{{ lxd_vm_root_size }}",
    },
  },
  "lxd_vm_default_profiles": [
    "default",
  ],
  "__base_config": {},
  "__docker_config":
    '{% if lxd_vm_docker -%} {"security.nesting": "true"} {% else %}{}{% endif -%}',
  "lxd_vm_default_config": "{{ __base_config | combine(__docker_config) }}",
} satisfies VarsFile;
