// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_vm/vars/zfs.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { jinja } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { SharedVars } from "../../../../lib/sharedvars.ts";

interface Self {
  __base_config: unknown;
  __docker_config: unknown;
  __docker_device: unknown;
  __lxd_vm_config: unknown;
  __lxd_vm_devices: unknown;
  __lxd_vm_profiles: unknown;
  __root_device: unknown;
  lxd_source: unknown;
  lxd_vm_config: unknown;
  lxd_vm_default_config: unknown;
  lxd_vm_default_devices: unknown;
  lxd_vm_default_profiles: unknown;
  lxd_vm_devices: unknown;
  lxd_vm_docker: unknown;
  lxd_vm_docker_size: unknown;
  lxd_vm_forward: unknown;
  lxd_vm_inventory_hostname: unknown;
  lxd_vm_ip: unknown;
  lxd_vm_port: unknown;
  lxd_vm_profiles: unknown;
  lxd_vm_root_pool: unknown;
  lxd_vm_root_size: unknown;
  lxd_vm_ubuntu_version: unknown;
  zfsdocker_name: unknown;
}
const { V, tmpl } = context<Self & SharedVars>();

export default {
  "__root_device": {
    "root": {
      "path": "/",
      "type": "disk",
      "pool": "default",
      "size": V.lxd_vm_root_size,
    },
  },
  "__docker_device": tmpl`${jinja`{% if ${V.lxd_vm_docker} -%}`} {"docker": {
  "path": "/var/lib/docker",
  "source": "${V.zfsdocker_zvol}",
  "type": "disk",
  "raw.mount.options": "user_subvol_rm_allowed" }}
${jinja`{% else -%}`}{}${jinja`{% endif -%}`}`,
  "lxd_vm_default_devices": V.__root_device.combine(V.__docker_device),
  "lxd_vm_default_profiles": [
    "default",
  ],
  "__base_config": {},
  "__docker_config":
    tmpl`${jinja`{% if ${V.lxd_vm_docker} -%}`} {"security.nesting": "true"} ${jinja`{% else %}`}{}${jinja`{% endif -%}`}`,
  "lxd_vm_default_config": V.__base_config.combine(V.__docker_config),
} satisfies VarsFile;
