// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_vm/vars/zfs.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "__root_device": {
    "root": {
      "path": "/",
      "type": "disk",
      "pool": "default",
      "size": "{{ lxd_vm_root_size }}",
    },
  },
  "__docker_device":
    '{% if lxd_vm_docker -%} {"docker": {\n  "path": "/var/lib/docker",\n  "source": "{{ zfsdocker_zvol }}",\n  "type": "disk",\n  "raw.mount.options": "user_subvol_rm_allowed" }}\n{% else -%}{}{% endif -%}',
  "lxd_vm_default_devices": "{{ __root_device | combine(__docker_device) }}",
  "lxd_vm_default_profiles": [
    "default",
  ],
  "__base_config": {},
  "__docker_config":
    '{% if lxd_vm_docker -%} {"security.nesting": "true"} {% else %}{}{% endif -%}',
  "lxd_vm_default_config": "{{ __base_config | combine(__docker_config) }}",
} satisfies VarsFile;
