// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.eurocom/{defaults,vars}/*.yml
// Per-role variable context: 4 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  eurocom_auth_file: string;
  eurocom_data_home: string;
  eurocom_domain: string;
  eurocom_web_root: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
