// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.eurocom/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  eurocom_auth_file: unknown;
  eurocom_data_home: unknown;
  eurocom_domain: unknown;
  eurocom_web_root: unknown;
}

export const { V } = context<
  Vars & ParamVars
>();
