// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.eurocom/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  eurocom_auth_file: string;
  eurocom_data_home: string;
  eurocom_domain: string;
  eurocom_web_root: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
