// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_guest/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "lxd_guest_root_keys": null,
} satisfies VarsFile;
