// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_guest/defaults/main.yml
import type { Vars } from "../../../../roles/icos.lxd_guest/_ctx.ts";
import type { Restated } from "../../../../lib/data.ts";
import type { Globals } from "../../../../lib/globals.ts";

export default {
  "lxd_guest_root_keys": null,
} satisfies Vars & Restated<Globals, "lxd_guest_root_keys">;
