// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.pipx/{defaults,vars}/*.yml
// Per-role variable context: 2 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  pipx_home: string;
  pipx_upgrade: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
