// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.pipx/{defaults,vars}/*.yml
// Per-role variable context: 2 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  pipx_home: string;
  pipx_upgrade: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const pipx_home = vref("pipx_home");
export const pipx_upgrade = vref("pipx_upgrade");
