// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.postgis/{defaults,vars}/*.yml
// Per-role variable context: 10 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  postgis_backup_enable: boolean;
  postgis_db_name: string;
  postgis_db_pass: string;
  postgis_db_user: string;
  postgis_db_users: unknown[];
  postgis_dbs: unknown[];
  postgis_home: string;
  postgis_package: string;
  postgis_postgres_version: number;
  postgresql_postgis_enable: boolean;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
