// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.postgis/{defaults,vars}/*.yml
// Per-role variable context: 8 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  postgis_db_name: string;
  postgis_db_pass: string;
  postgis_db_user: string;
  postgis_db_users: unknown[];
  postgis_home: string;
  postgis_package: string;
  postgis_postgres_version: number;
  postgresql_postgis_enable: boolean;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
