// Auto-generated by gen-data.ts from ../devops/roles/icos.doi/defaults/main.yml
import { coreapp_bind_addr, coreapp_httpproxy_host, cpmeta_icos_domain } from "../../../../lib/globals.ts";
import { type Vars } from "../../../../roles/icos.doi/_ctx.ts";

export default {
  "doi_user": "doi",
  "doi_home": "/home/doi",
  "doi_servicename": "doi",
  "doi_port": 8079,
  "doi_bind_addr": coreapp_bind_addr,
  "doi_host": coreapp_httpproxy_host,
  "doi_meta_domain": cpmeta_icos_domain
} satisfies Vars;
