// Auto-generated by gen-data.ts from ../devops/roles/icos.doi/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  doi_user: unknown;
  doi_home: unknown;
  doi_servicename: unknown;
  doi_port: unknown;
  doi_bind_addr: unknown;
  doi_host: unknown;
  doi_meta_domain: unknown;
}
const { V } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "doi_user": "doi",
  "doi_home": "/home/doi",
  "doi_servicename": "doi",
  "doi_port": 8079,
  "doi_bind_addr": V.coreapp_bind_addr,
  "doi_host": V.coreapp_httpproxy_host,
  "doi_meta_domain": V.cpmeta_icos_domain,
} satisfies VarsFile;
