// Auto-generated by gen-data.ts from ../devops/roles/icos.uv/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "uv_home": "/opt/uv",
  "uv_upgrade": tmpl("{{ upgrade_everything | default(False) | bool }}"),
  "uv_architecture": tmpl(
    "{{ fake_architecture | default(ansible_architecture) }}",
  ),
  "uv_version": tmpl("{{ hostvars.localhost.uv_version }}"),
  "uv_url_map": {
    "armv6l": tmpl(
      "https://github.com/astral-sh/uv/releases/download/{{ uv_version }}/uv-arm-unknown-linux-musleabihf.tar.gz",
    ),
    "armv7l": tmpl(
      "https://github.com/astral-sh/uv/releases/download/{{ uv_version }}/uv-armv7-unknown-linux-gnueabihf.tar.gz",
    ),
    "aarch64": tmpl(
      "https://github.com/astral-sh/uv/releases/download/{{ uv_version }}/uv-aarch64-unknown-linux-gnu.tar.gz",
    ),
    "x86_64": tmpl(
      "https://github.com/astral-sh/uv/releases/download/{{ uv_version }}/uv-x86_64-unknown-linux-gnu.tar.gz",
    ),
  },
} satisfies VarsFile;
