// Auto-generated by gen-data.ts from ../devops/roles/icos.cpmeta/defaults/main.yml
import type { Vars } from "../../../../roles/icos.cpmeta/_ctx.ts";
import type { Restated } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";

const { V } = context<Globals & VaultVars>();

export default {
  "cpmeta_user": "cpmeta",
  "cpmeta_home": "/home/cpmeta",
  "cpmeta_rdfstorage_path": "./rdfStorage",
  "cpmeta_servicename": "cpmeta",
  "cpmeta_readonly_mode": false,
  "cpmeta_db_name": "rdflog",
  "cpmeta_db_user": "rdflog",
  "cpmeta_db_port": 2345,
  "cpmeta_db_pass": V.rdflog_db_pass,
  "doi_password_icos": V.vault_doi_password,
  "cpmeta_backup_enable": true,
  "cpmeta_bind_addr": V.coreapp_bind_addr,
  "cpmeta_host": V.coreapp_httpproxy_host,
  "cpmeta_port": 9094,
} satisfies
  & Vars
  & Restated<Globals, "cpmeta_rdfstorage_path" | "cpmeta_backup_enable">;
