// Auto-generated by gen-data.ts from ../devops/roles/icos.cpmeta/defaults/main.yml
import { type Restated } from "../../../../lib/data.ts";
import { coreapp_bind_addr, coreapp_httpproxy_host, type Globals, rdflog_db_pass } from "../../../../lib/globals.ts";
import { vault_doi_password } from "../../../../lib/vaultvars.ts";
import { type Vars } from "../../../../roles/icos.cpmeta/_ctx.ts";

export default {
  "cpmeta_user": "cpmeta",
  "cpmeta_home": "/home/cpmeta",
  "cpmeta_rdfstorage_path": "./rdfStorage",
  "cpmeta_servicename": "cpmeta",
  "cpmeta_readonly_mode": false,
  "cpmeta_db_name": "rdflog",
  "cpmeta_db_user": "rdflog",
  "cpmeta_db_port": 2345,
  "cpmeta_db_pass": rdflog_db_pass,
  "doi_password_icos": vault_doi_password,
  "cpmeta_backup_enable": true,
  "cpmeta_bind_addr": coreapp_bind_addr,
  "cpmeta_host": coreapp_httpproxy_host,
  "cpmeta_port": 9094
} satisfies Vars & Restated<Globals, "cpmeta_rdfstorage_path" | "cpmeta_backup_enable">;
