// Auto-generated by gen-data.ts from ../devops/roles/icos.cpmeta/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  cpmeta_user: unknown;
  cpmeta_home: unknown;
  cpmeta_servicename: unknown;
  cpmeta_readonly_mode: unknown;
  cpmeta_db_name: unknown;
  cpmeta_db_user: unknown;
  cpmeta_db_port: unknown;
  cpmeta_db_pass: unknown;
  doi_password_icos: unknown;
  cpmeta_bind_addr: unknown;
  cpmeta_host: unknown;
  cpmeta_port: unknown;
}
const { V } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "cpmeta_user": "cpmeta",
  "cpmeta_home": "/home/cpmeta",
  "cpmeta_rdfstorage_path": "./rdfStorage",
  "cpmeta_servicename": "cpmeta",
  "cpmeta_readonly_mode": false,
  "cpmeta_db_name": "rdflog",
  "cpmeta_db_user": "rdflog",
  "cpmeta_db_port": 2345,
  "cpmeta_db_pass": V.rdflog_db_pass,
  "doi_password_icos": V.vault_doi_password,
  "cpmeta_backup_enable": true,
  "cpmeta_bind_addr": V.coreapp_bind_addr,
  "cpmeta_host": V.coreapp_httpproxy_host,
  "cpmeta_port": 9094,
} satisfies VarsFile;
