// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.stiltweb/{defaults,vars}/*.yml
// Per-role variable context: 9 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, type VarRef, varProxy } from "../../lib/template.ts";

export interface Vars {
  stiltweb_akka_hostname: Tmpl;
  stiltweb_akka_port: number;
  stiltweb_bindir: Tmpl;
  stiltweb_certbot_name: string;
  stiltweb_home: Tmpl;
  stiltweb_java: string;
  stiltweb_jre_package: string;
  stiltweb_nginxsite_name: string;
  stiltweb_username: string;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } =
  new Proxy({}, { get: (_t, name: string) => varProxy(name) }) as
    { readonly [K in keyof Vars]: VarRef<Vars[K]> };
