// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.stiltweb/{defaults,vars}/*.yml
// Per-role variable context: 9 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  stiltweb_akka_hostname: string;
  stiltweb_akka_port: number;
  stiltweb_bindir: string;
  stiltweb_certbot_name: string;
  stiltweb_home: string;
  stiltweb_java: string;
  stiltweb_jre_package: string;
  stiltweb_nginxsite_name: string;
  stiltweb_username: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
