// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.borg/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  borg_libc_map: Record<string, Record<string, string>>;
  borg_libc_version: Tmpl;
  borg_upgrade: Tmpl;
  borg_url_map: Record<string, Tmpl>;
  borg_version: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const borg_libc_map = vref("borg_libc_map");
export const borg_libc_version = vref("borg_libc_version");
export const borg_upgrade = vref("borg_upgrade");
export const borg_url_map = vref("borg_url_map");
export const borg_version = vref("borg_version");
