// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.borg/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  borg_libc_map: Record<string, unknown>;
  borg_libc_version: string;
  borg_upgrade: string;
  borg_url_map: Record<string, unknown>;
  borg_version: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
