services:
  fdp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./application.yml:/fdp/application.yml:ro
      - ./rdf/data:/fdp/fdp-store
    restart: unless-stopped

  fdp-client:
    image: fairdata/fairdatapoint-client:1.16
    ports:
      - 80:80
    environment:
      - FDP_HOST=fdp
    volumes:
      # Mount new logo file to assets in the container
      - ./eh-next_logo.png:/usr/share/nginx/html/assets/my-logo.png:ro
      # Mount _variables.scss so that styles are regenerated
      - ./_variables.scss:/src/scss/custom/_variables.scss:ro
    restart: unless-stopped

  mongo:
    image: mongo:4.2.24
    volumes:
      - ./mongo/data:/data/db
    restart: unless-stopped
