// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.mailman/{defaults,vars}/*.yml
// Per-role variable context: 26 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  mailman_admin_email: string;
  mailman_build_core: string;
  mailman_build_web: string;
  mailman_certbot_name: string;
  mailman_core_ipv4: string;
  mailman_database_ipv4: string;
  mailman_django_settings: string;
  mailman_home: string;
  mailman_host_ipv4: string;
  mailman_hyperkitty_api_key: string;
  mailman_nginxsite_file: string;
  mailman_nginxsite_name: string;
  mailman_postfix_config: unknown[];
  mailman_postgres_password: string;
  mailman_rest_allow_deny: unknown;
  mailman_rest_port: number;
  mailman_rest_user: string;
  mailman_serve_from_domain: string;
  mailman_subnet: string;
  mailman_user: string;
  mailman_version: string;
  mailman_volume_core: string;
  mailman_volume_database: string;
  mailman_volume_web: string;
  mailman_web_ipv4: string;
  mailman_web_secret_key: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
