// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.mailman/{defaults,vars}/*.yml
// Per-role variable context: 26 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, type VarRef, varProxy } from "../../lib/template.ts";

export interface Vars {
  mailman_admin_email: Tmpl;
  mailman_build_core: Tmpl;
  mailman_build_web: Tmpl;
  mailman_certbot_name: string;
  mailman_core_ipv4: string;
  mailman_database_ipv4: string;
  mailman_django_settings: Tmpl;
  mailman_home: string;
  mailman_host_ipv4: string;
  mailman_hyperkitty_api_key: Tmpl;
  mailman_nginxsite_file: string;
  mailman_nginxsite_name: string;
  mailman_postfix_config: unknown;
  mailman_postgres_password: Tmpl;
  mailman_rest_allow_deny: null;
  mailman_rest_port: number;
  mailman_rest_user: string;
  mailman_serve_from_domain: Tmpl;
  mailman_subnet: string;
  mailman_user: string;
  mailman_version: string;
  mailman_volume_core: Tmpl;
  mailman_volume_database: Tmpl;
  mailman_volume_web: Tmpl;
  mailman_web_ipv4: string;
  mailman_web_secret_key: Tmpl;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } =
  new Proxy({}, { get: (_t, name: string) => varProxy(name) }) as
    { readonly [K in keyof Vars]: VarRef<Vars[K]> };
