// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.cpdata/{defaults,vars}/*.yml
// Per-role variable context: 17 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  cpdata_bind_addr: Tmpl;
  cpdata_cpuser_secret_salt: Tmpl;
  cpdata_dlreporter_pass: Tmpl;
  cpdata_etcfacade_secret: Tmpl;
  cpdata_home: string;
  cpdata_host: Tmpl;
  cpdata_irods_pass: Tmpl;
  cpdata_jre_package: string;
  cpdata_meta_addr: string;
  cpdata_meta_port: number;
  cpdata_netcdf_folder: unknown;
  cpdata_pgreslog_admin_pass: Tmpl;
  cpdata_pgreslog_reader_pass: Tmpl;
  cpdata_pgreslog_writer_pass: Tmpl;
  cpdata_port: number;
  cpdata_service: string;
  cpdata_user: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const cpdata_bind_addr = vref("cpdata_bind_addr");
export const cpdata_cpuser_secret_salt = vref("cpdata_cpuser_secret_salt");
export const cpdata_dlreporter_pass = vref("cpdata_dlreporter_pass");
export const cpdata_etcfacade_secret = vref("cpdata_etcfacade_secret");
export const cpdata_home = vref("cpdata_home");
export const cpdata_host = vref("cpdata_host");
export const cpdata_irods_pass = vref("cpdata_irods_pass");
export const cpdata_jre_package = vref("cpdata_jre_package");
export const cpdata_meta_addr = vref("cpdata_meta_addr");
export const cpdata_meta_port = vref("cpdata_meta_port");
export const cpdata_netcdf_folder = vref("cpdata_netcdf_folder");
export const cpdata_pgreslog_admin_pass = vref("cpdata_pgreslog_admin_pass");
export const cpdata_pgreslog_reader_pass = vref("cpdata_pgreslog_reader_pass");
export const cpdata_pgreslog_writer_pass = vref("cpdata_pgreslog_writer_pass");
export const cpdata_port = vref("cpdata_port");
export const cpdata_service = vref("cpdata_service");
export const cpdata_user = vref("cpdata_user");
