// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.cpdata/{defaults,vars}/*.yml
// Per-role variable context: 17 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

export interface Vars {
  cpdata_bind_addr: string;
  cpdata_cpuser_secret_salt: string;
  cpdata_dlreporter_pass: string;
  cpdata_etcfacade_secret: string;
  cpdata_home: string;
  cpdata_host: string;
  cpdata_irods_pass: string;
  cpdata_jre_package: string;
  cpdata_meta_addr: string;
  cpdata_meta_port: string;
  cpdata_netcdf_folder: string;
  cpdata_pgreslog_admin_pass: string;
  cpdata_pgreslog_reader_pass: string;
  cpdata_pgreslog_writer_pass: string;
  cpdata_port: string;
  cpdata_service: string;
  cpdata_user: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars
>();
