// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.rspamd/{defaults,vars}/*.yml
// Per-role variable context: 0 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";

// deno-lint-ignore no-empty-interface
export interface Vars {}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars
>();
