// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.rspamd/{defaults,vars}/*.yml
// Per-role variable context: 0 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

// deno-lint-ignore no-empty-interface
export interface Vars {}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars
>();
