// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.rsyncd/{defaults,vars}/*.yml
// Per-role variable context: 1 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  rsyncd_enable: boolean;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
