// Auto-generated by gen-data.ts from ../devops/roles/icos.bbserver/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";

interface Self {
  bbserver_home: unknown;
  bbserver_repo_home: unknown;
  bbserver_monitor_home: unknown;
  bbserver_textfiles: unknown;
}
const { V, tmpl } = context<Self>();

export default {
  "bbserver_user": "bbserver",
  "bbserver_home": "/home/bbserver",
  "bbserver_repo_home": tmpl`${V.bbserver_home}/repos`,
  "bbserver_monitor_home": tmpl`${V.bbserver_home}/monitor`,
  "bbserver_textfiles": "/opt/node_exporter/textfiles",
} satisfies VarsFile;
