// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.docker_utils/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  dive_architecture: Tmpl;
  dive_url_map: Record<string, Tmpl>;
  dive_version: Tmpl;
  lazydocker_architecture: Tmpl;
  lazydocker_url_map: Record<string, Tmpl>;
  lazydocker_version: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const dive_architecture = vref("dive_architecture");
export const dive_url_map = vref("dive_url_map");
export const dive_version = vref("dive_version");
export const lazydocker_architecture = vref("lazydocker_architecture");
export const lazydocker_url_map = vref("lazydocker_url_map");
export const lazydocker_version = vref("lazydocker_version");
