// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.docker_utils/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";

export interface Vars {
  dive_architecture: unknown;
  dive_url_map: unknown;
  dive_version: unknown;
  lazydocker_architecture: unknown;
  lazydocker_url_map: unknown;
  lazydocker_version: unknown;
}

export const { V, tmpl } = context<
  Vars
>();
