// Auto-generated by gen-data.ts from ../devops/roles/icos.telegraf/meta/main.yml
import { type Meta } from "../../../../lib/data.ts";

export default {
  "dependencies": [
    {
      "role": "icos.just",
      "tags": "just"
    }
  ]
} satisfies Meta;
