// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.restic_server/{defaults,vars}/*.yml
// Per-role variable context: 11 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  restic_server_architecture: string;
  restic_server_data: unknown;
  restic_server_exec: string;
  restic_server_home: string;
  restic_server_htpasswd: string;
  restic_server_listen: number;
  restic_server_upgrade: string;
  restic_server_url_map: Record<string, unknown>;
  restic_server_user: string;
  restic_server_users: unknown[];
  restic_server_version: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
