// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.restic_server/{defaults,vars}/*.yml
// Per-role variable context: 11 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, type VarRef, varProxy } from "../../lib/template.ts";

export interface Vars {
  restic_server_architecture: Tmpl;
  restic_server_data: null;
  restic_server_exec: Tmpl;
  restic_server_home: string;
  restic_server_htpasswd: Tmpl;
  restic_server_listen: number;
  restic_server_upgrade: Tmpl;
  restic_server_url_map: Record<string, Tmpl>;
  restic_server_user: string;
  restic_server_users: unknown;
  restic_server_version: Tmpl;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } =
  new Proxy({}, { get: (_t, name: string) => varProxy(name) }) as
    { readonly [K in keyof Vars]: VarRef<Vars[K]> };
