// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.postgresql/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  postgresql_bin: unknown;
  postgresql_confd: unknown;
  postgresql_etc: unknown;
  postgresql_home: unknown;
  postgresql_listen_addresses: unknown;
  postgresql_pg_hba: unknown;
  postgresql_pg_stat_enable: unknown;
  postgresql_postgis_enable: unknown;
  postgresql_postgres_password: unknown;
  postgresql_ssh_keys: unknown;
}

export const { V, tmpl } = context<
  Vars & BuiltinVars & ParamVars
>();
