// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.postgresql/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  postgresql_bin: Tmpl;
  postgresql_confd: Tmpl;
  postgresql_etc: Tmpl;
  postgresql_home: string;
  postgresql_listen_addresses: null;
  postgresql_pg_hba: Tmpl;
  postgresql_pg_stat_enable: boolean;
  postgresql_postgis_enable: boolean;
  postgresql_postgres_password: null;
  postgresql_ssh_keys: null;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const postgresql_bin = vref("postgresql_bin");
export const postgresql_confd = vref("postgresql_confd");
export const postgresql_etc = vref("postgresql_etc");
export const postgresql_home = vref("postgresql_home");
export const postgresql_listen_addresses = vref("postgresql_listen_addresses");
export const postgresql_pg_hba = vref("postgresql_pg_hba");
export const postgresql_pg_stat_enable = vref("postgresql_pg_stat_enable");
export const postgresql_postgis_enable = vref("postgresql_postgis_enable");
export const postgresql_postgres_password = vref(
  "postgresql_postgres_password",
);
export const postgresql_ssh_keys = vref("postgresql_ssh_keys");
