// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.postgresql/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  postgresql_bin: string;
  postgresql_confd: string;
  postgresql_etc: string;
  postgresql_home: string;
  postgresql_listen_addresses: unknown;
  postgresql_pg_hba: string;
  postgresql_pg_stat_enable: boolean;
  postgresql_postgis_enable: boolean;
  postgresql_postgres_password: unknown;
  postgresql_ssh_keys: unknown;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
