// Auto-generated by gen-data.ts from ../devops/roles/icos.quince/vars/main.yml
import { type VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/template.ts";
import {
  quince_home,
  quince_user,
} from "../../../../roles/icos.quince/_ctx.ts";

export default {
  "bbclient_name": "quince",
  "bbclient_user": quince_user,
  "bbclient_home": tmpl`${quince_home}/.bbclient`,
} satisfies VarsFile;
