// Auto-generated by gen-data.ts from ../devops/roles/icos.quince/vars/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";

interface Self {
  bbclient_name: unknown;
  bbclient_user: unknown;
  quince_backup_enable: unknown;
  quince_filestore: unknown;
  quince_home: unknown;
  quince_jdk_version: unknown;
  quince_log_file: unknown;
  quince_slack_url: unknown;
  quince_tomcat_home: unknown;
  quince_tomcat_url: unknown;
  quince_user: unknown;
}
const { V, tmpl } = context<Self>();

export default {
  "bbclient_name": "quince",
  "bbclient_user": V.quince_user,
  "bbclient_home": tmpl`${V.quince_home}/.bbclient`,
} satisfies VarsFile;
