// Auto-generated by gen-data.ts from ../devops/roles/icos.postgresql/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  postgresql_postgis_enable: string;
  postgresql_pg_stat_enable: string;
  postgresql_postgres_password: string;
  postgresql_listen_addresses: string;
  postgresql_ssh_keys: string;
  postgresql_etc: string;
  postgresql_confd: string;
  postgresql_pg_hba: string;
  postgresql_home: string;
  postgresql_bin: string;
}
const { V, expr, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "postgresql_postgis_enable": false,
  "postgresql_pg_stat_enable": true,
  "postgresql_postgres_password": null,
  "postgresql_listen_addresses": null,
  "postgresql_ssh_keys": null,
  "postgresql_etc": tmpl`/etc/postgresql/${expr("postgresql_version")}/main`,
  "postgresql_confd": tmpl`${V.postgresql_etc}/conf.d`,
  "postgresql_pg_hba": tmpl`${V.postgresql_etc}/pg_hba.conf`,
  "postgresql_home": "/var/lib/postgresql",
  "postgresql_bin": tmpl`${V.postgresql_home}/bin`,
} satisfies VarsFile;
