// Auto-generated by gen-data.ts from ../devops/roles/icos.postgresql/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "postgresql_postgis_enable": false,
  "postgresql_pg_stat_enable": true,
  "postgresql_postgres_password": null,
  "postgresql_listen_addresses": null,
  "postgresql_ssh_keys": null,
  "postgresql_etc": tmpl`/etc/postgresql/${expr("postgresql_version")}/main`,
  "postgresql_confd": tmpl`${expr("postgresql_etc")}/conf.d`,
  "postgresql_pg_hba": tmpl`${expr("postgresql_etc")}/pg_hba.conf`,
  "postgresql_home": "/var/lib/postgresql",
  "postgresql_bin": tmpl`${expr("postgresql_home")}/bin`,
} satisfies VarsFile;
