// Generate typed TS modules for the non-executable data files, mirroring the
// devops layout under data/:
//   roles/<r>/meta/*.yml      -> data/roles/<r>/meta/*.ts        (Meta)
//   roles/<r>/{defaults,vars} -> data/roles/<r>/{defaults,vars}  (VarsFile)
//   *.inventory/**            -> data/*.inventory/**             (Inventory)
//   host_vars,group_vars/**   -> data/{host_vars,group_vars}/**  (VarsFile)
//
// Each module is `export default <data literal> satisfies <Type>`, rendering
// back to semantically-identical YAML (verified by verify.ts).
//
// Encrypted Ansible-vault files ($ANSIBLE_VAULT) and files with inline !vault
// tags are skipped — they are ciphertext, not data, and must stay as .yml.
//
//   deno run --allow-read --allow-write --allow-env gen-data.ts
import { parse } from "npm:yaml@2";

const devops = new URL("../devops/", import.meta.url);
const dataOut = new URL("./data/", import.meta.url);

/** Pick the `satisfies` type + its export name for a given relative path. */
function typeFor(rel: string): { name: string } {
  if (/\/meta\//.test(rel)) return { name: "Meta" };
  if (/\.inventory\//.test(rel)) return { name: "Inventory" };
  return { name: "VarsFile" }; // defaults, vars, host_vars, group_vars
}

/** Collect every candidate data .yml under devops. */
async function dataYmls(): Promise<string[]> {
  const out: string[] = [];
  async function walk(dir: URL, rel: string) {
    for await (const e of Deno.readDir(dir)) {
      const childRel = rel ? `${rel}/${e.name}` : e.name;
      if (e.isDirectory) {
        await walk(new URL(`${e.name}/`, dir), childRel);
      } else if (e.isFile && e.name.endsWith(".yml")) {
        out.push(childRel);
      }
    }
  }
  // roles/<r>/{meta,defaults,vars}
  for await (const role of Deno.readDir(new URL("roles/", devops))) {
    if (!role.isDirectory) continue;
    for (const sub of ["meta", "defaults", "vars"]) {
      await walk(
        new URL(`roles/${role.name}/${sub}/`, devops),
        `roles/${role.name}/${sub}`,
      ).catch(() => {});
    }
  }
  // *.inventory/**, host_vars/**, group_vars/**, fixes/vars/** (vars_files data)
  for await (const e of Deno.readDir(devops)) {
    if (!e.isDirectory) continue;
    if (
      e.name.endsWith(".inventory") || e.name === "host_vars" ||
      e.name === "group_vars"
    ) {
      await walk(new URL(`${e.name}/`, devops), e.name);
    }
  }
  await walk(new URL("fixes/vars/", devops), "fixes/vars").catch(() => {});
  return out;
}

let generated = 0;
const skipped: string[] = [];

for (const rel of await dataYmls()) {
  const raw = await Deno.readTextFile(new URL(rel, devops));
  if (raw.includes("$ANSIBLE_VAULT")) {
    skipped.push(`${rel} (encrypted vault)`);
    continue;
  }
  if (/!vault|!unsafe/.test(raw)) {
    skipped.push(`${rel} (inline !vault tag)`);
    continue;
  }
  let doc: unknown;
  try {
    // Parse as YAML 1.1 (like Ansible's PyYAML and verify.ts), so `yes`/`no`
    // become booleans rather than the strings "yes"/"no".
    doc = parse(raw, { version: "1.1" });
  } catch (e) {
    skipped.push(`${rel} (parse error: ${e instanceof Error ? e.message : e})`);
    continue;
  }
  if (doc === null || doc === undefined) {
    skipped.push(`${rel} (empty)`);
    continue;
  }

  const { name } = typeFor(rel);
  const ups = "../".repeat(rel.split("/").length); // dir depth + 1 (for data/)
  const literal = JSON.stringify(doc, null, 2);
  const out = `// Auto-generated by gen-data.ts from ../devops/${rel}\n` +
    `import type { ${name} } from "${ups}lib/data.ts";\n\n` +
    `export default ${literal} satisfies ${name};\n`;

  const outUrl = new URL(rel.replace(/\.yml$/, ".ts"), dataOut);
  await Deno.mkdir(new URL(".", outUrl), { recursive: true });
  await Deno.writeTextFile(outUrl, out);
  generated++;
}

console.log(`Generated ${generated} data modules; skipped ${skipped.length}:`);
for (const s of skipped) console.log(`  - ${s}`);
