// Generate per-role variable contexts: roles/<role>/_ctx.ts
//
// Reads each role's ../devops/roles/<role>/{defaults,vars}/*.yml, collects the
// top-level variable names with inferred types, and emits a `Vars` interface +
// a `context<Vars>()` accessor. Idempotent; re-run after editing role defaults.
//
//   deno run --allow-read --allow-write gen-contexts.ts
import { parse } from "yaml";

const devopsRoles = new URL("../devops/roles/", import.meta.url);
const tsRoles = new URL("./roles/", import.meta.url);

/** Interface member names declared in a lib file (to avoid intersection clashes). */
async function declaredNames(path: string): Promise<Set<string>> {
  const names = new Set<string>();
  const text = await Deno.readTextFile(new URL(path, import.meta.url));
  for (const m of text.matchAll(/^\s{2}([A-Za-z_$][\w$]*)\??:/gm)) {
    names.add(m[1]);
  }
  return names;
}

// A role's own var that is also a global/builtin would make `Vars & Globals &
// Builtins` collide (e.g. boolean & string -> never), so own vars exclude them;
// they remain reachable through the widening with the global/builtin type.
const reserved = new Set([
  ...await declaredNames("./lib/globals.ts"),
  ...await declaredNames("./lib/builtins.ts"),
]);

/** Infer a TS type string from a YAML default value. */
function tsType(v: unknown): string {
  if (typeof v === "boolean") return "boolean";
  if (typeof v === "number") return "number";
  if (typeof v === "string") return "string";
  if (Array.isArray(v)) return "unknown[]";
  if (v && typeof v === "object") return "Record<string, unknown>";
  return "unknown"; // null / undefined (empty `key:`)
}

/** A valid bare TS identifier needs no quoting as an interface key. */
const ident = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

let generated = 0;
for await (const role of Deno.readDir(devopsRoles)) {
  if (!role.isDirectory) continue;

  const vars = new Map<string, string>(); // name -> ts type
  for (const sub of ["defaults", "vars"]) {
    const dir = new URL(`${role.name}/${sub}/`, devopsRoles);
    let entries: Deno.DirEntry[] = [];
    try {
      for await (const f of Deno.readDir(dir)) entries.push(f);
    } catch {
      continue;
    }
    for (const f of entries) {
      if (!f.isFile || !f.name.endsWith(".yml")) continue;
      let doc: unknown;
      try {
        doc = parse(await Deno.readTextFile(new URL(f.name, dir)));
      } catch {
        continue;
      }
      if (doc && typeof doc === "object" && !Array.isArray(doc)) {
        for (const [k, v] of Object.entries(doc as Record<string, unknown>)) {
          if (reserved.has(k)) continue; // covered by Globals/Builtins widening
          // defaults win over vars only if vars hasn't set a non-unknown type
          if (!vars.has(k) || vars.get(k) === "unknown") {
            vars.set(k, tsType(v));
          }
        }
      }
    }
  }

  // Ensure the role's TS dir exists (it does for ported roles; create otherwise).
  const outDir = new URL(`${role.name}/`, tsRoles);
  try {
    await Deno.mkdir(outDir, { recursive: true });
  } catch { /* exists */ }

  const lines = [...vars.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, type]) => {
      const key = ident.test(name) ? name : JSON.stringify(name);
      return `  ${key}: ${type};`;
    });

  const body = lines.length
    ? `export interface Vars {\n${lines.join("\n")}\n}`
    : `// deno-lint-ignore no-empty-interface\nexport interface Vars {}`;

  // The context is widened with globals (group_vars/inventory) and Ansible
  // built-ins, so references to those are checkable too — not just own-defaults.
  const out = `// Auto-generated by gen-contexts.ts from\n` +
    `// ../../../devops/roles/${role.name}/{defaults,vars}/*.yml\n` +
    `// Per-role variable context: ${vars.size} own variables (+ globals + builtins).\n` +
    `import { context } from "../../lib/context.ts";\n` +
    `import type { Globals } from "../../lib/globals.ts";\n` +
    `import type { Builtins } from "../../lib/builtins.ts";\n\n` +
    `${body}\n\n` +
    `export const { V, tmpl, isDef, notVar } = context<\n` +
    `  Vars & Globals & Builtins\n` +
    `>();\n`;

  await Deno.writeTextFile(new URL("_ctx.ts", outDir), out);
  generated++;
}

console.log(`Generated ${generated} role contexts.`);
