// Generate per-role variable contexts: roles/<role>/_ctx.ts
//
// Reads each role's ../devops/roles/<role>/{defaults,vars}/*.yml, collects the
// top-level variable names with inferred types, and emits a `Vars` interface +
// a `context<Vars>()` accessor. Idempotent; re-run after editing role defaults.
//
//   deno run --allow-read --allow-write gen-contexts.ts
import { parse } from "yaml";

const devopsRoles = new URL("../devops/roles/", import.meta.url);
const tsRoles = new URL("./roles/", import.meta.url);

/** Interface member names declared in a lib file (to avoid intersection clashes). */
async function declaredNames(path: string): Promise<Set<string>> {
  const names = new Set<string>();
  const text = await Deno.readTextFile(new URL(path, import.meta.url));
  for (const m of text.matchAll(/^\s{2}([A-Za-z_$][\w$]*)\??:/gm)) {
    names.add(m[1]);
  }
  return names;
}

// A role's own var that is also a global/builtin would make `Vars & Globals &
// BuiltinVars` collide (e.g. boolean & string -> never), so own vars exclude them;
// they remain reachable through the widening with the global/builtin type.
const reserved = new Set([
  ...await declaredNames("./lib/globals.ts"),
  ...await declaredNames("./lib/builtins.ts"),
]);

// Every var name is declared `string`, matching Globals/BuiltinVars/Self: only
// the NAMES matter (the V accessor maps every key to a Ref, erasing the value
// type), so precise types are unused. Declaring them uniformly also keeps the
// `Vars & ... & AllVars` intersection conflict-free — a name typed e.g. boolean
// here but string in AllVars would intersect to a `never` property, which (via
// the generic mapped type in context<V>()) collapses the whole accessor to
// `never`. Uniform `string` avoids that.
function tsType(_v: unknown): string {
  return "string";
}

/** A valid bare TS identifier needs no quoting as an interface key. */
const ident = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

// Every var name defined in ANY role's defaults/vars, accumulated across all
// roles. Emitted as lib/allvars.ts so a role-defined variable can be referenced
// statically (checked `V.x`) from an inventory or a *different* role — Ansible
// variable names are a single flat namespace, so a name defined anywhere is the
// same variable everywhere. Already excludes globals/builtins (via `reserved`).
const allVars = new Set<string>();

let generated = 0;
for await (const role of Deno.readDir(devopsRoles)) {
  if (!role.isDirectory) continue;

  const vars = new Map<string, string>(); // name -> ts type
  for (const sub of ["defaults", "vars"]) {
    const dir = new URL(`${role.name}/${sub}/`, devopsRoles);
    let entries: Deno.DirEntry[] = [];
    try {
      for await (const f of Deno.readDir(dir)) entries.push(f);
    } catch {
      continue;
    }
    for (const f of entries) {
      if (!f.isFile || !f.name.endsWith(".yml")) continue;
      let doc: unknown;
      try {
        doc = parse(await Deno.readTextFile(new URL(f.name, dir)));
      } catch {
        continue;
      }
      if (doc && typeof doc === "object" && !Array.isArray(doc)) {
        for (const [k, v] of Object.entries(doc as Record<string, unknown>)) {
          if (reserved.has(k)) continue; // covered by Globals/BuiltinVars widening
          // defaults win over vars only if vars hasn't set a non-unknown type
          if (!vars.has(k) || vars.get(k) === "unknown") {
            vars.set(k, tsType(v));
          }
        }
      }
    }
  }

  // Ensure the role's TS dir exists (it does for ported roles; create otherwise).
  const outDir = new URL(`${role.name}/`, tsRoles);
  try {
    await Deno.mkdir(outDir, { recursive: true });
  } catch { /* exists */ }

  for (const name of vars.keys()) allVars.add(name);

  const lines = [...vars.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, type]) => {
      const key = ident.test(name) ? name : JSON.stringify(name);
      return `  ${key}: ${type};`;
    });

  const body = lines.length
    ? `export interface Vars {\n${lines.join("\n")}\n}`
    : `// deno-lint-ignore no-empty-interface\nexport interface Vars {}`;

  // The context is widened with globals (group_vars/inventory) and Ansible
  // built-ins, so references to those are checkable too — not just own-defaults.
  const out = `// Auto-generated by gen-contexts.ts from\n` +
    `// ../../../devops/roles/${role.name}/{defaults,vars}/*.yml\n` +
    `// Per-role variable context: ${vars.size} own variables (+ globals + builtins).\n` +
    `import { context } from "../../lib/context.ts";\n` +
    `import type { Globals } from "../../lib/globals.ts";\n` +
    `import type { BuiltinVars } from "../../lib/builtins.ts";\n` +
    `import type { AllVars } from "../../lib/allvars.ts";\n\n` +
    `${body}\n\n` +
    `export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<\n` +
    `  Vars & Globals & BuiltinVars & AllVars\n` +
    `>();\n`;

  await Deno.writeTextFile(new URL("_ctx.ts", outDir), out);
  generated++;
}

// Emit the flat, system-wide registry of role-defined variable names.
const allVarLines = [...allVars]
  .sort((a, b) => a.localeCompare(b))
  .map((name) => `  ${ident.test(name) ? name : JSON.stringify(name)}: string;`);
const allVarsOut =
  `// Auto-generated by gen-contexts.ts from ../../../devops/roles/*/{defaults,vars}/*.yml\n` +
  `// Flat registry of every variable name defined in ANY role (excluding names\n` +
  `// already in Globals/BuiltinVars). Ansible variable names form a single\n` +
  `// namespace, so a role-defined var is the same variable everywhere; declaring\n` +
  `// the names here lets an inventory or a different role reference one as a\n` +
  `// checked \`V.x\` instead of the \`expr("x")\` escape hatch. Declared as \`string\`\n` +
  `// — only the names matter (the V accessor maps every key to a Ref).\n` +
  `export interface AllVars {\n${allVarLines.join("\n")}\n}\n`;
await Deno.writeTextFile(new URL("./lib/allvars.ts", import.meta.url), allVarsOut);

console.log(
  `Generated ${generated} role contexts; ${allVars.size} names in allvars.ts.`,
);
