// Auto-generated by gen-data.ts from ../devops/roles/icos.jarservice/defaults/main.yml
import type { Vars } from "../../../../roles/icos.jarservice/_ctx.ts";
import { register } from "../../../../lib/register.ts";
import { context } from "../../../../lib/context.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";

const { V, tmpl } = context<ParamVars>();

export default {
  "jarservice_keep_n_old": 10,
  "jarservice_jar": tmpl`${register("_user").home.ref}/${V.servicename}.jar`,
  "extra_groups": "",
  "certbot_disabled": false,
} satisfies Vars;
