// Auto-generated by gen-data.ts from ../devops/roles/icos.jarservice/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  jarservice_keep_n_old: unknown;
  jarservice_jar: unknown;
  extra_groups: unknown;
  certbot_disabled: unknown;
}
const { V, tmpl, rawTmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "jarservice_keep_n_old": 10,
  "jarservice_jar": tmpl`${rawTmpl("{{ _user.home}}")}/${V.servicename}.jar`,
  "extra_groups": "",
  "certbot_disabled": false,
} satisfies VarsFile;
