// Auto-generated by gen-data.ts from ../devops/roles/icos.jarservice/defaults/main.yml
import { servicename } from "../../../../lib/paramvars.ts";
import { register } from "../../../../lib/register.ts";
import { tmpl } from "../../../../lib/template.ts";
import { type Vars } from "../../../../roles/icos.jarservice/_ctx.ts";

export default {
  "jarservice_keep_n_old": 10,
  "jarservice_jar": tmpl`${register("_user").home.ref}/${servicename}.jar`,
  "extra_groups": "",
  "certbot_disabled": false
} satisfies Vars;
