// Auto-generated by gen-data.ts from ../devops/roles/icos.flexextract/defaults/main.yml
import type { Vars } from "../../../../roles/icos.flexextract/_ctx.ts";
import { context } from "../../../../lib/context.ts";

interface Self {
  flexextract_bin_dir: unknown;
  flexextract_download_cont: unknown;
  flexextract_download_host: unknown;
  flexextract_home: unknown;
  flexextract_tag: unknown;
  flexextract_user: unknown;
}
const { V, tmpl } = context<Self>();

export default {
  "flexextract_user": "flexextract",
  "flexextract_home": "/docker/flexextract",
  "flexextract_tag": "flexextract",
  "flexextract_download_host": tmpl`${V.flexextract_home}/download`,
  "flexextract_download_cont": "/usr/local/Flexpart_9.0.3/download/",
  "flexextract_bin_dir": tmpl`${V.flexextract_home}/bin`,
} satisfies Vars;
