// Auto-generated by gen-data.ts from ../devops/roles/icos.victoriametrics/defaults/main.yml
import { upgrade_everything } from "../../../../lib/sharedvars.ts";
import { tmpl } from "../../../../lib/template.ts";
import {
  type Vars,
  vm_home,
} from "../../../../roles/icos.victoriametrics/_ctx.ts";

export default {
  "vm_home": "/opt/victoriametrics",
  "vm_scrape_conf": "",
  "vm_vm_port": 8428,
  "vm_upgrade": upgrade_everything.default(false).bool(),
  "vm_graf_port": 3000,
  "vm_graf_url": "http://grafana.local",
  "vm_graf_plugins": tmpl`${vm_home}/grafana/data/plugins`,
  "vm_graf_image": "grafana/grafana",
  "vm_promlens_port": 3001,
} satisfies Vars;
