// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.jarservice2/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  jarservice_jar: string;
  jarservice_jar_enable: boolean;
  jarservice_keep_n_old: number;
  jarservice_restart: boolean;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
