// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.jarservice2/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  jarservice_jar: Tmpl;
  jarservice_jar_enable: boolean;
  jarservice_keep_n_old: number;
  jarservice_restart: boolean;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const jarservice_jar = vref("jarservice_jar");
export const jarservice_jar_enable = vref("jarservice_jar_enable");
export const jarservice_keep_n_old = vref("jarservice_keep_n_old");
export const jarservice_restart = vref("jarservice_restart");
