// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.flexextract/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  flexextract_bin_dir: Tmpl;
  flexextract_download_cont: string;
  flexextract_download_host: Tmpl;
  flexextract_home: string;
  flexextract_tag: string;
  flexextract_user: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const flexextract_bin_dir = vref("flexextract_bin_dir");
export const flexextract_download_cont = vref("flexextract_download_cont");
export const flexextract_download_host = vref("flexextract_download_host");
export const flexextract_home = vref("flexextract_home");
export const flexextract_tag = vref("flexextract_tag");
export const flexextract_user = vref("flexextract_user");
