// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.flexextract/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  flexextract_bin_dir: unknown;
  flexextract_download_cont: unknown;
  flexextract_download_host: unknown;
  flexextract_home: unknown;
  flexextract_tag: unknown;
  flexextract_user: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & BuiltinVars & ParamVars
>();
