// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.flexextract/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  flexextract_bin_dir: string;
  flexextract_download_cont: string;
  flexextract_download_host: string;
  flexextract_home: string;
  flexextract_tag: string;
  flexextract_user: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
