// Auto-generated by gen-data.ts from ../devops/roles/icos.bbclient2/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "bbclient_user": "root",
  "bbclient_home": tmpl("/opt/bbclient-{{ bbclient_name }}"),
  "bbclient_timer_conf": "OnCalendar=daily\nRandomizedDelaySec=2h\n",
  "bbclient_patterns": "R volumes\n",
  "bbclient_ssh_dir": tmpl("{{ bbclient_home }}/ssh"),
  "bbclient_bin_dir": tmpl("{{ bbclient_home }}/bin"),
  "bbclient_borg_dir": tmpl("{{ bbclient_home }}/borg"),
  "bbclient_ssh_bin": tmpl("{{ bbclient_bin_dir }}/ssh"),
  "bbclient_ssh_config": tmpl("{{ bbclient_ssh_dir }}/config"),
  "bbclient_ssh_hosts": tmpl("{{ bbclient_ssh_dir }}/known_hosts"),
  "bbclient_ssh_key": tmpl("{{ bbclient_ssh_dir }}/bbclient.rsa"),
  "bbclient_repo_url": tmpl(
    "{{ bbclient_remote }}:repos/{{ bbclient_name }}.repo",
  ),
  "bbclient_repo_file": tmpl("{{ bbclient_home }}/repos"),
  "bbclient_wrapper": tmpl("{{ bbclient_bin_dir }}/borg"),
  "bbclient_one": tmpl("{{ bbclient_bin_dir }}/bbclient"),
  "bbclient_all": tmpl("{{ bbclient_bin_dir }}/bbclient-all"),
  "bbclient_remote_user": tmpl("{{ hostvars[bbclient_remote].bbserver_user }}"),
  "bbclient_remote_repo": tmpl(
    "{{ hostvars[bbclient_remote].bbserver_home }}/repos/{{ bbclient_name }}.repo",
  ),
  "bbclient_coldbackup_hour": tmpl("{{ 4 | random(seed=bbclient_name) }}"),
  "bbclient_coldbackup_minute": tmpl("{{ 60 | random(seed=bbclient_name) }}"),
  "bbclient_patterns_path": tmpl("{{ bbclient_home }}/patterns.lst"),
} satisfies VarsFile;
