// Auto-generated by gen-data.ts from ../devops/roles/icos.bbclient2/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "bbclient_user": "root",
  "bbclient_home": tmpl`/opt/bbclient-${expr("bbclient_name")}`,
  "bbclient_timer_conf": "OnCalendar=daily\nRandomizedDelaySec=2h\n",
  "bbclient_patterns": "R volumes\n",
  "bbclient_ssh_dir": tmpl`${expr("bbclient_home")}/ssh`,
  "bbclient_bin_dir": tmpl`${expr("bbclient_home")}/bin`,
  "bbclient_borg_dir": tmpl`${expr("bbclient_home")}/borg`,
  "bbclient_ssh_bin": tmpl`${expr("bbclient_bin_dir")}/ssh`,
  "bbclient_ssh_config": tmpl`${expr("bbclient_ssh_dir")}/config`,
  "bbclient_ssh_hosts": tmpl`${expr("bbclient_ssh_dir")}/known_hosts`,
  "bbclient_ssh_key": tmpl`${expr("bbclient_ssh_dir")}/bbclient.rsa`,
  "bbclient_repo_url": tmpl`${expr("bbclient_remote")}:repos/${
    expr("bbclient_name")
  }.repo`,
  "bbclient_repo_file": tmpl`${expr("bbclient_home")}/repos`,
  "bbclient_wrapper": tmpl`${expr("bbclient_bin_dir")}/borg`,
  "bbclient_one": tmpl`${expr("bbclient_bin_dir")}/bbclient`,
  "bbclient_all": tmpl`${expr("bbclient_bin_dir")}/bbclient-all`,
  "bbclient_remote_user": expr("hostvars[bbclient_remote].bbserver_user"),
  "bbclient_remote_repo": tmpl`${
    expr("hostvars[bbclient_remote].bbserver_home")
  }/repos/${expr("bbclient_name")}.repo`,
  "bbclient_coldbackup_hour": expr("4 | random(seed=bbclient_name)"),
  "bbclient_coldbackup_minute": expr("60 | random(seed=bbclient_name)"),
  "bbclient_patterns_path": tmpl`${expr("bbclient_home")}/patterns.lst`,
} satisfies VarsFile;
