// Auto-generated by gen-data.ts from ../devops/roles/icos.python_util/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "python_util_bin_dir": "/usr/local/bin",
  "python_util_python_executable": "python3.11",
  "python_util_install_prefix": "/opt/",
  "python_util_install_dir": tmpl`${expr("python_util_install_prefix")}/${
    expr("python_util_src | basename")
  }`,
} satisfies VarsFile;
