// Auto-generated by gen-data.ts from ../devops/roles/icos.python_util/defaults/main.yml
import { python_util_src } from "../../../../lib/paramvars.ts";
import { tmpl } from "../../../../lib/template.ts";
import { V, type Vars } from "../../../../roles/icos.python_util/_ctx.ts";

export default {
  "python_util_bin_dir": "/usr/local/bin",
  "python_util_python_executable": "python3.11",
  "python_util_install_prefix": "/opt/",
  "python_util_install_dir": tmpl`${V.python_util_install_prefix}/${python_util_src.basename()}`
} satisfies Vars;
