// Auto-generated by gen-data.ts from ../devops/roles/icos.python_util/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  python_util_bin_dir: string;
  python_util_python_executable: string;
  python_util_install_prefix: string;
  python_util_install_dir: string;
}
const { V, expr, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "python_util_bin_dir": "/usr/local/bin",
  "python_util_python_executable": "python3.11",
  "python_util_install_prefix": "/opt/",
  "python_util_install_dir": tmpl`${V.python_util_install_prefix}/${
    expr("python_util_src | basename")
  }`,
} satisfies VarsFile;
