// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.mtail/{defaults,vars}/*.yml
// Per-role variable context: 4 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  mtail_host: string;
  mtail_logs: unknown[];
  mtail_port: number;
  mtail_programs: unknown[];
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
