cpdoi{
	httpBindInterface = "{{ doi_bind_addr }}"
	httpBindPort = {{ doi_port }}
	admins = {{ doi_admins | to_json }}
	mailing.password = "{{ vault_doi_email_password }}"
	mailing.toAddresses = {{ doi_to_addresses | to_json if doi_to_addresses else '[]' }}
	metaHost = "{{ doi_meta_domain }}"

	{% if doi_test_password is defined %}
	test.member.password = "{{ doi_test_password }}"
	{% else %}
	test = null # Disable the test config in production
	{% endif %}
	production.member.password = "{{ doi_password }}"
}

{% include 'roles/icos.cpauth/templates/application_auth_views.conf' %}
