// Auto-generated by gen-data.ts from ../devops/roles/icos.pve_server/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";

interface Self {
  pve_dnat_bridge: string;
  pve_dnat_leases: string;
}
const { V, tmpl } = context<Self & Globals & BuiltinVars>();

export default {
  "pve_dnat_bridge": "vmbr0",
  "pve_dnat_leases": tmpl`/var/lib/misc/dnsmasq.${V.pve_dnat_bridge}.leases`,
} satisfies VarsFile;
