// Auto-generated by gen-data.ts from ../devops/roles/icos.pve_server/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "pve_dnat_bridge": "vmbr0",
  "pve_dnat_leases": "/var/lib/misc/dnsmasq.{{ pve_dnat_bridge }}.leases",
} satisfies VarsFile;
