
- name: Create application.conf
  copy:
    dest: "{{ cpmeta_home }}/application.conf"
    content: |
      {% for item in cpmeta_config_files %}
      # {{ item }}
      {{ lookup('template', item) }}

      {% endfor %}
  register: _config

- include_tasks: restart.yml
  vars:
    _restart_needed: "{{ _config.changed }}"
