services:
  virtuoso:
    image: {{ virtuoso_image }}
    environment:
      DBA_PASSWORD: "{{ virtuoso_dba_pass }}"
      VIRT_Parameters_NumberOfBuffers: "{{ virtuoso_number_of_buffers }}"
      VIRT_Parameters_MaxDirtyBuffers: "{{ virtuoso_max_dirty_buffers }}"
      VIRT_Parameters_MaxClientConnections: "{{ virtuoso_max_client_connections }}"
      VIRT_SPARQL_ResultSetMaxRows: "{{ virtuoso_result_set_max_rows }}"
    ports:
      - "{{ virtuoso_bind_host }}:{{ virtuoso_http_port }}:8890"
      - "{{ virtuoso_bind_host }}:{{ virtuoso_isql_port }}:1111"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ virtuoso_home }}/volumes/virtuoso.db:/database"
    restart: unless-stopped
