;
; Virtuoso configuration - managed by Ansible
;

[Database]
DatabaseFile       = /database/virtuoso.db
ErrorLogFile       = /database/virtuoso.log
LockFile           = /database/virtuoso.lck
TransactionFile    = /database/virtuoso.trx
xa_persistent_file = /database/virtuoso.pxa
ErrorLogLevel      = 7

[TempDatabase]
DatabaseFile       = /database/virtuoso-temp.db
TransactionFile    = /database/virtuoso-temp.trx
MaxCheckpointRemap = 2000

[Parameters]
ServerPort           = 1111
LiteMode             = 0
DisableUnixSocket    = 1
DisableTcpSocket     = 0
MaxClientConnections = {{ virtuoso_max_client_connections }}
CheckpointInterval   = 60
CaseMode             = 2
MaxStaticCursorRows  = 5000
AllowOSCalls         = 0
SchedulerInterval    = 10
DirsAllowed          = ., /usr/local/virtuoso-opensource/share/virtuoso/vad, /database
NumberOfBuffers      = {{ virtuoso_number_of_buffers }}
MaxDirtyBuffers      = {{ virtuoso_max_dirty_buffers }}

[HTTPServer]
ServerPort           = 8890
ServerRoot           = /usr/local/virtuoso-opensource/var/lib/virtuoso/vsp
DavRoot              = DAV
EnabledGzipContent   = 1
Charset              = UTF-8

[AutoRepair]
BadParentLinks = 0

[Client]
SQL_PREFETCH_ROWS  = 100
SQL_PREFETCH_BYTES = 16000
SQL_QUERY_TIMEOUT  = 0
SQL_TXN_TIMEOUT    = 0

[Replication]
ServerName   = db-localhost
ServerEnable = 1
QueueMax     = 50000

[SPARQL]
ResultSetMaxRows           = {{ virtuoso_result_set_max_rows }}
MaxQueryCostEstimationTime = 400
MaxQueryExecutionTime      = 60
DefaultQuery               = select distinct ?Concept where {[] a ?Concept} LIMIT 100

[Plugins]
LoadPath = /usr/local/virtuoso-opensource/lib/virtuoso/hosting
