// Auto-generated by gen-data.ts from ../devops/roles/icos.jarservice2/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "jarservice_keep_n_old": 10,
  "jarservice_jar": "{{ jarservice_home }}/{{ jarservice_name }}.jar",
  "jarservice_jar_enable": true,
  "jarservice_restart": true,
} satisfies VarsFile;
