// Auto-generated by gen-data.ts from ../devops/roles/icos.jarservice2/defaults/main.yml
import type { Vars } from "../../../../roles/icos.jarservice2/_ctx.ts";
import { context } from "../../../../lib/context.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";

const { V, tmpl } = context<ParamVars>();

export default {
  "jarservice_keep_n_old": 10,
  "jarservice_jar": tmpl`${V.jarservice_home}/${V.jarservice_name}.jar`,
  "jarservice_jar_enable": true,
  "jarservice_restart": true,
} satisfies Vars;
