// Auto-generated by gen-data.ts from ../devops/roles/icos.jarservice2/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  jarservice_keep_n_old: unknown;
  jarservice_jar: unknown;
  jarservice_jar_enable: unknown;
  jarservice_restart: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "jarservice_keep_n_old": 10,
  "jarservice_jar": tmpl`${V.jarservice_home}/${V.jarservice_name}.jar`,
  "jarservice_jar_enable": true,
  "jarservice_restart": true,
} satisfies VarsFile;
