// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.pgrep/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  pgrep_conninfo: Tmpl;
  pgrep_home: Tmpl;
  pgrep_image: string;
  pgrep_metric_port: number;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const pgrep_conninfo = vref("pgrep_conninfo");
export const pgrep_home = vref("pgrep_home");
export const pgrep_image = vref("pgrep_image");
export const pgrep_metric_port = vref("pgrep_metric_port");
