// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.pgrep/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  pgrep_conninfo: string;
  pgrep_home: string;
  pgrep_image: string;
  pgrep_metric_port: number;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
