// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.pgrep/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  pgrep_conninfo: unknown;
  pgrep_home: unknown;
  pgrep_image: unknown;
  pgrep_metric_port: unknown;
}

export const { V, tmpl } = context<
  Vars & Globals & BuiltinVars
>();
