// Auto-generated by gen-data.ts from ../devops/roles/icos.docker_utils/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { hostvar } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";

interface Self {
  dive_architecture: unknown;
  dive_version: unknown;
  dive_url_map: unknown;
  lazydocker_architecture: unknown;
  lazydocker_version: unknown;
  lazydocker_url_map: unknown;
}
const { V, tmpl } = context<Self & BuiltinVars & ParamVars>();

export default {
  "dive_architecture": V.fake_architecture.default(V.ansible_architecture),
  "dive_version": hostvar("localhost").dive_version,
  "dive_url_map": {
    "aarch64":
      tmpl`https://github.com/wagoodman/dive/releases/download/v${V.dive_version}/dive_${V.dive_version}_linux_arm64.deb`,
    "x86_64":
      tmpl`https://github.com/wagoodman/dive/releases/download/v${V.dive_version}/dive_${V.dive_version}_linux_amd64.deb`,
  },
  "lazydocker_architecture": V.fake_architecture.default(
    V.ansible_architecture,
  ),
  "lazydocker_version": hostvar("localhost").lazydocker_version,
  "lazydocker_url_map": {
    "armv6l":
      tmpl`https://github.com/jesseduffield/lazydocker/releases/download/v${V.lazydocker_version}/lazydocker_${V.lazydocker_version}_Linux_armv6.tar.gz`,
    "armv7l":
      tmpl`https://github.com/jesseduffield/lazydocker/releases/download/v${V.lazydocker_version}/lazydocker_${V.lazydocker_version}_Linux_armv7.tar.gz`,
    "aarch64":
      tmpl`https://github.com/jesseduffield/lazydocker/releases/download/v${V.lazydocker_version}/lazydocker_${V.lazydocker_version}_Linux_arm64.tar.gz`,
    "x86_64":
      tmpl`https://github.com/jesseduffield/lazydocker/releases/download/v${V.lazydocker_version}/lazydocker_${V.lazydocker_version}_Linux_x86_64.tar.gz  `,
  },
} satisfies VarsFile;
