// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.exploredata/{defaults,vars}/*.yml
// Per-role variable context: 8 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  exploredata_home: Tmpl;
  exploredata_hub_container: Tmpl;
  exploredata_hub_image: Tmpl;
  exploredata_max_notebooks: number;
  exploredata_name: Tmpl;
  exploredata_network: Tmpl;
  exploredata_notebook_image: Tmpl;
  exploredata_port: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const exploredata_home = vref("exploredata_home");
export const exploredata_hub_container = vref("exploredata_hub_container");
export const exploredata_hub_image = vref("exploredata_hub_image");
export const exploredata_max_notebooks = vref("exploredata_max_notebooks");
export const exploredata_name = vref("exploredata_name");
export const exploredata_network = vref("exploredata_network");
export const exploredata_notebook_image = vref("exploredata_notebook_image");
export const exploredata_port = vref("exploredata_port");
