// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.exploredata/{defaults,vars}/*.yml
// Per-role variable context: 8 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { ParamVars } from "../../lib/paramvars.ts";
import type { VaultVars } from "../../lib/vaultvars.ts";
import type { VarShapes } from "../../lib/shapes.ts";

export interface Vars {
  exploredata_home: unknown;
  exploredata_hub_container: unknown;
  exploredata_hub_image: unknown;
  exploredata_max_notebooks: unknown;
  exploredata_name: unknown;
  exploredata_network: unknown;
  exploredata_notebook_image: unknown;
  exploredata_port: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();
