// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.exploredata/{defaults,vars}/*.yml
// Per-role variable context: 8 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  exploredata_home: string;
  exploredata_hub_container: string;
  exploredata_hub_image: string;
  exploredata_max_notebooks: number;
  exploredata_name: string;
  exploredata_network: string;
  exploredata_notebook_image: string;
  exploredata_port: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
