nginx_user: www-data
nginx_certbot_bin: /snap/bin/certbot

# Should we install and run the nginx metrics exporter?
nginx_metrics_enable: False

# The prometheus exporters address.
nginx_metrics_addr: "127.0.0.1:9113"

# The address to nginx's metrics page
nginx_metrics_url: "http://127.0.0.1/metrics"
