// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.users/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { VarShapes } from "../../lib/shapes.ts";

export interface Vars {
  user_disable_coredump: unknown;
}

export const { V, tmpl } = context<
  BuiltinVars & VarShapes
>();
