// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.users/{defaults,vars}/*.yml
// Per-role variable context: 1 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  user_disable_coredump: boolean;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
