// Auto-generated by gen-data.ts from ../devops/roles/icos.exploredata/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { eq, iff } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";

interface Self {
  exploredata_port: unknown;
  exploredata_name: unknown;
  exploredata_home: unknown;
  exploredata_network: unknown;
  exploredata_hub_image: unknown;
  exploredata_hub_container: unknown;
  exploredata_notebook_image: unknown;
  exploredata_max_notebooks: unknown;
}
const { V, tmpl } = context<Self & ParamVars>();

export default {
  "exploredata_port": iff(eq(V.exploredata_type, "test"), 4567, 4566),
  "exploredata_name": tmpl`exploredata.${V.exploredata_type}`,
  "exploredata_home": tmpl`/docker/${V.exploredata_name}`,
  "exploredata_network": V.exploredata_name,
  "exploredata_hub_image": tmpl`${V.exploredata_name}.hub`,
  "exploredata_hub_container": tmpl`${V.exploredata_name}.hub`,
  "exploredata_notebook_image":
    tmpl`registry.icos-cp.eu/${V.exploredata_name}.notebook`,
  "exploredata_max_notebooks": 50,
} satisfies VarsFile;
