// Auto-generated by gen-data.ts from ../devops/roles/icos.exploredata/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  exploredata_port: string;
  exploredata_name: string;
  exploredata_home: string;
  exploredata_network: string;
  exploredata_hub_image: string;
  exploredata_hub_container: string;
  exploredata_notebook_image: string;
  exploredata_max_notebooks: string;
}
const { V, expr, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "exploredata_port": expr("4567 if exploredata_type == 'test' else 4566"),
  "exploredata_name": tmpl`exploredata.${expr("exploredata_type")}`,
  "exploredata_home": tmpl`/docker/${V.exploredata_name}`,
  "exploredata_network": V.exploredata_name,
  "exploredata_hub_image": tmpl`${V.exploredata_name}.hub`,
  "exploredata_hub_container": tmpl`${V.exploredata_name}.hub`,
  "exploredata_notebook_image":
    tmpl`registry.icos-cp.eu/${V.exploredata_name}.notebook`,
  "exploredata_max_notebooks": 50,
} satisfies VarsFile;
