// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.xcaddy/{defaults,vars}/*.yml
// Per-role variable context: 1 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  xcaddy_upgrade: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
