// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.xcaddy/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";

export interface Vars {
  xcaddy_upgrade: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars
>();
