// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_forward/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { hostvar } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";

const { V } = context<ParamVars>();

export default {
  "lxd_forward_port": hostvar(V.lxd_forward_name).ansible_port,
} satisfies VarsFile;
