// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_forward/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "lxd_forward_port": "{{ hostvars[lxd_forward_name].ansible_port }}",
} satisfies VarsFile;
