- name: restart cron
  service:
    name: cron
    state: restarted
  register: _r
  # cron might not be installed
  failed_when:
    - _r.failed
    - _r.msg.find('Could not find the requested service cron') < 0
