// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.dokku/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

export interface Vars {
  dokku_data: string;
  dokku_home: string;
  dokku_http_port: string;
  dokku_ssh_port: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars
>();
