// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.dokku/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  dokku_data: string;
  dokku_home: string;
  dokku_http_port: number;
  dokku_ssh_port: number;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
