// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.dokku/{defaults,vars}/*.yml
// Per-role variable context: 4 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  dokku_data: string;
  dokku_home: string;
  dokku_http_port: number;
  dokku_ssh_port: number;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
