// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.keycloak/{defaults,vars}/*.yml
// Per-role variable context: 2 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  kc_home: string;
  kc_port: number;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const kc_home = vref("kc_home");
export const kc_port = vref("kc_port");
