// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.keycloak/{defaults,vars}/*.yml
// Per-role variable context: 2 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  kc_home: unknown;
  kc_port: unknown;
}

export const { V, tmpl } = context<
  Vars & ParamVars
>();
