// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.keycloak/{defaults,vars}/*.yml
// Per-role variable context: 2 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  kc_home: string;
  kc_port: number;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
