// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.jbuild/{defaults,vars}/*.yml
// Per-role variable context: 9 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  jbuild_edctl_host_name: Tmpl;
  jbuild_edctl_host_port: Tmpl;
  jbuild_jyctl_host_name: Tmpl;
  jbuild_jyctl_host_port: Tmpl;
  jbuild_registry: Record<string, Tmpl>;
  jbuild_rrsync_bin: string;
  jbuild_rsync_host_name: Tmpl;
  jbuild_rsync_host_port: Tmpl;
  jbuild_rsync_user: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const jbuild_edctl_host_name = vref("jbuild_edctl_host_name");
export const jbuild_edctl_host_port = vref("jbuild_edctl_host_port");
export const jbuild_jyctl_host_name = vref("jbuild_jyctl_host_name");
export const jbuild_jyctl_host_port = vref("jbuild_jyctl_host_port");
export const jbuild_registry = vref("jbuild_registry");
export const jbuild_rrsync_bin = vref("jbuild_rrsync_bin");
export const jbuild_rsync_host_name = vref("jbuild_rsync_host_name");
export const jbuild_rsync_host_port = vref("jbuild_rsync_host_port");
export const jbuild_rsync_user = vref("jbuild_rsync_user");
