// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.jbuild/{defaults,vars}/*.yml
// Per-role variable context: 9 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { ParamVars } from "../../lib/paramvars.ts";
import type { VarShapes } from "../../lib/shapes.ts";

export interface Vars {
  jbuild_edctl_host_name: unknown;
  jbuild_edctl_host_port: unknown;
  jbuild_jyctl_host_name: unknown;
  jbuild_jyctl_host_port: unknown;
  jbuild_registry: unknown;
  jbuild_rrsync_bin: unknown;
  jbuild_rsync_host_name: unknown;
  jbuild_rsync_host_port: unknown;
  jbuild_rsync_user: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & ParamVars & VarShapes
>();
