// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.jbuild/{defaults,vars}/*.yml
// Per-role variable context: 9 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  jbuild_edctl_host_name: string;
  jbuild_edctl_host_port: string;
  jbuild_jyctl_host_name: string;
  jbuild_jyctl_host_port: string;
  jbuild_registry: Record<string, unknown>;
  jbuild_rrsync_bin: string;
  jbuild_rsync_host_name: string;
  jbuild_rsync_host_port: string;
  jbuild_rsync_user: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
