// Auto-generated by gen-data.ts from ../devops/roles/icos.mtail/defaults/main.yml
import { type Vars } from "../../../../roles/icos.mtail/_ctx.ts";

export default {
  "mtail_logs": [],
  "mtail_port": 3903,
  "mtail_host": "localhost",
  "mtail_programs": [],
} satisfies Vars;
