// Auto-generated by gen-data.ts from ../devops/roles/icos.restic_server/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { hostvar } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  restic_server_data: unknown;
  restic_server_listen: unknown;
  restic_server_users: unknown;
  restic_server_htpasswd: unknown;
  restic_server_home: unknown;
  restic_server_exec: unknown;
  restic_server_user: unknown;
  restic_server_upgrade: unknown;
  restic_server_architecture: unknown;
  restic_server_version: unknown;
  restic_server_url_map: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "restic_server_data": null,
  "restic_server_listen": 8900,
  "restic_server_users": [],
  "restic_server_htpasswd": tmpl`${V.restic_server_data}/.htpasswd`,
  "restic_server_home": "/opt/restic-server",
  "restic_server_exec": tmpl`${V.restic_server_home}/bin/rest-server`,
  "restic_server_user": "restic-server",
  "restic_server_upgrade": V.upgrade_everything.default(false).bool(),
  "restic_server_architecture": V.fake_architecture.default(
    V.ansible_architecture,
  ),
  "restic_server_version": hostvar("localhost").restic_server_version,
  "restic_server_url_map": {
    "armv6l":
      tmpl`https://github.com/restic/rest-server/releases/download/v${V.restic_server_version}/rest-server_${V.restic_server_version}_linux_armv6.tar.gz`,
    "armv7l":
      tmpl`https://github.com/restic/rest-server/releases/download/v${V.restic_server_version}/rest-server_${V.restic_server_version}_linux_armv7.tar.gz`,
    "aarch64":
      tmpl`https://github.com/restic/rest-server/releases/download/v${V.restic_server_version}/rest-server_${V.restic_server_version}_linux_arm64.tar.gz`,
    "x86_64":
      tmpl`https://github.com/restic/rest-server/releases/download/v${V.restic_server_version}/rest-server_${V.restic_server_version}_linux_amd64.tar.gz`,
  },
} satisfies VarsFile;
