// Auto-generated by gen-data.ts from ../devops/roles/icos.restic_server/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "restic_server_data": null,
  "restic_server_listen": 8900,
  "restic_server_users": [],
  "restic_server_htpasswd": tmpl("{{ restic_server_data }}/.htpasswd"),
  "restic_server_home": "/opt/restic-server",
  "restic_server_exec": tmpl("{{ restic_server_home }}/bin/rest-server"),
  "restic_server_user": "restic-server",
  "restic_server_upgrade": tmpl(
    "{{ upgrade_everything | default(False) | bool }}",
  ),
  "restic_server_architecture": tmpl(
    "{{ fake_architecture | default(ansible_architecture) }}",
  ),
  "restic_server_version": tmpl(
    "{{ hostvars.localhost.restic_server_version }}",
  ),
  "restic_server_url_map": {
    "armv6l": tmpl(
      "https://github.com/restic/rest-server/releases/download/v{{ restic_server_version }}/rest-server_{{ restic_server_version }}_linux_armv6.tar.gz",
    ),
    "armv7l": tmpl(
      "https://github.com/restic/rest-server/releases/download/v{{ restic_server_version }}/rest-server_{{ restic_server_version }}_linux_armv7.tar.gz",
    ),
    "aarch64": tmpl(
      "https://github.com/restic/rest-server/releases/download/v{{ restic_server_version }}/rest-server_{{ restic_server_version }}_linux_arm64.tar.gz",
    ),
    "x86_64": tmpl(
      "https://github.com/restic/rest-server/releases/download/v{{ restic_server_version }}/rest-server_{{ restic_server_version }}_linux_amd64.tar.gz",
    ),
  },
} satisfies VarsFile;
