// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.fairdatapoint/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  fdp_domain: string;
  fdp_home: string;
  index_enabled: boolean;
  ping_enabled: boolean;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
