// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.fairdatapoint/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  fdp_domain: string;
  fdp_home: string;
  index_enabled: boolean;
  ping_enabled: boolean;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const fdp_domain = vref("fdp_domain");
export const fdp_home = vref("fdp_home");
export const index_enabled = vref("index_enabled");
export const ping_enabled = vref("ping_enabled");
