// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.fairdatapoint/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  fdp_domain: string;
  fdp_home: string;
  index_enabled: boolean;
  ping_enabled: boolean;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
