- name: Restore RestHeart backup
  ansible.builtin.script:
    cmd: "{{ restheart_restore_script_dir | default('/usr/local/bin') }}/restore_restheart_db.py --host={{ restheart_backup_host }} --location={{ restheart_backup_location }}"
    executable: /usr/bin/python3

