// Auto-generated by gen-data.ts from ../devops/roles/icos.nginxsite/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "nginxsite_state": "present",
  "nginxsite_path_available": tmpl`/etc/nginx/sites-available/${
    expr("nginxsite_name")
  }.conf`,
  "nginxsite_path_enable": tmpl`/etc/nginx/sites-enabled/${
    expr("nginxsite_name")
  }.conf`,
  "nginxsite_path_confd": tmpl`/etc/nginx/conf.d/${
    expr("nginxsite_name")
  }.conf`,
  "certbot_name": expr("nginxsite_name"),
  "certbot_domains": expr("nginxsite_domains"),
  "nginxauth_name": expr("nginxsite_name"),
  "nginxauth_users": expr("nginxsite_users"),
} satisfies VarsFile;
