// Auto-generated by gen-data.ts from ../devops/roles/icos.nginxsite/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  nginxsite_state: unknown;
  nginxsite_path_available: unknown;
  nginxsite_path_enable: unknown;
  nginxsite_path_confd: unknown;
  certbot_name: unknown;
  certbot_domains: unknown;
  nginxauth_name: unknown;
  nginxauth_users: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "nginxsite_state": "present",
  "nginxsite_path_available":
    tmpl`/etc/nginx/sites-available/${V.nginxsite_name}.conf`,
  "nginxsite_path_enable":
    tmpl`/etc/nginx/sites-enabled/${V.nginxsite_name}.conf`,
  "nginxsite_path_confd": tmpl`/etc/nginx/conf.d/${V.nginxsite_name}.conf`,
  "certbot_name": V.nginxsite_name,
  "certbot_domains": V.nginxsite_domains,
  "nginxauth_name": V.nginxsite_name,
  "nginxauth_users": V.nginxsite_users,
} satisfies VarsFile;
