// Auto-generated by gen-data.ts from ../devops/roles/icos.nginxsite/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "nginxsite_state": "present",
  "nginxsite_path_available": tmpl(
    "/etc/nginx/sites-available/{{ nginxsite_name }}.conf",
  ),
  "nginxsite_path_enable": tmpl(
    "/etc/nginx/sites-enabled/{{ nginxsite_name }}.conf",
  ),
  "nginxsite_path_confd": tmpl("/etc/nginx/conf.d/{{ nginxsite_name }}.conf"),
  "certbot_name": tmpl("{{ nginxsite_name }}"),
  "certbot_domains": tmpl("{{ nginxsite_domains }}"),
  "nginxauth_name": tmpl("{{ nginxsite_name }}"),
  "nginxauth_users": tmpl("{{ nginxsite_users }}"),
} satisfies VarsFile;
