# dnsmasq reads /etc/hosts and answers questions about it
# one usage is to add round-robin aliases for interval services

- name: Populate /etc/hosts
  blockinfile:
    marker: "# {mark} ansible / dnsmasq / {{ dnsmasq_config_name }}"
    state: "{{ 'present' if dnsmasq_hosts else 'absent' }}"
    create: no
    insertafter: EOF
    path: /etc/hosts
    block: "{{ dnsmasq_hosts }}"
