// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.maps/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, type VarRef, varProxy } from "../../lib/template.ts";

export interface Vars {
  maps_domains: unknown;
  maps_lantmateriet_auth: Tmpl;
  maps_lantmateriet_loc: string;
  maps_lantmateriet_url: string;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } =
  new Proxy({}, { get: (_t, name: string) => varProxy(name) }) as
    { readonly [K in keyof Vars]: VarRef<Vars[K]> };
