// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.maps/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  maps_domains: unknown;
  maps_lantmateriet_auth: Tmpl;
  maps_lantmateriet_loc: string;
  maps_lantmateriet_url: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const maps_domains = vref("maps_domains");
export const maps_lantmateriet_auth = vref("maps_lantmateriet_auth");
export const maps_lantmateriet_loc = vref("maps_lantmateriet_loc");
export const maps_lantmateriet_url = vref("maps_lantmateriet_url");
