// Auto-generated by gen-data.ts from ../devops/roles/icos.utils/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  ripgrep_version: string;
  ripgrep_url_map: string;
  ncdu_version: string;
  ncdu_arch_map: string;
  ncdu_url: string;
  fd_architecture: string;
  fd_version: string;
  fd_url_map: string;
  watchexec_architecture: string;
  watchexec_version: string;
  watchexec_url_map: string;
  btop_version: string;
  btop_home: string;
  btop_url_map: string;
  trippy_version: string;
  trippy_url_map: string;
  lazygit_upgrade: string;
  lazygit_architecture: string;
  lazygit_version: string;
  lazygit_url_map: string;
}
const { V, expr, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "ripgrep_version": expr("hostvars.localhost.ripgrep_version"),
  "ripgrep_url_map": {
    "x86_64":
      tmpl`https://github.com/BurntSushi/ripgrep/releases/download/${V.ripgrep_version}/ripgrep_${V.ripgrep_version}-1_amd64.deb`,
  },
  "ncdu_version": 2.3,
  "ncdu_arch_map": {
    "armv7l": "arm",
    "x86_64": "x86_64",
    "aarch64": "aarch64",
  },
  "ncdu_url":
    tmpl`https://dev.yorhel.nl/download/ncdu-${V.ncdu_version}-linux-${
      expr("ncdu_arch_map[ansible_architecture]")
    }.tar.gz`,
  "fd_architecture": expr("fake_architecture | default(ansible_architecture)"),
  "fd_version": expr("hostvars.localhost.fd_version"),
  "fd_url_map": {
    "armv6l":
      tmpl`https://github.com/sharkdp/fd/releases/download/v${V.fd_version}/fd-v${V.fd_version}-arm-unknown-linux-gnueabihf.tar.gz`,
    "armv7l":
      tmpl`https://github.com/sharkdp/fd/releases/download/v${V.fd_version}/fd-v${V.fd_version}-arm-unknown-linux-gnueabihf.tar.gz`,
    "aarch64":
      tmpl`https://github.com/sharkdp/fd/releases/download/v${V.fd_version}/fd-v${V.fd_version}-aarch64-unknown-linux-gnu.tar.gz`,
    "x86_64":
      tmpl`https://github.com/sharkdp/fd/releases/download/v${V.fd_version}/fd-musl_${V.fd_version}_amd64.deb`,
  },
  "watchexec_architecture": expr(
    "fake_architecture | default(ansible_architecture)",
  ),
  "watchexec_version": expr("hostvars.localhost.watchexec_version"),
  "watchexec_url_map": {
    "armv7l":
      tmpl`https://github.com/watchexec/watchexec/releases/download/v${V.watchexec_version}/watchexec-${V.watchexec_version}-armv7-unknown-linux-gnueabihf.deb`,
    "aarch64":
      tmpl`https://github.com/watchexec/watchexec/releases/download/v${V.watchexec_version}/watchexec-${V.watchexec_version}-aarch64-unknown-linux-gnu.deb`,
    "x86_64":
      tmpl`https://github.com/watchexec/watchexec/releases/download/v${V.watchexec_version}/watchexec-${V.watchexec_version}-x86_64-unknown-linux-musl.deb`,
  },
  "btop_version": expr("hostvars.localhost.btop_version"),
  "btop_home": "/opt",
  "btop_url_map": {
    "armv6l":
      tmpl`https://github.com/aristocratos/btop/releases/download/v${V.btop_version}/btop-armv5l-linux-musleabi.tbz`,
    "armv7l":
      tmpl`https://github.com/aristocratos/btop/releases/download/v${V.btop_version}/btop-armv7l-linux-musleabihf.tbz`,
    "aarch64":
      tmpl`https://github.com/aristocratos/btop/releases/download/v${V.btop_version}/btop-aarch64-linux-musl.tbz`,
    "x86_64":
      tmpl`https://github.com/aristocratos/btop/releases/download/v${V.btop_version}/btop-x86_64-linux-musl.tbz`,
  },
  "trippy_version": expr("hostvars.localhost.trippy_version"),
  "trippy_url_map": {
    "armv7l":
      tmpl`https://github.com/fujiapple852/trippy/releases/download/${V.trippy_version}/trippy-${V.trippy_version}-armv7-unknown-linux-musleabi.tar.gz`,
    "aarch64":
      tmpl`https://github.com/fujiapple852/trippy/releases/download/${V.trippy_version}/trippy-${V.trippy_version}-aarch64-unknown-linux-musl.tar.gz`,
    "x86_64":
      tmpl`https://github.com/fujiapple852/trippy/releases/download/${V.trippy_version}/trippy-${V.trippy_version}-x86_64-unknown-linux-gnu.tar.gz`,
  },
  "lazygit_upgrade": expr("upgrade_everything | default(False) | bool"),
  "lazygit_architecture": expr(
    "fake_architecture | default(ansible_architecture)",
  ),
  "lazygit_version": expr("hostvars.localhost.lazygit_version"),
  "lazygit_url_map": {
    "armv6l":
      tmpl`https://github.com/jesseduffield/lazygit/releases/download/v${V.lazygit_version}/lazygit_${V.lazygit_version}_Linux_armv6.tar.gz`,
    "armv7l":
      tmpl`https://github.com/jesseduffield/lazygit/releases/download/v${V.lazygit_version}/lazygit_${V.lazygit_version}_Linux_armv6.tar.gz`,
    "aarch64":
      tmpl`https://github.com/jesseduffield/lazygit/releases/download/v${V.lazygit_version}/lazygit_${V.lazygit_version}_Linux_arm64.tar.gz`,
    "x86_64":
      tmpl`https://github.com/jesseduffield/lazygit/releases/download/v${V.lazygit_version}/lazygit_${V.lazygit_version}_Linux_x86_64.tar.gz`,
  },
} satisfies VarsFile;
