// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.just/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  just_upgrade: string;
  just_url_map: Record<string, unknown>;
  just_version: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
