// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.just/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  just_upgrade: Tmpl;
  just_url_map: Record<string, Tmpl>;
  just_version: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const just_upgrade = vref("just_upgrade");
export const just_url_map = vref("just_url_map");
export const just_version = vref("just_version");
