// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.just/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  just_upgrade: unknown;
  just_url_map: unknown;
  just_version: unknown;
}

export const { V, tmpl } = context<
  Vars & BuiltinVars
>();
