// Auto-generated by gen-data.ts from ../devops/roles/icos.zrepl/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "zrepl_port": 9479,
} satisfies VarsFile;
