// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.caddy/{defaults,vars}/*.yml
// Per-role variable context: 8 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  caddy_bin: string;
  caddy_dropin_path: string;
  caddy_global_conf: string;
  caddy_modules: unknown[];
  caddy_site_state: string;
  caddy_upgrade: string;
  caddy_via_xcaddy: string;
  xcaddy_upgrade: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
