// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.caddy/{defaults,vars}/*.yml
// Per-role variable context: 8 own variables, widened with
// only the registries this role's task/handler files reference.
import type { Tmpl } from "../../lib/template.ts";
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  caddy_bin: Tmpl;
  caddy_dropin_path: string;
  caddy_global_conf: string;
  caddy_modules: unknown;
  caddy_site_state: string;
  caddy_upgrade: Tmpl;
  caddy_via_xcaddy: string;
  xcaddy_upgrade: Tmpl;
}

export const { V, tmpl, notVar } = context<
  Vars & BuiltinVars & ParamVars
>();
