// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.dataold/{defaults,vars}/*.yml
// Per-role variable context: 4 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  certbot_domains: unknown[];
  certbot_name: string;
  dataold_ext_port: number;
  dataold_home: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
