// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.dataold/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  certbot_domains: unknown;
  certbot_name: string;
  dataold_ext_port: number;
  dataold_home: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const certbot_domains = vref("certbot_domains");
export const certbot_name = vref("certbot_name");
export const dataold_ext_port = vref("dataold_ext_port");
export const dataold_home = vref("dataold_home");
