// Auto-generated by gen-data.ts from ../devops/roles/icos.telegraf/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "telegraf_config_root": "/etc/telegraf",
  "telegraf_config_file": "telegraf.conf",
  "telegraf_config_state": "present",
  "telegraf_config": "",
  "telegraf_upgrade": tmpl("{{ upgrade_everything | default(False) | bool }}"),
  "telegraf_smart_enable": false,
} satisfies VarsFile;
