// Auto-generated by gen-data.ts from ../devops/roles/icos.xcaddy/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

const { V } = context<AllVars>();

export default {
  "xcaddy_upgrade": V.upgrade_everything.default(false).bool(),
} satisfies VarsFile;
