// Auto-generated by gen-data.ts from ../devops/roles/icos.xcaddy/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr } from "../../../../lib/ansible.ts";

export default {
  "xcaddy_upgrade": expr("upgrade_everything | default(False) | bool"),
} satisfies VarsFile;
