// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.cni_plugins/{defaults,vars}/*.yml
// Per-role variable context: 1 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  cni_plugin_url: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
