// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.cni_plugins/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  cni_plugin_url: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const cni_plugin_url = vref("cni_plugin_url");
