// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.cni_plugins/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  cni_plugin_url: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
