# https://grafana.com/docs/grafana/latest/administration/plugin-management/#install-grafana-plugins
# https://github.com/VictoriaMetrics/grafana-datasource
# https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#plugins-1

- when: grafana_datasource_version is not defined
  run_once: true
  check_mode: false
  delegate_to: localhost
  delegate_facts: true
  block:

  - name: Find the latest release of grafana_datasource
    github_release:
      user: VictoriaMetrics
      repo: grafana-datasource
      action: latest_release
    register: gh

  - name: Set grafana_datasource_version fact
    set_fact:
      grafana_datasource_version: "{{ gh.tag.lstrip('v') }}"
      cacheable: true

- name: Create grafana plugin directory
  file:
    path: "{{ vm_graf_plugins }}"
    state: directory

- name: Install victoriametrics grafana-datasource
  unarchive:
    src: "https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v{{ hostvars.localhost.grafana_datasource_version }}/victoriametrics-metrics-datasource-v{{ hostvars.localhost.grafana_datasource_version }}.zip"
    dest: "{{ vm_graf_plugins }}"
    remote_src: true
    creates: >-
      {{omit if vm_upgrade else vm_graf_plugins + '/victoriametrics-datasource'}}
  diff: false

- name: Which version of grafana-datasource was installed
  debug:
    msg: "Installed {{ hostvars.localhost.grafana_datasource_version }}"
