// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.cpmeta/{defaults,vars}/*.yml
// Per-role variable context: 12 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { ParamVars } from "../../lib/paramvars.ts";
import type { VaultVars } from "../../lib/vaultvars.ts";
import type { VarShapes } from "../../lib/shapes.ts";

export interface Vars {
  cpmeta_bind_addr: unknown;
  cpmeta_db_name: unknown;
  cpmeta_db_pass: unknown;
  cpmeta_db_port: unknown;
  cpmeta_db_user: unknown;
  cpmeta_home: unknown;
  cpmeta_host: unknown;
  cpmeta_port: unknown;
  cpmeta_readonly_mode: unknown;
  cpmeta_servicename: unknown;
  cpmeta_user: unknown;
  doi_password_icos: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();
