// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.cpmeta/{defaults,vars}/*.yml
// Per-role variable context: 14 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  cpmeta_backup_enable: boolean;
  cpmeta_bind_addr: string;
  cpmeta_db_name: string;
  cpmeta_db_pass: string;
  cpmeta_db_port: number;
  cpmeta_db_user: string;
  cpmeta_home: string;
  cpmeta_host: string;
  cpmeta_port: number;
  cpmeta_rdfstorage_path: string;
  cpmeta_readonly_mode: boolean;
  cpmeta_servicename: string;
  cpmeta_user: string;
  doi_password_icos: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
