// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.conmon/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";

export interface Vars {
  conmon_apt_version_ok: unknown;
  conmon_local_version_ok: unknown;
  conmon_url: unknown;
  conmon_version_install: unknown;
}

export const { V, tmpl, notVar } = context<
  Vars
>();
