// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.conmon/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  conmon_apt_version_ok: Tmpl;
  conmon_local_version_ok: Tmpl;
  conmon_url: Tmpl;
  conmon_version_install: string;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
