// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.conmon/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  conmon_apt_version_ok: Tmpl;
  conmon_local_version_ok: Tmpl;
  conmon_url: Tmpl;
  conmon_version_install: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const conmon_apt_version_ok = vref("conmon_apt_version_ok");
export const conmon_local_version_ok = vref("conmon_local_version_ok");
export const conmon_url = vref("conmon_url");
export const conmon_version_install = vref("conmon_version_install");
