// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.certbot2/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  certbot_bin: string;
  certbot_cert_path: Tmpl;
  certbot_email: string;
  certbot_key_path: Tmpl;
  certbot_nginx_conf: Tmpl;
  certbot_site_path: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const certbot_bin = vref("certbot_bin");
export const certbot_cert_path = vref("certbot_cert_path");
export const certbot_email = vref("certbot_email");
export const certbot_key_path = vref("certbot_key_path");
export const certbot_nginx_conf = vref("certbot_nginx_conf");
export const certbot_site_path = vref("certbot_site_path");
