// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.certbot2/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { ParamVars } from "../../lib/paramvars.ts";
import type { VaultVars } from "../../lib/vaultvars.ts";
import type { VarShapes } from "../../lib/shapes.ts";

export interface Vars {
  certbot_bin: unknown;
  certbot_cert_path: unknown;
  certbot_email: unknown;
  certbot_key_path: unknown;
  certbot_nginx_conf: unknown;
  certbot_site_path: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();
