// Auto-generated by gen-data.ts from ../devops/roles/icos.golang/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  golang_version_install: unknown;
  golang_min_version: unknown;
  golang_local_version_ok: unknown;
  golang_apt_version_ok: unknown;
  golang_url: unknown;
  golang_opt_dir: unknown;
  golang_bin_dir: unknown;
}
const { V, expr, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "golang_version_install": "1.21.1",
  "golang_min_version": V.golang_version_install,
  "golang_local_version_ok": expr(
    'golang_local_version and\n   golang_local_version is version(golang_min_version, ">=")',
  ),
  "golang_apt_version_ok": expr(
    'golang_apt_version is version(golang_min_version, ">=")',
  ),
  "golang_url":
    tmpl`https://go.dev/dl/go${V.golang_version_install}.linux-amd64.tar.gz  `,
  "golang_opt_dir": tmpl`/opt/golang-${V.golang_version_install}`,
  "golang_bin_dir": tmpl`${V.golang_opt_dir}/go/bin`,
} satisfies VarsFile;
