// Auto-generated by gen-data.ts from ../devops/roles/icos.golang/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "golang_version_install": "1.21.1",
  "golang_min_version": expr("golang_version_install"),
  "golang_local_version_ok": expr(
    'golang_local_version and\n   golang_local_version is version(golang_min_version, ">=")',
  ),
  "golang_apt_version_ok": expr(
    'golang_apt_version is version(golang_min_version, ">=")',
  ),
  "golang_url": tmpl`https://go.dev/dl/go${
    expr("golang_version_install")
  }.linux-amd64.tar.gz  `,
  "golang_opt_dir": tmpl`/opt/golang-${expr("golang_version_install")}`,
  "golang_bin_dir": tmpl`${expr("golang_opt_dir")}/go/bin`,
} satisfies VarsFile;
