// Auto-generated by gen-data.ts from ../devops/roles/icos.sitesaquanetform/vars/vars.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "project_dir": "/disk/data/sites-aquanet-form",
  "certbot_domains": [
    "apply.fieldsites.se",
  ],
  "nginx_conf_name": "sites-aquanet-form",
  "certbot_conf_name": "sites_aquanet_form",
} satisfies VarsFile;
