// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.registry/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";

export interface Vars {
  registry_home: unknown;
  registry_htpasswd_file: unknown;
  registry_users: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars
>();
