// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.registry/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  registry_home: string;
  registry_htpasswd_file: string;
  registry_users: unknown[];
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
