// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.uv/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  uv_architecture: Tmpl;
  uv_home: string;
  uv_upgrade: Tmpl;
  uv_url_map: Record<string, Tmpl>;
  uv_version: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const uv_architecture = vref("uv_architecture");
export const uv_home = vref("uv_home");
export const uv_upgrade = vref("uv_upgrade");
export const uv_url_map = vref("uv_url_map");
export const uv_version = vref("uv_version");
