// Auto-generated by gen-data.ts from ../devops/roles/icos.caddy/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr } from "../../../../lib/ansible.ts";

export default {
  "caddy_global_conf": ':80 {\n  respond "Not found." 404\n}\n',
  "caddy_site_state": "present",
  "caddy_modules": [],
  "caddy_dropin_path": "/etc/systemd/system/caddy.service.d/usr_local_bin.conf",
  "caddy_via_xcaddy": "/usr/local/bin/caddy",
  "caddy_bin": expr("caddy_via_xcaddy if caddy_modules else '/usr/bin/caddy'"),
  "caddy_upgrade": expr("upgrade_everything | default(False) | bool"),
  "xcaddy_upgrade": expr("caddy_upgrade"),
} satisfies VarsFile;
