- when: nebula_version is not defined
  run_once: true
  check_mode: false
  delegate_to: localhost
  delegate_facts: true
  block:

  - name: Find the latest release of nebula
    uri:
      url: https://api.github.com/repos/slackhq/nebula/releases/latest
      return_content: true
    register: gh

  - name: Set nebula_version fact
    set_fact:
      nebula_version: "{{ gh.json.tag_name.lstrip('v') }}"
      cacheable: true

- name: Install nebula
  unarchive:
    remote_src: true
    src: "{{ nebula_url_map[ansible_architecture] }}"
    dest: "{{ nebula_bin_dir }}"
    extra_opts:
      - --no-same-owner
  notify: restart nebula
