- name: Install packages
  apt:
    name:
      # needed by the justfile
      - jq

- name: Create nebula user
  user:
    name: "{{ nebula_user }}"
    shell: /usr/sbin/nologin
    system: true
    create_home: no

- name: Create etc directory
  file:
    path: "{{ nebula_etc_dir }}"
    owner: "{{ nebula_user }}"
    group: "{{ nebula_user }}"
    state: directory
    mode: 0700

- name: Check whether nebula is already installed
  stat:
    path: "{{ nebula_bin_dir }}/nebula"
  register: _r

- name: Download and unpack nebula
  include_tasks: download.yml
  when: not _r.stat.exists or nebula_upgrade

- name: Check that nebula runs
  shell: |
    {{ nebula_bin_dir }}/{{ item }} -version
  changed_when: no
  register: version
  loop:
    - nebula
    - nebula-cert

- name: Inform about installed version
  run_once: true
  debug:
    msg: |
      We've installed nebula {{ version.results[0].stdout_lines[0] }}
  when: not ansible_check_mode
