// Auto-generated by gen-data.ts from ../devops/roles/icos.keycloak/defaults/main.yml
import type { Vars } from "../../../../roles/icos.keycloak/_ctx.ts";

export default {
  "kc_home": "/opt/keycloak",
  "kc_port": 28080,
} satisfies Vars;
