// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.postfix/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  postfix_config_list: unknown;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const postfix_config_list = vref("postfix_config_list");
