// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.postfix/{defaults,vars}/*.yml
// Per-role variable context: 1 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  postfix_config_list: unknown[];
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
