// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nextcloud/{defaults,vars}/*.yml
// Per-role variable context: 18 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  certbot_domains: unknown;
  certbot_name: string;
  nextcloud_certbot_enable: boolean;
  nextcloud_db_host: string;
  nextcloud_db_name: string;
  nextcloud_db_user: string;
  nextcloud_domain: string;
  nextcloud_exporter_conf_host: Tmpl;
  nextcloud_exporter_port: number;
  nextcloud_exporter_user: string;
  nextcloud_home: string;
  nextcloud_nextcloud_version: string;
  nextcloud_port: number;
  nextcloud_postgres_version: number;
  nextcloud_user: string;
  nextcloud_volume_nextcloud: Tmpl;
  nextcloud_volume_postgres: Tmpl;
  nextcloud_volumes: unknown;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const certbot_domains = vref("certbot_domains");
export const certbot_name = vref("certbot_name");
export const nextcloud_certbot_enable = vref("nextcloud_certbot_enable");
export const nextcloud_db_host = vref("nextcloud_db_host");
export const nextcloud_db_name = vref("nextcloud_db_name");
export const nextcloud_db_user = vref("nextcloud_db_user");
export const nextcloud_domain = vref("nextcloud_domain");
export const nextcloud_exporter_conf_host = vref(
  "nextcloud_exporter_conf_host",
);
export const nextcloud_exporter_port = vref("nextcloud_exporter_port");
export const nextcloud_exporter_user = vref("nextcloud_exporter_user");
export const nextcloud_home = vref("nextcloud_home");
export const nextcloud_nextcloud_version = vref("nextcloud_nextcloud_version");
export const nextcloud_port = vref("nextcloud_port");
export const nextcloud_postgres_version = vref("nextcloud_postgres_version");
export const nextcloud_user = vref("nextcloud_user");
export const nextcloud_volume_nextcloud = vref("nextcloud_volume_nextcloud");
export const nextcloud_volume_postgres = vref("nextcloud_volume_postgres");
export const nextcloud_volumes = vref("nextcloud_volumes");
