// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nextcloud/{defaults,vars}/*.yml
// Per-role variable context: 18 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  certbot_domains: unknown[];
  certbot_name: string;
  nextcloud_certbot_enable: boolean;
  nextcloud_db_host: string;
  nextcloud_db_name: string;
  nextcloud_db_user: string;
  nextcloud_domain: string;
  nextcloud_exporter_conf_host: string;
  nextcloud_exporter_port: number;
  nextcloud_exporter_user: string;
  nextcloud_home: string;
  nextcloud_nextcloud_version: string;
  nextcloud_port: number;
  nextcloud_postgres_version: number;
  nextcloud_user: string;
  nextcloud_volume_nextcloud: string;
  nextcloud_volume_postgres: string;
  nextcloud_volumes: unknown[];
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
