// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nextcloud/{defaults,vars}/*.yml
// Per-role variable context: 18 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  certbot_domains: unknown;
  certbot_name: unknown;
  nextcloud_certbot_enable: unknown;
  nextcloud_db_host: unknown;
  nextcloud_db_name: unknown;
  nextcloud_db_user: unknown;
  nextcloud_domain: unknown;
  nextcloud_exporter_conf_host: unknown;
  nextcloud_exporter_port: unknown;
  nextcloud_exporter_user: unknown;
  nextcloud_home: unknown;
  nextcloud_nextcloud_version: unknown;
  nextcloud_port: unknown;
  nextcloud_postgres_version: unknown;
  nextcloud_user: unknown;
  nextcloud_volume_nextcloud: unknown;
  nextcloud_volume_postgres: unknown;
  nextcloud_volumes: unknown;
}

export const { V, tmpl } = context<
  Vars & BuiltinVars
>();
