// Auto-generated by gen-data.ts from ../devops/roles/icos.conmon/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "conmon_version_install": "2.1.4",
  "conmon_local_version_ok": tmpl(
    '{{ conmon_local_version and\n   conmon_local_version is version(conmon_min_version, ">=") }}',
  ),
  "conmon_apt_version_ok": tmpl(
    '{{ conmon_apt_version is version(conmon_min_version, ">=") }}',
  ),
  "conmon_url": tmpl(
    "https://github.com/containers/conmon/archive/refs/tags/v{{ conmon_version_install }}.tar.gz",
  ),
} satisfies VarsFile;
