// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.bbclient2/{defaults,vars}/*.yml
// Per-role variable context: 20 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  bbclient_all: unknown;
  bbclient_bin_dir: unknown;
  bbclient_borg_dir: unknown;
  bbclient_coldbackup_hour: unknown;
  bbclient_coldbackup_minute: unknown;
  bbclient_one: unknown;
  bbclient_patterns: unknown;
  bbclient_patterns_path: unknown;
  bbclient_remote_repo: unknown;
  bbclient_remote_user: unknown;
  bbclient_repo_file: unknown;
  bbclient_repo_url: unknown;
  bbclient_ssh_bin: unknown;
  bbclient_ssh_config: unknown;
  bbclient_ssh_dir: unknown;
  bbclient_ssh_hosts: unknown;
  bbclient_ssh_key: unknown;
  bbclient_timer_conf: unknown;
  bbclient_user: unknown;
  bbclient_wrapper: unknown;
}

export const { V, tmpl, rawTmpl } = context<
  Vars & Globals & BuiltinVars & AllVars & ParamVars
>();
