// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.bbclient2/{defaults,vars}/*.yml
// Per-role variable context: 20 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  bbclient_all: string;
  bbclient_bin_dir: string;
  bbclient_borg_dir: string;
  bbclient_coldbackup_hour: string;
  bbclient_coldbackup_minute: string;
  bbclient_one: string;
  bbclient_patterns: string;
  bbclient_patterns_path: string;
  bbclient_remote_repo: string;
  bbclient_remote_user: string;
  bbclient_repo_file: string;
  bbclient_repo_url: string;
  bbclient_ssh_bin: string;
  bbclient_ssh_config: string;
  bbclient_ssh_dir: string;
  bbclient_ssh_hosts: string;
  bbclient_ssh_key: string;
  bbclient_timer_conf: string;
  bbclient_user: string;
  bbclient_wrapper: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
