// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.podman_manual/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  conmon_min_version: string;
  golang_min_version: number;
  podman_arch: Record<string, string>;
  podman_docker: boolean;
  podman_src_dir: Tmpl;
  podman_version: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const conmon_min_version = vref("conmon_min_version");
export const golang_min_version = vref("golang_min_version");
export const podman_arch = vref("podman_arch");
export const podman_docker = vref("podman_docker");
export const podman_src_dir = vref("podman_src_dir");
export const podman_version = vref("podman_version");
