// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.podman_manual/{defaults,vars}/*.yml
// Per-role variable context: 6 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  conmon_min_version: string;
  golang_min_version: number;
  podman_arch: Record<string, unknown>;
  podman_docker: boolean;
  podman_src_dir: string;
  podman_version: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
