// Auto-generated by gen-data.ts from ../devops/roles/icos.nextcloud/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  nextcloud_nextcloud_version: string;
  nextcloud_postgres_version: string;
  nextcloud_port: string;
  nextcloud_user: string;
  nextcloud_home: string;
  nextcloud_domain: string;
  nextcloud_certbot_enable: string;
  certbot_domains: string;
  certbot_name: string;
  nextcloud_volume_nextcloud: string;
  nextcloud_volume_postgres: string;
  nextcloud_db_name: string;
  nextcloud_db_user: string;
  nextcloud_db_host: string;
  nextcloud_exporter_conf_host: string;
  nextcloud_exporter_user: string;
  nextcloud_exporter_port: string;
  nextcloud_volumes: string;
}
const { V, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "nextcloud_nextcloud_version": "29.0.11",
  "nextcloud_postgres_version": 13.18,
  "nextcloud_port": 9000,
  "nextcloud_user": "nextcloud",
  "nextcloud_home": "/docker/nextcloud",
  "nextcloud_domain": "fileshare.icos-cp.eu",
  "nextcloud_certbot_enable": true,
  "certbot_domains": [
    V.nextcloud_domain,
  ],
  "certbot_name": "nextcloud",
  "nextcloud_volume_nextcloud": tmpl`${V.nextcloud_home}/volumes/nextcloud`,
  "nextcloud_volume_postgres": tmpl`${V.nextcloud_home}/volumes/postgres`,
  "nextcloud_db_name": "nextcloud",
  "nextcloud_db_user": "nextcloud",
  "nextcloud_db_host": "db",
  "nextcloud_exporter_conf_host":
    tmpl`${V.nextcloud_home}/nextcloud-exporter.conf`,
  "nextcloud_exporter_user": "nextcloud-exporter",
  "nextcloud_exporter_port": 9205,
  "nextcloud_volumes": [],
} satisfies VarsFile;
