// Auto-generated by gen-data.ts from ../devops/roles/icos.nextcloud/defaults/main.yml
import { tmpl } from "../../../../lib/template.ts";
import {
  nextcloud_domain,
  nextcloud_home,
  type Vars,
} from "../../../../roles/icos.nextcloud/_ctx.ts";

export default {
  "nextcloud_nextcloud_version": "29.0.11",
  "nextcloud_postgres_version": 13.18,
  "nextcloud_port": 9000,
  "nextcloud_user": "nextcloud",
  "nextcloud_home": "/docker/nextcloud",
  "nextcloud_domain": "fileshare.icos-cp.eu",
  "nextcloud_certbot_enable": true,
  "certbot_domains": [
    nextcloud_domain,
  ],
  "certbot_name": "nextcloud",
  "nextcloud_volume_nextcloud": tmpl`${nextcloud_home}/volumes/nextcloud`,
  "nextcloud_volume_postgres": tmpl`${nextcloud_home}/volumes/postgres`,
  "nextcloud_db_name": "nextcloud",
  "nextcloud_db_user": "nextcloud",
  "nextcloud_db_host": "db",
  "nextcloud_exporter_conf_host":
    tmpl`${nextcloud_home}/nextcloud-exporter.conf`,
  "nextcloud_exporter_user": "nextcloud-exporter",
  "nextcloud_exporter_port": 9205,
  "nextcloud_volumes": [],
} satisfies Vars;
