// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.restic/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";

export interface Vars {
  restic_architecture: unknown;
  restic_upgrade: unknown;
  restic_url_map: unknown;
  restic_version: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars
>();
