// Auto-generated by gen-data.ts from ../devops/roles/icos.drupal/defaults/main.yml
import { type Vars } from "../../../../roles/icos.drupal/_ctx.ts";

export default {
  "drupal_version": 10.6,
  "drupal_websites": [
    "ac",
    "ch",
    "cp",
    "fi",
    "next",
    "nl",
    "no",
    "otc",
    "otctest",
    "se",
    "sites",
  ],
  "drupal_home": "/disk/data/drupal",
  "drupal_modules": [],
  "update": false,
} satisfies Partial<Vars>;
