// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.typesense/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type VarRef, varProxy } from "../../lib/template.ts";

export interface Vars {
  base_urls: Record<string, string>;
  typesense_home: string;
  typesense_port: number;
  typesense_user: string;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } =
  new Proxy({}, { get: (_t, name: string) => varProxy(name) }) as
    { readonly [K in keyof Vars]: VarRef<Vars[K]> };
