// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.typesense/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  base_urls: Record<string, unknown>;
  typesense_home: string;
  typesense_port: number;
  typesense_user: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
