// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.typesense/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  base_urls: Record<string, string>;
  typesense_home: string;
  typesense_port: number;
  typesense_user: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const base_urls = vref("base_urls");
export const typesense_home = vref("typesense_home");
export const typesense_port = vref("typesense_port");
export const typesense_user = vref("typesense_user");
