// Auto-generated by gen-data.ts from ../devops/roles/icos.dnsmasq/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "dnsmasq_hosts": null,
  "dnsmasq_config_name": "config",
  "dnsmasq_config_state": "present",
  "dnsmasq_config_dir": tmpl("/etc/dnsmasq.{{ dnsmasq_instance }}.d"),
  "dnsmasq_config_file": tmpl(
    "{{ dnsmasq_config_dir }}/{{ dnsmasq_config_name }}",
  ),
  "dnsmasq_service_name": tmpl("dnsmasq@{{ dnsmasq_instance }}.service"),
} satisfies VarsFile;
