// Auto-generated by gen-data.ts from ../devops/roles/icos.dnsmasq/defaults/main.yml
import { dnsmasq_instance } from "../../../../lib/paramvars.ts";
import { tmpl } from "../../../../lib/template.ts";
import { V, type Vars } from "../../../../roles/icos.dnsmasq/_ctx.ts";

export default {
  "dnsmasq_hosts": null,
  "dnsmasq_config_name": "config",
  "dnsmasq_config_state": "present",
  "dnsmasq_config_dir": tmpl`/etc/dnsmasq.${dnsmasq_instance}.d`,
  "dnsmasq_config_file": tmpl`${V.dnsmasq_config_dir}/${V.dnsmasq_config_name}`,
  "dnsmasq_service_name": tmpl`dnsmasq@${dnsmasq_instance}.service`
} satisfies Vars;
