// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nebula/{defaults,vars}/*.yml
// Per-role variable context: 21 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, type VarRef, varProxy } from "../../lib/template.ts";

export interface Vars {
  nebula_bin_dir: string;
  nebula_ca_path: Tmpl;
  nebula_cert_min_days: number;
  nebula_domain: string;
  nebula_etc_dir: string;
  nebula_fw_enable: boolean;
  nebula_hostname: Tmpl;
  nebula_hosts_enable: boolean;
  nebula_is_lighthouse: boolean;
  nebula_resolve_enable: boolean;
  nebula_resolve_servers: null;
  nebula_resolve_test: null;
  nebula_resolve_type: string;
  nebula_ssh_key: Tmpl;
  nebula_ssh_port: number;
  nebula_stats_enable: boolean;
  nebula_stats_port: number;
  nebula_upgrade: Tmpl;
  nebula_url_map: Record<string, Tmpl>;
  nebula_user: string;
  nebula_version: Tmpl;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } =
  new Proxy({}, { get: (_t, name: string) => varProxy(name) }) as
    { readonly [K in keyof Vars]: VarRef<Vars[K]> };
