// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nebula/{defaults,vars}/*.yml
// Per-role variable context: 26 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  nebula_bin_dir: string;
  nebula_ca_path: string;
  nebula_cert_copy: string;
  nebula_cert_min_days: number;
  nebula_domain: string;
  nebula_etc_dir: string;
  nebula_fw_enable: boolean;
  nebula_hostname: string;
  nebula_hosts_block: unknown;
  nebula_hosts_enable: boolean;
  nebula_interface: string;
  nebula_is_lighthouse: boolean;
  nebula_port: number;
  nebula_resolve_enable: boolean;
  nebula_resolve_servers: unknown;
  nebula_resolve_test: unknown;
  nebula_resolve_type: string;
  nebula_ssh_enable: boolean;
  nebula_ssh_key: string;
  nebula_ssh_port: number;
  nebula_stats_enable: boolean;
  nebula_stats_port: number;
  nebula_upgrade: string;
  nebula_url_map: Record<string, unknown>;
  nebula_user: string;
  nebula_version: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
