// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.node_exporter/{defaults,vars}/*.yml
// Per-role variable context: 20 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  dirsize_dirnames: string;
  dirsize_home: string;
  dirsize_initial: unknown[];
  dirsize_prom: string;
  dirsize_sh: string;
  dockermon_enable: boolean;
  dockermon_home: string;
  dockermon_prom: string;
  lxdmon_enable: boolean;
  node_exporter_allow: boolean;
  node_exporter_arch: string;
  node_exporter_arch_map: Record<string, unknown>;
  node_exporter_bin: string;
  node_exporter_bindto: string;
  node_exporter_download: string;
  node_exporter_environ: string;
  node_exporter_home: string;
  node_exporter_listen: number;
  node_exporter_textfiles: string;
  node_exporter_user: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
