// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.node_exporter/{defaults,vars}/*.yml
// Per-role variable context: 20 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

export interface Vars {
  dirsize_dirnames: string;
  dirsize_home: string;
  dirsize_initial: string;
  dirsize_prom: string;
  dirsize_sh: string;
  dockermon_enable: string;
  dockermon_home: string;
  dockermon_prom: string;
  lxdmon_enable: string;
  node_exporter_allow: string;
  node_exporter_arch: string;
  node_exporter_arch_map: string;
  node_exporter_bin: string;
  node_exporter_bindto: string;
  node_exporter_download: string;
  node_exporter_environ: string;
  node_exporter_home: string;
  node_exporter_listen: string;
  node_exporter_textfiles: string;
  node_exporter_user: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars
>();
