// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.node_exporter/{defaults,vars}/*.yml
// Per-role variable context: 20 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  dirsize_dirnames: Tmpl;
  dirsize_home: Tmpl;
  dirsize_initial: unknown;
  dirsize_prom: Tmpl;
  dirsize_sh: Tmpl;
  dockermon_enable: boolean;
  dockermon_home: Tmpl;
  dockermon_prom: Tmpl;
  lxdmon_enable: boolean;
  node_exporter_allow: boolean;
  node_exporter_arch: Tmpl;
  node_exporter_arch_map: Record<string, string>;
  node_exporter_bin: string;
  node_exporter_bindto: string;
  node_exporter_download: Tmpl;
  node_exporter_environ: Tmpl;
  node_exporter_home: string;
  node_exporter_listen: number;
  node_exporter_textfiles: Tmpl;
  node_exporter_user: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const dirsize_dirnames = vref("dirsize_dirnames");
export const dirsize_home = vref("dirsize_home");
export const dirsize_initial = vref("dirsize_initial");
export const dirsize_prom = vref("dirsize_prom");
export const dirsize_sh = vref("dirsize_sh");
export const dockermon_enable = vref("dockermon_enable");
export const dockermon_home = vref("dockermon_home");
export const dockermon_prom = vref("dockermon_prom");
export const lxdmon_enable = vref("lxdmon_enable");
export const node_exporter_allow = vref("node_exporter_allow");
export const node_exporter_arch = vref("node_exporter_arch");
export const node_exporter_arch_map = vref("node_exporter_arch_map");
export const node_exporter_bin = vref("node_exporter_bin");
export const node_exporter_bindto = vref("node_exporter_bindto");
export const node_exporter_download = vref("node_exporter_download");
export const node_exporter_environ = vref("node_exporter_environ");
export const node_exporter_home = vref("node_exporter_home");
export const node_exporter_listen = vref("node_exporter_listen");
export const node_exporter_textfiles = vref("node_exporter_textfiles");
export const node_exporter_user = vref("node_exporter_user");
