#!/bin/bash
# This script is a psql(1), hardcoded to connect to the replication master.
set -Eueo pipefail

# If stdout is a tty then we need the '-T' flag, otherwise we're redirecting to
# a file and we must not have "-T".
if [ -t 0 ] && [ -t 1 ]; then O=""; else O="-T"; fi

docker-compose --project-directory "{{ pgrep_home }}" \
               run $O --user=postgres --rm --entrypoint=/usr/bin/psql -- \
               db -d '{{ pgrep_conninfo }}' "$@"
