#!/bin/bash
# This script starts a psql inside the "db" service.
set -Eueo pipefail

# If stdout is a tty then we need the '-T' flag, otherwise we're redirecting to
# a file and we must not have "-T". 
if [ -t 0 ] && [ -t 1 ]; then O=""; else O="-T"; fi

docker-compose --project-directory "{{ pgrep_home }}" \
               exec $O --user=postgres -- db psql "$@"

