// Auto-generated by gen-data.ts from ../devops/roles/icos.mailman/defaults/main.yml
import type { Vars } from "../../../../roles/icos.mailman/_ctx.ts";
import { jinja } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";

interface Self {
  mailman_admin_email: unknown;
  mailman_build_core: unknown;
  mailman_build_web: unknown;
  mailman_certbot_name: unknown;
  mailman_core_ipv4: unknown;
  mailman_database_ipv4: unknown;
  mailman_django_settings: unknown;
  mailman_home: unknown;
  mailman_host_ipv4: unknown;
  mailman_hyperkitty_api_key: unknown;
  mailman_nginxsite_file: unknown;
  mailman_nginxsite_name: unknown;
  mailman_postfix_config: unknown;
  mailman_postgres_password: unknown;
  mailman_rest_allow_deny: unknown;
  mailman_rest_port: unknown;
  mailman_rest_user: unknown;
  mailman_serve_from_domain: unknown;
  mailman_subnet: unknown;
  mailman_user: unknown;
  mailman_version: unknown;
  mailman_volume_core: unknown;
  mailman_volume_database: unknown;
  mailman_volume_web: unknown;
  mailman_web_ipv4: unknown;
  mailman_web_secret_key: unknown;
}
const { V, tmpl } = context<Self & ParamVars & VaultVars>();

export default {
  "mailman_user": "mailman",
  "mailman_home": "/docker/mailman",
  "mailman_version": "0.4.6",
  "mailman_serve_from_domain":
    jinja`{{ ${V.mailman_domains} | mandatory | first}}`,
  "mailman_postgres_password": V.vault_mailman_postgres_password,
  "mailman_hyperkitty_api_key": V.vault_mailman_hyperkitty_api_key,
  "mailman_web_secret_key": V.vault_mailman_web_secret_key,
  "mailman_admin_email": V.vault_mailman_admin_email,
  "mailman_volume_core": tmpl`${V.mailman_home}/volumes/core`,
  "mailman_volume_web": tmpl`${V.mailman_home}/volumes/web`,
  "mailman_volume_database": tmpl`${V.mailman_home}/volumes/database`,
  "mailman_build_core": tmpl`${V.mailman_home}/build/core`,
  "mailman_build_web": tmpl`${V.mailman_home}/build/web`,
  "mailman_django_settings": tmpl`${V.mailman_volume_web}/settings_local.py`,
  "mailman_subnet": "172.19.199.0/24",
  "mailman_host_ipv4": "172.19.199.1",
  "mailman_core_ipv4": "172.19.199.2",
  "mailman_web_ipv4": "172.19.199.3",
  "mailman_database_ipv4": "172.19.199.4",
  "mailman_postfix_config": [
    {
      "param": "recipient_delimiter",
      "value": "+",
    },
    {
      "param": "unknown_local_recipient_reject_code",
      "value": 550,
    },
    {
      "param": "owner_request_special",
      "value": "no",
    },
    {
      "param": "transport_maps",
      "value": tmpl`regexp:${V.mailman_volume_core}/var/data/postfix_lmtp`,
      "append": true,
    },
    {
      "param": "local_recipient_maps",
      "value": tmpl`regexp:${V.mailman_volume_core}/var/data/postfix_lmtp`,
      "append": true,
    },
    {
      "param": "relay_domains",
      "value": tmpl`regexp:${V.mailman_volume_core}/var/data/postfix_domains`,
      "append": true,
    },
    {
      "param": "mynetworks",
      "value": V.mailman_core_ipv4,
      "append": true,
    },
    {
      "param": "mynetworks",
      "value": V.mailman_web_ipv4,
      "append": true,
    },
  ],
  "mailman_rest_user": "restadmin",
  "mailman_rest_port": 8001,
  "mailman_rest_allow_deny": null,
  "mailman_certbot_name": "mailman",
  "mailman_nginxsite_name": "mailman",
  "mailman_nginxsite_file": "mailman-nginx.conf",
} satisfies Vars;
