// Auto-generated by gen-data.ts from ../devops/roles/icos.mailman/defaults/main.yml
import { mailman_domains } from "../../../../lib/paramvars.ts";
import { jinja, tmpl } from "../../../../lib/template.ts";
import {
  vault_mailman_admin_email,
  vault_mailman_hyperkitty_api_key,
  vault_mailman_postgres_password,
  vault_mailman_web_secret_key,
} from "../../../../lib/vaultvars.ts";
import { V, type Vars } from "../../../../roles/icos.mailman/_ctx.ts";

export default {
  "mailman_user": "mailman",
  "mailman_home": "/docker/mailman",
  "mailman_version": "0.4.6",
  "mailman_serve_from_domain":
    jinja`{{ ${mailman_domains} | mandatory | first}}`,
  "mailman_postgres_password": vault_mailman_postgres_password,
  "mailman_hyperkitty_api_key": vault_mailman_hyperkitty_api_key,
  "mailman_web_secret_key": vault_mailman_web_secret_key,
  "mailman_admin_email": vault_mailman_admin_email,
  "mailman_volume_core": tmpl`${V.mailman_home}/volumes/core`,
  "mailman_volume_web": tmpl`${V.mailman_home}/volumes/web`,
  "mailman_volume_database": tmpl`${V.mailman_home}/volumes/database`,
  "mailman_build_core": tmpl`${V.mailman_home}/build/core`,
  "mailman_build_web": tmpl`${V.mailman_home}/build/web`,
  "mailman_django_settings": tmpl`${V.mailman_volume_web}/settings_local.py`,
  "mailman_subnet": "172.19.199.0/24",
  "mailman_host_ipv4": "172.19.199.1",
  "mailman_core_ipv4": "172.19.199.2",
  "mailman_web_ipv4": "172.19.199.3",
  "mailman_database_ipv4": "172.19.199.4",
  "mailman_postfix_config": [
    {
      "param": "recipient_delimiter",
      "value": "+",
    },
    {
      "param": "unknown_local_recipient_reject_code",
      "value": 550,
    },
    {
      "param": "owner_request_special",
      "value": "no",
    },
    {
      "param": "transport_maps",
      "value": tmpl`regexp:${V.mailman_volume_core}/var/data/postfix_lmtp`,
      "append": true,
    },
    {
      "param": "local_recipient_maps",
      "value": tmpl`regexp:${V.mailman_volume_core}/var/data/postfix_lmtp`,
      "append": true,
    },
    {
      "param": "relay_domains",
      "value": tmpl`regexp:${V.mailman_volume_core}/var/data/postfix_domains`,
      "append": true,
    },
    {
      "param": "mynetworks",
      "value": V.mailman_core_ipv4,
      "append": true,
    },
    {
      "param": "mynetworks",
      "value": V.mailman_web_ipv4,
      "append": true,
    },
  ],
  "mailman_rest_user": "restadmin",
  "mailman_rest_port": 8001,
  "mailman_rest_allow_deny": null,
  "mailman_certbot_name": "mailman",
  "mailman_nginxsite_name": "mailman",
  "mailman_nginxsite_file": "mailman-nginx.conf",
} satisfies Vars;
