// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.jarservice/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  certbot_disabled: boolean;
  extra_groups: string;
  jarservice_jar: Tmpl;
  jarservice_keep_n_old: number;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
