// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.jarservice/{defaults,vars}/*.yml
// Per-role variable context: 4 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  certbot_disabled: boolean;
  extra_groups: string;
  jarservice_jar: string;
  jarservice_keep_n_old: number;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
