// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.lxd_forward/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  lxd_forward_port: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & ParamVars
>();
