// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.lxd_forward/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  lxd_forward_port: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
