// Auto-generated by gen-data.ts from ../devops/roles/icos.pgrep/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  pgrep_home: unknown;
  pgrep_conninfo: unknown;
  pgrep_metric_port: unknown;
  pgrep_image: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "pgrep_home": tmpl`/docker/pgrep_${V.pgrep_name}`,
  "pgrep_conninfo":
    tmpl`host=${V.pgrep_peer_host} port=${V.pgrep_peer_port} dbname=postgres user=${V.pgrep_peer_user} sslmode=verify-ca`,
  "pgrep_metric_port": 9187,
  "pgrep_image": "postgres:10",
} satisfies VarsFile;
