// Auto-generated by gen-data.ts from ../devops/roles/icos.pgrep/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "pgrep_home": "/docker/pgrep_{{ pgrep_name }}",
  "pgrep_conninfo":
    "host={{ pgrep_peer_host }} port={{ pgrep_peer_port }} dbname=postgres user={{ pgrep_peer_user }} sslmode=verify-ca",
  "pgrep_metric_port": 9187,
  "pgrep_image": "postgres:10",
} satisfies VarsFile;
