// Auto-generated by gen-data.ts from ../devops/roles/icos.pgrep/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";

interface Self {
  pgrep_home: string;
  pgrep_conninfo: string;
  pgrep_metric_port: string;
  pgrep_image: string;
}
const { V, tmpl } = context<Self & Globals & BuiltinVars>();

export default {
  "pgrep_home": tmpl`/docker/pgrep_${V.pgrep_name}`,
  "pgrep_conninfo":
    tmpl`host=${V.pgrep_peer_host} port=${V.pgrep_peer_port} dbname=postgres user=${V.pgrep_peer_user} sslmode=verify-ca`,
  "pgrep_metric_port": 9187,
  "pgrep_image": "postgres:10",
} satisfies VarsFile;
