// Auto-generated by gen-data.ts from ../devops/roles/icos.nfs4/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "nfs4_interface": null,
  "nfs4_host": null,
} satisfies VarsFile;
