- import_tasks: setup.yml
  tags: cpmetardfstore_setup

- import_tasks: deploy.yml
  tags: cpmetardfstore_deploy
  when: cpmetardfstore_jar_file is defined

- import_tasks: restart.yml
  tags: cpmetardfstore_restart
  vars:
    _restart_needed: true
