- name: Create cpmetardfstore user
  user:
    name: "{{ cpmetardfstore_user }}"
    home: "{{ cpmetardfstore_home }}"
    shell: /bin/bash

- name: Create rdfStorage directory (if not present), take ownership
  file:
    path: "{{ cpmetardfstore_rdfstorage_path }}"
    state: directory
    owner: "{{ cpmetardfstore_user }}"
    group: "{{ cpmetardfstore_user }}"
    # only rdfStore may read/write the store files
    mode: "0700"
    recurse: yes

- name: Add systemd service
  template:
    src: cpmetardfstore.service
    dest: /etc/systemd/system/cpmetardfstore.service
  register: _service

- name: Restart systemd service daemon
  systemd:
    name: cpmetardfstore.service
    enabled: yes
    daemon-reload: yes
  when: _service.changed
