// Auto-generated by gen-data.ts from ../devops/roles/icos.geoip/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  geoip_user: string;
  geoip_home: string;
  geoip_build_dir: string;
  geoip_repo_dir: string;
  geoip_db_dir: string;
  geoip_git_repo: string;
  geoip_git_version: string;
  geoip_host_port: string;
  geoip_nginx_allow_deny: string;
  geoip_python_version: string;
  certbot_domains: string;
  certbot_name: string;
  nginxsite_name: string;
  nginxsite_file: string;
  geoip_domain: string;
}
const { V, expr, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "geoip_user": "geoip",
  "geoip_home": tmpl`${expr("docker_compose_home | default('/docker')")}/geoip`,
  "geoip_build_dir": tmpl`${V.geoip_home}/build`,
  "geoip_repo_dir": tmpl`${V.geoip_build_dir}/repo`,
  "geoip_db_dir": tmpl`${V.geoip_home}/volumes/db`,
  "geoip_git_repo": "https://github.com/ICOS-Carbon-Portal/data",
  "geoip_git_version": "master",
  "geoip_host_port": 8447,
  "geoip_nginx_allow_deny": expr("vault_geoip_nginx_allow_deny"),
  "geoip_python_version": "3.10",
  "certbot_domains": [
    "geoip.icos-cp.eu",
  ],
  "certbot_name": "geoip",
  "nginxsite_name": "geoip",
  "nginxsite_file": "geoip.conf",
  "geoip_domain": "geoip.icos-cp.eu",
} satisfies VarsFile;
