// Auto-generated by gen-data.ts from ../devops/roles/icos.geoip/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "geoip_user": "geoip",
  "geoip_home": tmpl`${expr("docker_compose_home | default('/docker')")}/geoip`,
  "geoip_build_dir": tmpl`${expr("geoip_home")}/build`,
  "geoip_repo_dir": tmpl`${expr("geoip_build_dir")}/repo`,
  "geoip_db_dir": tmpl`${expr("geoip_home")}/volumes/db`,
  "geoip_git_repo": "https://github.com/ICOS-Carbon-Portal/data",
  "geoip_git_version": "master",
  "geoip_host_port": 8447,
  "geoip_nginx_allow_deny": expr("vault_geoip_nginx_allow_deny"),
  "geoip_python_version": "3.10",
  "certbot_domains": [
    "geoip.icos-cp.eu",
  ],
  "certbot_name": "geoip",
  "nginxsite_name": "geoip",
  "nginxsite_file": "geoip.conf",
  "geoip_domain": "geoip.icos-cp.eu",
} satisfies VarsFile;
