// Auto-generated by gen-data.ts from ../devops/roles/icos.certbot/vars/centos.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { SharedVars } from "../../../../lib/sharedvars.ts";

const { V, tmpl } = context<SharedVars>();

export default {
  "certbot_fake_key": tmpl`/etc/pki/tls/private/${V.certbot_conf_name}.key`,
  "certbot_fake_crt": tmpl`/etc/pki/tls/certs/${V.certbot_conf_name}.crt`,
} satisfies VarsFile;
