// Auto-generated by gen-data.ts from ../devops/roles/icos.certbot/vars/centos.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  certbot_fake_key: unknown;
  certbot_fake_crt: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "certbot_fake_key": tmpl`/etc/pki/tls/private/${V.certbot_conf_name}.key`,
  "certbot_fake_crt": tmpl`/etc/pki/tls/certs/${V.certbot_conf_name}.crt`,
} satisfies VarsFile;
