// Auto-generated by gen-data.ts from ../devops/roles/icos.certbot/vars/centos.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "certbot_fake_key": "/etc/pki/tls/private/{{ certbot_conf_name }}.key",
  "certbot_fake_crt": "/etc/pki/tls/certs/{{ certbot_conf_name }}.crt",
} satisfies VarsFile;
