// Auto-generated by gen-data.ts from ../devops/roles/icos.certbot/vars/ubuntu.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  certbot_fake_key: string;
  certbot_fake_crt: string;
}
const { V, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "certbot_fake_key": tmpl`/etc/ssl/private/${V.certbot_conf_name}.key`,
  "certbot_fake_crt": tmpl`/etc/ssl/certs/${V.certbot_conf_name}.crt`,
} satisfies VarsFile;
