// Auto-generated by gen-data.ts from ../devops/roles/icos.certbot/vars/ubuntu.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "certbot_fake_key": tmpl`/etc/ssl/private/${expr("certbot_conf_name")}.key`,
  "certbot_fake_crt": tmpl`/etc/ssl/certs/${expr("certbot_conf_name")}.crt`,
} satisfies VarsFile;
