// Auto-generated by gen-data.ts from ../devops/roles/icos.certbot/vars/ubuntu.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

const { V, tmpl } = context<AllVars>();

export default {
  "certbot_fake_key": tmpl`/etc/ssl/private/${V.certbot_conf_name}.key`,
  "certbot_fake_crt": tmpl`/etc/ssl/certs/${V.certbot_conf_name}.crt`,
} satisfies VarsFile;
