- include_role:
    name: icos.bbclient2
  vars:
    bbclient_user: root
    bbclient_home: "{{ virtuoso_home }}/bbclient"
    bbclient_name: "{{ virtuoso_bbclient_name }}"
    bbclient_timer_conf: "OnCalendar=00/6:45"
    bbclient_timer_content: |
      #!/bin/bash
      set -Eueo pipefail

      cd "{{ virtuoso_home }}"
      mkdir -p backup

      docker compose exec -T virtuoso isql -U dba -P "{{ virtuoso_dba_pass }}" \
        exec="backup_context_clear(); backup_online('backup/virt_backup_', 150);"

      {{ bbclient_all }} create -xvs '::{now}' backup
      {{ bbclient_all }} prune -vs --keep-within 7d --keep-daily=30 --keep-weekly=150
      {{ bbclient_all }} compact --verbose

      rm -rf -- ./backup
