exploredata_port: "{{ 4567 if exploredata_type == 'test' else 4566 }}"
exploredata_name: "exploredata.{{ exploredata_type }}"
exploredata_home: "/docker/{{ exploredata_name }}"
exploredata_network: "{{ exploredata_name }}"
exploredata_hub_image: "{{ exploredata_name }}.hub"
exploredata_hub_container: "{{ exploredata_name }}.hub"
exploredata_icosbase_image : "registry.icos-cp.eu/{{ exploredata_name }}.icosbase"
exploredata_pylib_examples_image : "registry.icos-cp.eu/{{ exploredata_name }}.pylib-examples"
exploredata_icos_notebooks_image : "registry.icos-cp.eu/{{ exploredata_name }}.icos-notebooks"
exploredata_summer_school_image : "registry.icos-cp.eu/{{ exploredata_name }}.summer-school"

exploredata_max_notebooks: 50
