// Auto-generated by gen-data.ts from ../devops/roles/icos.script_exporter/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";

interface Self {
  sexp_home: unknown;
  sexp_config_file: unknown;
  sexp_listen: unknown;
  sexp_arch: unknown;
  sexp_arch_map: unknown;
  sexp_scripts_venv: unknown;
  sexp_scripts_repo: unknown;
  sexp_scripts_enable: unknown;
}
const { V, expr, tmpl } = context<Self>();

export default {
  "sexp_home": "/opt/script_exporter",
  "sexp_config_file": tmpl`${V.sexp_home}/config.yaml`,
  "sexp_listen": "localhost:9469",
  "sexp_arch": expr(
    "sexp_arch_map[ansible_architecture] |\n   default(ansible_architecture)",
  ),
  "sexp_arch_map": {
    "armv7l": "armv7",
    "x86_64": "amd64",
  },
  "sexp_scripts_venv": tmpl`${V.sexp_home}/scripts-venv`,
  "sexp_scripts_repo":
    tmpl`${V.sexp_home}/node-exporter-textfile-collector-scripts`,
  "sexp_scripts_enable": [],
} satisfies VarsFile;
