// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.iptables/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  iptables_mdns: boolean;
  iptables_ssh_port: number;
  iptables_upnp: boolean;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const iptables_mdns = vref("iptables_mdns");
export const iptables_ssh_port = vref("iptables_ssh_port");
export const iptables_upnp = vref("iptables_upnp");
