// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.iptables/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  iptables_mdns: boolean;
  iptables_ssh_port: number;
  iptables_upnp: boolean;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
