// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.iptables/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";

export interface Vars {
  iptables_mdns: boolean;
  iptables_ssh_port: number;
  iptables_upnp: boolean;
}

export const { V, tmpl } = context<
  Vars & Globals
>();
