// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.python_util/{defaults,vars}/*.yml
// Per-role variable context: 4 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  python_util_bin_dir: string;
  python_util_install_dir: string;
  python_util_install_prefix: string;
  python_util_python_executable: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
