// Auto-generated by gen-data.ts from ../devops/roles/icos.zfsdocker/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  zfsdocker_size: unknown;
  zfsdocker_zvol: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "zfsdocker_size": "100G",
  "zfsdocker_zvol": tmpl`/dev/zvol/pool/docker/${V.zfsdocker_name}`,
} satisfies VarsFile;
