// Auto-generated by gen-data.ts from ../devops/roles/icos.zfsdocker/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "zfsdocker_size": "100G",
  "zfsdocker_zvol": tmpl("/dev/zvol/pool/docker/{{ zfsdocker_name }}"),
} satisfies VarsFile;
