// Auto-generated by gen-data.ts from ../devops/roles/icos.zfsdocker/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  zfsdocker_size: string;
  zfsdocker_zvol: string;
}
const { V, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "zfsdocker_size": "100G",
  "zfsdocker_zvol": tmpl`/dev/zvol/pool/docker/${V.zfsdocker_name}`,
} satisfies VarsFile;
