// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.vmagent/{defaults,vars}/*.yml
// Per-role variable context: 20 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  caddy_conf: string;
  caddy_name: string;
  fsd_host: string;
  nginxsite_domains: unknown[];
  nginxsite_file: string;
  nginxsite_name: string;
  nginxsite_users: unknown[];
  vmagent_arch: string;
  vmagent_arch_map: Record<string, unknown>;
  vmagent_auth: unknown;
  vmagent_bin: string;
  vmagent_conf: string;
  vmagent_configs: string;
  vmagent_environ: string;
  vmagent_fsd: string;
  vmagent_home: string;
  vmagent_listen: string;
  vmagent_pathprefix: unknown;
  vmagent_proxy: string;
  vmagent_upgrade: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
