// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.vmagent/{defaults,vars}/*.yml
// Per-role variable context: 18 own variables, widened with
// only the registries this role's task/handler files reference.
import type { Tmpl } from "../../lib/template.ts";
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  caddy_conf: unknown;
  caddy_name: unknown;
  fsd_host: Tmpl;
  nginxsite_domains: unknown;
  nginxsite_file: string;
  nginxsite_name: string;
  nginxsite_users: unknown;
  vmagent_arch: Tmpl;
  vmagent_arch_map: Record<string, string>;
  vmagent_bin: Tmpl;
  vmagent_conf: Tmpl;
  vmagent_configs: Tmpl;
  vmagent_environ: Tmpl;
  vmagent_fsd: Tmpl;
  vmagent_home: string;
  vmagent_listen: string;
  vmagent_proxy: string;
  vmagent_upgrade: Tmpl;
}

export const { V, tmpl } = context<
  Vars & Globals & BuiltinVars & ParamVars
>();
