// Auto-generated by gen-data.ts from ../devops/roles/icos.fail2ban/defaults/main.yml
import { type Vars } from "../../../../roles/icos.fail2ban/_ctx.ts";

export default {
  "fail2ban_config_files": [],
} satisfies Vars;
