// Auto-generated by gen-data.ts from ../devops/roles/icos.fail2ban/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "fail2ban_config_files": [],
} satisfies VarsFile;
