// Auto-generated by gen-data.ts from ../devops/roles/icos.wg_hub/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  wg_hub_self: unknown;
  wg_hub_peer: unknown;
  wg_hub_ishub: unknown;
  wg_hub_port: unknown;
  wg_hub_addr: unknown;
  wg_hub_key_dir: unknown;
  wg_hub_key: unknown;
  wg_hub_intf: unknown;
  wg_hub_allow_all: unknown;
  wg_hub_reresolve: unknown;
}
const { V, expr, tmpl, rawTmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "wg_hub_self": V.wg_hub_config.peers.at(V.inventory_hostname),
  "wg_hub_peer": expr(
    "wg_hub_config.hub.addr if wg_hub_config.hub.addr in wg_hub_config.peers else wg_hub_config.hub.peer",
  ),
  "wg_hub_ishub": expr(
    'wg_hub_config.hub.addr == inventory_hostname or\n   wg_hub_config.hub.peer | default("") == inventory_hostname',
  ),
  "wg_hub_port": tmpl`${
    rawTmpl("{% if wg_hub_self.port is defined -%}")
  } ${V.wg_hub_self.port} ${
    rawTmpl("{% elif wg_hub_ishub -%}")
  } ${V.wg_hub_config.hub.port} ${rawTmpl("{% endif %}")}`,
  "wg_hub_addr": tmpl`${rawTmpl("{% if wg_hub_self.hub_addr is defined -%}")} ${
    rawTmpl("{{ wg_hub_self.hub_addr -}}")
  } ${rawTmpl("{% else -%}")} ${rawTmpl("{{ wg_hub_config.hub.addr -}}")} ${
    rawTmpl("{% endif %}")
  }`,
  "wg_hub_key_dir": "files/wireguard",
  "wg_hub_key": expr(
    "wg_hub_config.peers[wg_hub_peer].key | default(lookup('file', '%s/%s' % (wg_hub_key_dir, wg_hub_peer)))",
  ),
  "wg_hub_intf": tmpl`wg-${V.wg_hub_config.name}`,
  "wg_hub_allow_all": expr(
    "wg_hub_self.allow_all | default(wg_hub_config.allow_all) | default(False)",
  ),
  "wg_hub_reresolve": expr(
    "wg_hub_self.reresolve | default(wg_hub_config.reresolve) | default(False)",
  ),
} satisfies VarsFile;
