// Auto-generated by gen-data.ts from ../devops/roles/icos.wg_hub/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "wg_hub_self": tmpl("{{ wg_hub_config.peers[inventory_hostname] }}"),
  "wg_hub_peer": tmpl(
    "{{ wg_hub_config.hub.addr if wg_hub_config.hub.addr in wg_hub_config.peers else wg_hub_config.hub.peer }}",
  ),
  "wg_hub_ishub": tmpl(
    '{{ wg_hub_config.hub.addr == inventory_hostname or\n   wg_hub_config.hub.peer | default("") == inventory_hostname }}',
  ),
  "wg_hub_port": tmpl(
    "{% if wg_hub_self.port is defined -%} {{ wg_hub_self.port }} {% elif wg_hub_ishub -%} {{ wg_hub_config.hub.port }} {% endif %}",
  ),
  "wg_hub_addr": tmpl(
    "{% if wg_hub_self.hub_addr is defined -%} {{ wg_hub_self.hub_addr -}} {% else -%} {{ wg_hub_config.hub.addr -}} {% endif %}",
  ),
  "wg_hub_key_dir": "files/wireguard",
  "wg_hub_key": tmpl(
    "{{ wg_hub_config.peers[wg_hub_peer].key | default(lookup('file', '%s/%s' % (wg_hub_key_dir, wg_hub_peer))) }}",
  ),
  "wg_hub_intf": tmpl("wg-{{ wg_hub_config.name }}"),
  "wg_hub_allow_all": tmpl(
    "{{ wg_hub_self.allow_all | default(wg_hub_config.allow_all) | default(False) }}",
  ),
  "wg_hub_reresolve": tmpl(
    "{{ wg_hub_self.reresolve | default(wg_hub_config.reresolve) | default(False) }}",
  ),
} satisfies VarsFile;
