// Auto-generated by gen-data.ts from ../devops/roles/icos.wg_hub/defaults/main.yml
import type { Vars } from "../../../../roles/icos.wg_hub/_ctx.ts";
import { jinja } from "../../../../lib/ansible.ts";
import { context } from "../../../../lib/context.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  wg_hub_addr: unknown;
  wg_hub_allow_all: unknown;
  wg_hub_intf: unknown;
  wg_hub_ishub: unknown;
  wg_hub_key: unknown;
  wg_hub_key_dir: unknown;
  wg_hub_peer: unknown;
  wg_hub_port: unknown;
  wg_hub_reresolve: unknown;
  wg_hub_self: unknown;
}
const { V, tmpl } = context<Self & BuiltinVars & VarShapes>();

export default {
  "wg_hub_self": V.wg_hub_config.peers.at(V.inventory_hostname),
  "wg_hub_peer":
    jinja`{{ ${V.wg_hub_config.hub.addr} if ${V.wg_hub_config.hub.addr} in ${V.wg_hub_config.peers} else ${V.wg_hub_config.hub.peer} }}`,
  "wg_hub_ishub":
    jinja`{{ ${V.wg_hub_config.hub.addr} == ${V.inventory_hostname} or
   ${V.wg_hub_config.hub.peer} | default("") == ${V.inventory_hostname} }}`,
  "wg_hub_port":
    tmpl`${jinja`{% if ${V.wg_hub_self.port} is defined -%}`} ${V.wg_hub_self.port} ${jinja`{% elif ${V.wg_hub_ishub} -%}`} ${V.wg_hub_config.hub.port} ${jinja`{% endif %}`}`,
  "wg_hub_addr":
    tmpl`${jinja`{% if wg_hub_self.hub_addr is defined -%}`} ${jinja`{{ wg_hub_self.hub_addr -}}`} ${jinja`{% else -%}`} ${jinja`{{ ${V.wg_hub_config.hub.addr} -}}`} ${jinja`{% endif %}`}`,
  "wg_hub_key_dir": "files/wireguard",
  "wg_hub_key":
    jinja`{{ ${V.wg_hub_config.peers}[${V.wg_hub_peer}].key | default(lookup('file', '%s/%s' % (${V.wg_hub_key_dir}, ${V.wg_hub_peer}))) }}`,
  "wg_hub_intf": tmpl`wg-${V.wg_hub_config.name}`,
  "wg_hub_allow_all":
    jinja`{{ wg_hub_self.allow_all | default(${V.wg_hub_config.allow_all}) | default(False) }}`,
  "wg_hub_reresolve":
    jinja`{{ wg_hub_self.reresolve | default(${V.wg_hub_config.reresolve}) | default(False) }}`,
} satisfies Vars;
