- name: Install qemu-guest-agent
  apt:
    update_cache: true
    name:
      # This one enables interaction with the proxmox host.
      - qemu-guest-agent
  notify: reboot

- name: Set timezone to Europe/Stockholm
  timezone:
    name: Europe/Stockholm
  notify: restart cron

- name: Prioritize qemu guest agent
  copy:
    dest: /etc/systemd/system/qemu-guest-agent.service.d/priority.conf
    content: |
      [Service]
      Nice=-5
      CPUWeight=8000
      IOWeight=8000
      OOMScoreAdjust=-800
  notify: reload systemd

- name: Generate locale
  locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    - en_US.UTF-8
    - sv_SE.UTF-8

- name: Upgrade everything
  apt:
    update_cache: true
    upgrade: true
    autoclean: true
    autoremove: true
  when: upgrade_everything
  notify: reboot
