stiltcluster_username: stiltcluster
stiltcluster_servicename: stiltcluster

stiltcluster_home: /home/stiltcluster
stiltcluster_bindir: "{{ stiltcluster_home }}/bin"

# When installing new cluster nodes without having a stiltcluster development
# environment set up, we can instead fetch stiltcluster.jar from an existing
# cluster host.
stiltcluster_fetch_host:
stiltcluster_fetch_path: >-
  {{ hostvars[stiltcluster_fetch_host].stiltcluster_home
    | default(stiltcluster_home) }}/stiltcluster.jar"

# These hostnames used by akka. They control which interface akka will bind to
# (through the usual unix interface mechanisms). They also needs to be
# reachable by other hosts in the cluster - i.e they need to be resolveable and
# rechable.
stiltcluster_hostname: "{{ inventory_hostname }}"
stiltcluster_stiltweb_hostname: "{{ inventory_hostname }}"

# The port which stiltweb uses for akka.
stiltcluster_stiltweb_port: 2550

# The port which stiltcluster uses for akka. It differs from the one stiltweb
# uses so that they can both run on the same host if need be.
stiltcluster_port: 2561

# 0 == all of them
stiltcluster_maxcores: 0

# By default we use docker, but podman is also supported.
stiltcluster_docker: True
