// Auto-generated by gen-data.ts from ../devops/staging.inventory/group_vars/core_host/vars.yml
import type { Inventory } from "../../../../lib/data.ts";
import { expr } from "../../../../lib/ansible.ts";

export default {
  "postgis_admin_pass": expr("vault_postgis_admin_pass"),
  "postgis_writer_pass": expr("vault_postgis_writer_pass"),
  "postgis_reader_pass": expr("vault_postgis_reader_pass"),
  "rdflog_db_pass": expr("vault_rdflog_db_pass"),
  "doi_admins": expr("vault_doi_admins"),
  "doi_test_password": expr("vault_doi_test_password"),
  "doi_to_addresses": expr("vault_doi_to_addresses"),
} satisfies Inventory;
