// Auto-generated by gen-data.ts from ../devops/roles/icos.rdflog/defaults/main.yml
import type { Vars } from "../../../../roles/icos.rdflog/_ctx.ts";
import type { Restated } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";

const { V } = context<Globals & VaultVars>();

export default {
  "rdflog_home": "/docker/rdflog",
  "rdflog_postgres_version": 15,
  "rdflog_db_name": "rdflog",
  "rdflog_db_user": "rdflog",
  "rdflog_db_port": 2345,
  "rdflog_db_pass": V.vault_rdflog_db_pass,
  "rdflog_rep_user": "pgrepuser",
  "rdflog_rep_pass": V.vault_rdflog_rep_pass,
} satisfies
  & Vars
  & Restated<Globals, "rdflog_postgres_version" | "rdflog_db_pass">;
