// Auto-generated by gen-data.ts from ../devops/roles/icos.rdflog/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  rdflog_home: unknown;
  rdflog_db_name: unknown;
  rdflog_db_user: unknown;
  rdflog_db_port: unknown;
  rdflog_rep_user: unknown;
  rdflog_rep_pass: unknown;
}
const { V } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "rdflog_home": "/docker/rdflog",
  "rdflog_postgres_version": 15,
  "rdflog_db_name": "rdflog",
  "rdflog_db_user": "rdflog",
  "rdflog_db_port": 2345,
  "rdflog_db_pass": V.vault_rdflog_db_pass,
  "rdflog_rep_user": "pgrepuser",
  "rdflog_rep_pass": V.vault_rdflog_rep_pass,
} satisfies VarsFile;
