// Auto-generated by gen-data.ts from ../devops/production.inventory/group_vars/core_host/vars.yml
import type { Inventory } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "postgis_admin_pass": tmpl("{{ vault_postgis_admin_pass }}"),
  "postgis_writer_pass": tmpl("{{ vault_postgis_writer_pass }}"),
  "postgis_reader_pass": tmpl("{{ vault_postgis_reader_pass }}"),
  "rdflog_db_pass": tmpl("{{ vault_rdflog_db_pass }}"),
  "stiltweb_atmoaccess_user_password": tmpl(
    "{{ vault_stiltweb_atmoaccess_user_password }}",
  ),
  "doi_admins": tmpl("{{ vault_doi_admins }}"),
  "doi_to_addresses": tmpl("{{ vault_doi_to_addresses }}"),
  "cpmeta_sentry_dsn": tmpl("{{ vault_cpmeta_sentry_dsn }}"),
  "cpdata_sentry_backend_dsn": tmpl("{{ vault_cpdata_sentry_backend_dsn }}"),
  "cpdata_sentry_portal_dsn": tmpl("{{ vault_cpdata_sentry_portal_dsn }}"),
} satisfies Inventory;
