// Auto-generated by gen-data.ts from ../devops/production.inventory/group_vars/core_host/vars.yml
import type { Inventory } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";

const { V, expr } = context<VaultVars>();

export default {
  "postgis_admin_pass": V.vault_postgis_admin_pass,
  "postgis_writer_pass": V.vault_postgis_writer_pass,
  "postgis_reader_pass": V.vault_postgis_reader_pass,
  "rdflog_db_pass": V.vault_rdflog_db_pass,
  "stiltweb_atmoaccess_user_password": expr(
    "vault_stiltweb_atmoaccess_user_password",
  ),
  "doi_admins": V.vault_doi_admins,
  "doi_to_addresses": V.vault_doi_to_addresses,
  "cpmeta_sentry_dsn": V.vault_cpmeta_sentry_dsn,
  "cpdata_sentry_backend_dsn": V.vault_cpdata_sentry_backend_dsn,
  "cpdata_sentry_portal_dsn": V.vault_cpdata_sentry_portal_dsn,
} satisfies Inventory;
