// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.github_download_bin/{defaults,vars}/*.yml
// Per-role variable context: 13 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  _dbin_name: Tmpl;
  _dbin_path: Tmpl;
  _dbin_src: Tmpl;
  _dbin_unar: Tmpl;
  _dbin_url: Tmpl;
  dbin__down: Tmpl;
  dbin__plat: Tmpl;
  dbin__vers: Tmpl;
  dbin_arch: string;
  dbin_bin_dir: string;
  dbin_default_url: Tmpl;
  dbin_download_base: string;
  dbin_download_dest: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const _dbin_name = vref("_dbin_name");
export const _dbin_path = vref("_dbin_path");
export const _dbin_src = vref("_dbin_src");
export const _dbin_unar = vref("_dbin_unar");
export const _dbin_url = vref("_dbin_url");
export const dbin__down = vref("dbin__down");
export const dbin__plat = vref("dbin__plat");
export const dbin__vers = vref("dbin__vers");
export const dbin_arch = vref("dbin_arch");
export const dbin_bin_dir = vref("dbin_bin_dir");
export const dbin_default_url = vref("dbin_default_url");
export const dbin_download_base = vref("dbin_download_base");
export const dbin_download_dest = vref("dbin_download_dest");
