// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.github_download_bin/{defaults,vars}/*.yml
// Per-role variable context: 13 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  _dbin_name: string;
  _dbin_path: string;
  _dbin_src: string;
  _dbin_unar: string;
  _dbin_url: string;
  dbin__down: string;
  dbin__plat: string;
  dbin__vers: string;
  dbin_arch: string;
  dbin_bin_dir: string;
  dbin_default_url: string;
  dbin_download_base: string;
  dbin_download_dest: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
