// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.github_download_bin/{defaults,vars}/*.yml
// Per-role variable context: 13 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  _dbin_name: unknown;
  _dbin_path: unknown;
  _dbin_src: unknown;
  _dbin_unar: unknown;
  _dbin_url: unknown;
  dbin__down: unknown;
  dbin__plat: unknown;
  dbin__vers: unknown;
  dbin_arch: unknown;
  dbin_bin_dir: unknown;
  dbin_default_url: unknown;
  dbin_download_base: unknown;
  dbin_download_dest: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & ParamVars
>();
