
cpauth.restheart.ipsToIgnore = []

cpauth.oauth.ICOS{
			envriId.redirectPath = "https://{{ cpauth_icos_domain }}/oauth/envriId"
			envriId.issuer = "https://login.staging.envri.eu/auth/realms/envri"
}

