// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nexus/{defaults,vars}/*.yml
// Per-role variable context: 8 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  certbot_domains: Tmpl;
  certbot_name: string;
  nexus_domains: unknown;
  nexus_home: Tmpl;
  nexus_host_port: number;
  nexus_version: string;
  nginxsite_file: string;
  nginxsite_name: string;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
