// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nexus/{defaults,vars}/*.yml
// Per-role variable context: 8 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  certbot_domains: Tmpl;
  certbot_name: string;
  nexus_domains: unknown;
  nexus_home: Tmpl;
  nexus_host_port: number;
  nexus_version: string;
  nginxsite_file: string;
  nginxsite_name: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const certbot_domains = vref("certbot_domains");
export const certbot_name = vref("certbot_name");
export const nexus_domains = vref("nexus_domains");
export const nexus_home = vref("nexus_home");
export const nexus_host_port = vref("nexus_host_port");
export const nexus_version = vref("nexus_version");
export const nginxsite_file = vref("nginxsite_file");
export const nginxsite_name = vref("nginxsite_name");
