// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.stiltcluster/{defaults,vars}/*.yml
// Per-role variable context: 8 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  stiltcluster_bindir: Tmpl;
  stiltcluster_docker: boolean;
  stiltcluster_home: string;
  stiltcluster_maxcores: number;
  stiltcluster_port: number;
  stiltcluster_servicename: string;
  stiltcluster_stiltweb_port: number;
  stiltcluster_username: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const stiltcluster_bindir = vref("stiltcluster_bindir");
export const stiltcluster_docker = vref("stiltcluster_docker");
export const stiltcluster_home = vref("stiltcluster_home");
export const stiltcluster_maxcores = vref("stiltcluster_maxcores");
export const stiltcluster_port = vref("stiltcluster_port");
export const stiltcluster_servicename = vref("stiltcluster_servicename");
export const stiltcluster_stiltweb_port = vref("stiltcluster_stiltweb_port");
export const stiltcluster_username = vref("stiltcluster_username");
