// Auto-generated by gen-data.ts from ../devops/roles/icos.jupyter/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "jupyter_home": "/docker/jupyter",
  "jupyter_port": 8000,
  "jupyter_jusers_enable": false,
  "jupyter_hub_config_defaults": {
    "user_volumes": {},
    "admin_users": [],
    "image": "registry.icos-cp.eu/icosbase",
  },
  "jupyter_hub_config": {},
  "jusers_home": "/opt/jusers",
  "jusers_venv": tmpl("{{ jusers_home }}/venv"),
} satisfies VarsFile;
