// Auto-generated by gen-data.ts from ../devops/roles/icos.jupyter/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";

interface Self {
  jupyter_home: unknown;
  jupyter_port: unknown;
  jupyter_jusers_enable: unknown;
  jupyter_hub_config_defaults: unknown;
  jupyter_hub_config: unknown;
  jusers_home: unknown;
  jusers_venv: unknown;
}
const { V, tmpl } = context<Self>();

export default {
  "jupyter_home": "/docker/jupyter",
  "jupyter_port": 8000,
  "jupyter_jusers_enable": false,
  "jupyter_hub_config_defaults": {
    "user_volumes": {},
    "admin_users": [],
    "image": "registry.icos-cp.eu/icosbase",
  },
  "jupyter_hub_config": {},
  "jusers_home": "/opt/jusers",
  "jusers_venv": tmpl`${V.jusers_home}/venv`,
} satisfies VarsFile;
