// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.utils/{defaults,vars}/*.yml
// Per-role variable context: 20 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  btop_home: string;
  btop_url_map: Record<string, unknown>;
  btop_version: string;
  fd_architecture: string;
  fd_url_map: Record<string, unknown>;
  fd_version: string;
  lazygit_architecture: string;
  lazygit_upgrade: string;
  lazygit_url_map: Record<string, unknown>;
  lazygit_version: string;
  ncdu_arch_map: Record<string, unknown>;
  ncdu_url: string;
  ncdu_version: number;
  ripgrep_url_map: Record<string, unknown>;
  ripgrep_version: string;
  trippy_url_map: Record<string, unknown>;
  trippy_version: string;
  watchexec_architecture: string;
  watchexec_url_map: Record<string, unknown>;
  watchexec_version: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
