// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.utils/{defaults,vars}/*.yml
// Per-role variable context: 20 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  btop_home: string;
  btop_url_map: Record<string, Tmpl>;
  btop_version: Tmpl;
  fd_architecture: Tmpl;
  fd_url_map: Record<string, Tmpl>;
  fd_version: Tmpl;
  lazygit_architecture: Tmpl;
  lazygit_upgrade: Tmpl;
  lazygit_url_map: Record<string, Tmpl>;
  lazygit_version: Tmpl;
  ncdu_arch_map: Record<string, string>;
  ncdu_url: Tmpl;
  ncdu_version: number;
  ripgrep_url_map: Record<string, Tmpl>;
  ripgrep_version: Tmpl;
  trippy_url_map: Record<string, Tmpl>;
  trippy_version: Tmpl;
  watchexec_architecture: Tmpl;
  watchexec_url_map: Record<string, Tmpl>;
  watchexec_version: Tmpl;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
