// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.opendkim/{defaults,vars}/*.yml
// Per-role variable context: 4 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  opendkim_domains_testkeys: unknown[];
  opendkim_keys: string;
  opendkim_sock: string;
  opendkim_user: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
