import { V } from "../_ctx.ts";
import { type TaskFile } from "../../../lib/ansible/play.ts";
import { rsyncd_conf } from "../../../lib/paramvars.ts";
import { register } from "../../../lib/register.ts";
import { iff } from "../../../lib/template.ts";

const _justfile = register("_justfile");

export default [
  {
    name: "Install rsync",
    apt: { name: ["rsync"] },
  },
  {
    name: "Add config block to /etc/rsyncd.conf",
    copy: {
      dest: "/etc/rsyncd.conf",
      content: rsyncd_conf,
    },
    notify: "restart rsync",
  },
  {
    name: "Make sure that /etc/rsyncd.secrets exists",
    lineinfile: {
      path: "/etc/rsyncd.secrets",
      mode: 0o600,
      line: "# this file is partly generated by ansible",
      create: true,
      insertbefore: "BOF",
    },
  },
  {
    name: "Start rsync service",
    systemd: {
      name: "rsync",
      enabled: V.rsyncd_enable,
      state: iff(V.rsyncd_enable, "started", "stopped"),
    },
  },
  {
    name: "Copy justfile",
    template: {
      src: "ops-rsyncd",
      dest: "/usr/local/bin/",
      mode: "+x",
      variable_start_string: "((",
      variable_end_string: "))",
      lstrip_blocks: true,
    },
    register: _justfile,
  },
  {
    name: "Check that the justfile is executable",
    shell: _justfile.dest.ref,
    changed_when: false,
  },
] satisfies TaskFile;
