// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.sshlogin/{defaults,vars}/*.yml
// Per-role variable context: 16 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

export interface Vars {
  _sshlogin_opt_list: string;
  sshlogin_dst_command: string;
  sshlogin_dst_from: string;
  sshlogin_dst_key_file: string;
  sshlogin_dst_key_options: string;
  sshlogin_dst_known_hosts: string;
  sshlogin_dst_restrict: string;
  sshlogin_dst_ssh_dir: string;
  sshlogin_src_dst: string;
  sshlogin_src_dst_host: string;
  sshlogin_src_dst_name: string;
  sshlogin_src_dst_port: string;
  sshlogin_src_key_file: string;
  sshlogin_src_known_hosts: string;
  sshlogin_src_ssh_config: string;
  sshlogin_src_ssh_dir: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars
>();
