// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.sshlogin/{defaults,vars}/*.yml
// Per-role variable context: 16 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  _sshlogin_opt_list: unknown;
  sshlogin_dst_command: null;
  sshlogin_dst_from: null;
  sshlogin_dst_key_file: Tmpl;
  sshlogin_dst_key_options: Tmpl;
  sshlogin_dst_known_hosts: Tmpl;
  sshlogin_dst_restrict: null;
  sshlogin_dst_ssh_dir: Tmpl;
  sshlogin_src_dst: Tmpl;
  sshlogin_src_dst_host: Tmpl;
  sshlogin_src_dst_name: Tmpl;
  sshlogin_src_dst_port: Tmpl;
  sshlogin_src_key_file: Tmpl;
  sshlogin_src_known_hosts: Tmpl;
  sshlogin_src_ssh_config: Tmpl;
  sshlogin_src_ssh_dir: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const _sshlogin_opt_list = vref("_sshlogin_opt_list");
export const sshlogin_dst_command = vref("sshlogin_dst_command");
export const sshlogin_dst_from = vref("sshlogin_dst_from");
export const sshlogin_dst_key_file = vref("sshlogin_dst_key_file");
export const sshlogin_dst_key_options = vref("sshlogin_dst_key_options");
export const sshlogin_dst_known_hosts = vref("sshlogin_dst_known_hosts");
export const sshlogin_dst_restrict = vref("sshlogin_dst_restrict");
export const sshlogin_dst_ssh_dir = vref("sshlogin_dst_ssh_dir");
export const sshlogin_src_dst = vref("sshlogin_src_dst");
export const sshlogin_src_dst_host = vref("sshlogin_src_dst_host");
export const sshlogin_src_dst_name = vref("sshlogin_src_dst_name");
export const sshlogin_src_dst_port = vref("sshlogin_src_dst_port");
export const sshlogin_src_key_file = vref("sshlogin_src_key_file");
export const sshlogin_src_known_hosts = vref("sshlogin_src_known_hosts");
export const sshlogin_src_ssh_config = vref("sshlogin_src_ssh_config");
export const sshlogin_src_ssh_dir = vref("sshlogin_src_ssh_dir");
