// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.timer/{defaults,vars}/*.yml
// Per-role variable context: 8 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  _timer_sysd_service: string;
  _timer_sysd_timer: string;
  timer_desc: string;
  timer_dest: string;
  timer_exec: string;
  timer_home: string;
  timer_user: string;
  timer_wdir: unknown;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
