// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.timer/{defaults,vars}/*.yml
// Per-role variable context: 8 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { ParamVars } from "../../lib/paramvars.ts";
import type { VaultVars } from "../../lib/vaultvars.ts";
import type { VarShapes } from "../../lib/shapes.ts";

export interface Vars {
  _timer_sysd_service: unknown;
  _timer_sysd_timer: unknown;
  timer_desc: unknown;
  timer_dest: unknown;
  timer_exec: unknown;
  timer_home: unknown;
  timer_user: unknown;
  timer_wdir: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();
