- name: Don't create timer script in /etc/systemd/system
  assert:
    that: timer_home != "/etc/systemd/systemd"
  changed_when: no
  when: timer_content is defined

- name: Create home directory
  when: timer_home != "/etc/systemd/systemd"
  file:
    path: "{{ timer_home }}"
    state: directory

- name: Create timer script
  copy:
    dest: "{{ timer_dest }}"
    mode: +x
    content: "{{ timer_content }}"
  when: timer_content is defined

- name: Create systemd timer definition
  copy:
    dest: "{{ _timer_sysd_timer }}"
    content: |
      [Unit]
      Description={{ timer_desc }}

      [Timer]
      {{ timer_conf }}

      [Install]
      WantedBy=timers.target
  notify: restart icos timer

- name: Create systemd service
  copy:
    dest: "{{ _timer_sysd_service }}"
    content: |
      [Unit]
      Description={{ timer_desc }}

      [Service]
      User={{ timer_user }}
      Type=oneshot
      ExecStart={{ timer_exec }}
      {% for env in timer_envs | default([]) -%}
      Environment={{ env }}
      {% endfor -%}
      {% if timer_wdir %}
      WorkingDirectory={{ timer_wdir }}
      {% endif %}

- name: Link systemd files
  when: timer_home != "/etc/systemd/system"
  # noqa: command-instead-of-module
  command:  systemctl link {{ _timer_sysd_timer }} {{ _timer_sysd_service }}
  register: _r
  failed_when: _r.rc != 0
  changed_when: '"Created" in _r.stdout'

- name: Start timer
  when: not ansible_check_mode
  systemd:
    name: "{{ timer_name }}.timer"
    enabled: yes
    state: started
    daemon_reload: yes
