// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.certbot/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables, widened with
// only the registries this role's task/handler files reference.
import type { Tmpl } from "../../lib/ansible.ts";
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

export interface Vars {
  certbot_bin: string;
  certbot_conf_path: Tmpl;
  certbot_disabled: boolean;
  certbot_email: string;
  certbot_fake_certificate: boolean;
  certbot_fake_cn: Tmpl;
  certbot_fake_crt: Tmpl;
  certbot_fake_key: Tmpl;
  certbot_live_crt: Tmpl;
  certbot_live_key: Tmpl;
}

export const { V, tmpl, notVar } = context<
  Vars & BuiltinVars & AllVars
>();
