// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.certbot/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

export interface Vars {
  certbot_bin: unknown;
  certbot_conf_path: unknown;
  certbot_disabled: unknown;
  certbot_email: unknown;
  certbot_fake_certificate: unknown;
  certbot_fake_cn: unknown;
  certbot_fake_crt: unknown;
  certbot_fake_key: unknown;
  certbot_live_crt: unknown;
  certbot_live_key: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & BuiltinVars & AllVars
>();
