// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nginx/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  nginx_certbot_bin: string;
  nginx_metrics_addr: string;
  nginx_metrics_enable: boolean;
  nginx_metrics_url: string;
  nginx_user: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const nginx_certbot_bin = vref("nginx_certbot_bin");
export const nginx_metrics_addr = vref("nginx_metrics_addr");
export const nginx_metrics_enable = vref("nginx_metrics_enable");
export const nginx_metrics_url = vref("nginx_metrics_url");
export const nginx_user = vref("nginx_user");
