// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nginx/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";

export interface Vars {
  nginx_certbot_bin: unknown;
  nginx_metrics_addr: unknown;
  nginx_metrics_enable: unknown;
  nginx_metrics_url: unknown;
  nginx_user: unknown;
}

export const { V, tmpl, isDef } = context<
  Vars & Globals
>();
