// Auto-generated by gen-data.ts from ../devops/roles/icos.mosh/defaults/main.yml
import { type Vars } from "../../../../roles/icos.mosh/_ctx.ts";

export default {
  "mosh_add_firewall": true,
} satisfies Vars;
