// Auto-generated by gen-data.ts from ../devops/roles/icos.mosh/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "mosh_add_firewall": true,
} satisfies VarsFile;
