// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.sftp_user/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, type VarRef, varProxy } from "../../lib/template.ts";

export interface Vars {
  _sftp_create_home: Tmpl;
  _sftp_parent_dir: Tmpl;
  sftp_user_group: Tmpl;
  sftp_user_hostdesc: Tmpl;
  sftp_user_owner: Tmpl;
  sftp_user_password: null;
  sftp_user_pubkey: null;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } =
  new Proxy({}, { get: (_t, name: string) => varProxy(name) }) as
    { readonly [K in keyof Vars]: VarRef<Vars[K]> };
