// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.sftp_user/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

export interface Vars {
  _sftp_create_home: string;
  _sftp_parent_dir: string;
  sftp_user_group: string;
  sftp_user_hostdesc: string;
  sftp_user_owner: string;
  sftp_user_password: string;
  sftp_user_pubkey: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars
>();
