// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.sftp_user/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { ParamVars } from "../../lib/paramvars.ts";
import type { VaultVars } from "../../lib/vaultvars.ts";

export interface Vars {
  _sftp_create_home: unknown;
  _sftp_parent_dir: unknown;
  sftp_user_group: unknown;
  sftp_user_hostdesc: unknown;
  sftp_user_owner: unknown;
  sftp_user_password: unknown;
  sftp_user_pubkey: unknown;
}

export const { V, tmpl } = context<
  Vars & BuiltinVars & ParamVars & VaultVars
>();
