// Auto-generated by gen-data.ts from ../devops/roles/icos.dokku/defaults/main.yml
import { type Vars } from "../../../../roles/icos.dokku/_ctx.ts";

export default {
  "dokku_ssh_port": 3022,
  "dokku_http_port": 8008,
  "dokku_home": "/opt/dokku",
  "dokku_data": "/var/lib/dokku",
} satisfies Vars;
