// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nginxauth/{defaults,vars}/*.yml
// Per-role variable context: 3 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  nginxauth_conf: string;
  nginxauth_file: string;
  nginxauth_title: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
