// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nginxauth/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables, widened with
// only the registries this role's task/handler files reference.
import type { Tmpl } from "../../lib/template.ts";
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { SharedVars } from "../../lib/sharedvars.ts";

export interface Vars {
  nginxauth_conf: Tmpl;
  nginxauth_file: Tmpl;
  nginxauth_title: string;
}

export const { V, tmpl } = context<
  Vars & BuiltinVars & SharedVars
>();
