// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nginxauth/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  nginxauth_conf: Tmpl;
  nginxauth_file: Tmpl;
  nginxauth_title: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const nginxauth_conf = vref("nginxauth_conf");
export const nginxauth_file = vref("nginxauth_file");
export const nginxauth_title = vref("nginxauth_title");
