// Auto-generated by gen-data.ts from ../devops/roles/icos.podman/vars/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "podman_arch": {
    "x86_64": "amd64",
  },
} satisfies VarsFile;
