- name: Create application.conf
  copy:
    dest: "{{ cpdata_home }}/application.conf"
    content: |
      {% for item in cpdata_config_files %}
      # {{ item }}
      {{ lookup('template', item) }}

      {% endfor %}
  register: _config

- name: Start/restart service
  systemd:
    name: cpdata.service
    enabled: yes
    daemon-reload: "{{ _service.changed | default(False) }}"
    state: >-
      {{ 'restarted' if _jarfile.changed | default(False) or _config.changed else 'started' }}
