// Auto-generated by gen-data.ts from ../devops/roles/icos.cni_plugins/defaults/main.yml
import type { Vars } from "../../../../roles/icos.cni_plugins/_ctx.ts";
import { register } from "../../../../lib/register.ts";
import { context } from "../../../../lib/context.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { SharedVars } from "../../../../lib/sharedvars.ts";

const { V, tmpl } = context<BuiltinVars & SharedVars>();

export default {
  "cni_plugin_url":
    tmpl`https://github.com/containernetworking/plugins/releases/download/${
      register("podman_release").tag.ref
    }/cni-plugins-linux-${V.podman_arch.at(V.ansible_machine)}-${
      register("podman_release").tag.ref
    }.tgz`,
} satisfies Vars;
