// Auto-generated by gen-data.ts from ../devops/roles/icos.cni_plugins/defaults/main.yml
import { ansible_machine } from "../../../../lib/builtins.ts";
import { register } from "../../../../lib/register.ts";
import { podman_arch } from "../../../../lib/sharedvars.ts";
import { tmpl } from "../../../../lib/template.ts";
import { type Vars } from "../../../../roles/icos.cni_plugins/_ctx.ts";

export default {
  "cni_plugin_url":
    tmpl`https://github.com/containernetworking/plugins/releases/download/${
      register("podman_release").tag.ref
    }/cni-plugins-linux-${podman_arch.at(ansible_machine)}-${
      register("podman_release").tag.ref
    }.tgz`,
} satisfies Vars;
