// Auto-generated by gen-data.ts from ../devops/roles/icos.cni_plugins/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "cni_plugin_url": tmpl(
    "https://github.com/containernetworking/plugins/releases/download/{{ podman_release.tag }}/cni-plugins-linux-{{ podman_arch[ansible_machine] }}-{{ podman_release.tag }}.tgz",
  ),
} satisfies VarsFile;
