// Auto-generated by gen-data.ts from ../devops/roles/icos.pipx/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "pipx_home": "/opt/pipx",
  "pipx_upgrade": tmpl("{{ upgrade_everything | default(False) | bool }}"),
} satisfies VarsFile;
