// Auto-generated by gen-data.ts from ../devops/roles/icos.pipx/defaults/main.yml
import type { Vars } from "../../../../roles/icos.pipx/_ctx.ts";
import { context } from "../../../../lib/context.ts";
import type { SharedVars } from "../../../../lib/sharedvars.ts";

const { V } = context<SharedVars>();

export default {
  "pipx_home": "/opt/pipx",
  "pipx_upgrade": V.upgrade_everything.default(false).bool(),
} satisfies Vars;
