// Auto-generated by gen-data.ts from ../devops/roles/icos.pipx/defaults/main.yml
import { upgrade_everything } from "../../../../lib/sharedvars.ts";
import { type Vars } from "../../../../roles/icos.pipx/_ctx.ts";

export default {
  "pipx_home": "/opt/pipx",
  "pipx_upgrade": upgrade_everything.default(false).bool()
} satisfies Vars;
