// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.dnsmasq/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  dnsmasq_config_dir: Tmpl;
  dnsmasq_config_file: Tmpl;
  dnsmasq_config_name: string;
  dnsmasq_config_state: string;
  dnsmasq_hosts: null;
  dnsmasq_service_name: Tmpl;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
