// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.dnsmasq/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  dnsmasq_config_dir: unknown;
  dnsmasq_config_file: unknown;
  dnsmasq_config_name: unknown;
  dnsmasq_config_state: unknown;
  dnsmasq_hosts: unknown;
  dnsmasq_service_name: unknown;
}

export const { V, tmpl } = context<
  Vars & ParamVars
>();
