# RIPGREP
ripgrep_version: "{{ hostvars.localhost.ripgrep_version }}"
ripgrep_url_map:
  "x86_64": "https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep_{{ ripgrep_version }}-1_amd64.deb"


# NCDU
# ncdu is not on github, just hardcode a version
ncdu_version: 2.3
ncdu_arch_map:
  "armv7l": "arm"
  "x86_64": "x86_64"
  "aarch64": "aarch64"
ncdu_url: "https://dev.yorhel.nl/download/ncdu-{{ ncdu_version }}-linux-{{ ncdu_arch_map[ansible_architecture] }}.tar.gz"


# FD
fd_architecture: "{{ fake_architecture | default(ansible_architecture) }}"
fd_version: "{{ hostvars.localhost.fd_version }}"
fd_url_map:
  "armv6l": "https://github.com/sharkdp/fd/releases/download/v{{ fd_version }}/fd-v{{ fd_version }}-arm-unknown-linux-gnueabihf.tar.gz"
  "armv7l": "https://github.com/sharkdp/fd/releases/download/v{{ fd_version }}/fd-v{{ fd_version }}-arm-unknown-linux-gnueabihf.tar.gz"
  "aarch64": "https://github.com/sharkdp/fd/releases/download/v{{ fd_version }}/fd-v{{ fd_version }}-aarch64-unknown-linux-gnu.tar.gz"
  "x86_64": "https://github.com/sharkdp/fd/releases/download/v{{ fd_version }}/fd-musl_{{ fd_version }}_amd64.deb"


# WATCHEXEC
watchexec_architecture: "{{ fake_architecture | default(ansible_architecture) }}"
watchexec_version: "{{ hostvars.localhost.watchexec_version }}"
watchexec_url_map:
  "armv7l": "https://github.com/watchexec/watchexec/releases/download/v{{ watchexec_version }}/watchexec-{{ watchexec_version }}-armv7-unknown-linux-gnueabihf.deb"
  "aarch64": "https://github.com/watchexec/watchexec/releases/download/v{{ watchexec_version }}/watchexec-{{ watchexec_version }}-aarch64-unknown-linux-gnu.deb"
  # use musl version to avoid GLIBC_2.39 mismatch when installing on debian bookworm
  "x86_64": "https://github.com/watchexec/watchexec/releases/download/v{{ watchexec_version }}/watchexec-{{ watchexec_version }}-x86_64-unknown-linux-musl.deb"


# BTOP
btop_version: "{{ hostvars.localhost.btop_version }}"
btop_home: /opt
btop_url_map:
  "armv6l": "https://github.com/aristocratos/btop/releases/download/v{{ btop_version }}/btop-armv5l-linux-musleabi.tbz"
  "armv7l": "https://github.com/aristocratos/btop/releases/download/v{{ btop_version }}/btop-armv7l-linux-musleabihf.tbz"
  "aarch64": "https://github.com/aristocratos/btop/releases/download/v{{ btop_version }}/btop-aarch64-linux-musl.tbz"
  "x86_64": "https://github.com/aristocratos/btop/releases/download/v{{ btop_version }}/btop-x86_64-linux-musl.tbz"


# TRIPPY
trippy_version: "{{ hostvars.localhost.trippy_version }}"
trippy_url_map:
  "armv7l": "https://github.com/fujiapple852/trippy/releases/download/{{ trippy_version }}/trippy-{{ trippy_version }}-armv7-unknown-linux-musleabi.tar.gz"
  "aarch64": "https://github.com/fujiapple852/trippy/releases/download/{{ trippy_version }}/trippy-{{ trippy_version }}-aarch64-unknown-linux-musl.tar.gz"
  "x86_64": "https://github.com/fujiapple852/trippy/releases/download/{{ trippy_version }}/trippy-{{ trippy_version }}-x86_64-unknown-linux-gnu.tar.gz"


# LAZYGIT
lazygit_upgrade: "{{ upgrade_everything | default(False) | bool }}"
lazygit_architecture: "{{ fake_architecture | default(ansible_architecture) }}"
lazygit_version: "{{ hostvars.localhost.lazygit_version }}"
lazygit_url_map:
  "armv6l": "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_armv6.tar.gz"
  "armv7l": "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_armv6.tar.gz"
  "aarch64": "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_arm64.tar.gz"
  "x86_64": "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
