// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.jupyter/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

export interface Vars {
  jupyter_home: string;
  jupyter_hub_config: string;
  jupyter_hub_config_defaults: string;
  jupyter_jusers_enable: string;
  jupyter_port: string;
  jusers_home: string;
  jusers_venv: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars
>();
