// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.jupyter/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  jupyter_home: string;
  jupyter_hub_config: Record<string, unknown>;
  jupyter_hub_config_defaults: Record<string, unknown>;
  jupyter_jusers_enable: boolean;
  jupyter_port: number;
  jusers_home: string;
  jusers_venv: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
