// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.jupyter/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";
import type { VarValue } from "../../lib/ansible/values.ts";

export interface Vars {
  jupyter_home: string;
  jupyter_hub_config: Record<string, VarValue>;
  jupyter_hub_config_defaults: Record<string, VarValue>;
  jupyter_jusers_enable: boolean;
  jupyter_port: unknown;
  jusers_home: string;
  jusers_venv: Tmpl;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
