// Auto-generated by gen-data.ts from ../devops/roles/icos.stiltcluster/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";

interface Self {
  stiltcluster_username: unknown;
  stiltcluster_servicename: unknown;
  stiltcluster_home: unknown;
  stiltcluster_bindir: unknown;
  stiltcluster_stiltweb_port: unknown;
  stiltcluster_port: unknown;
  stiltcluster_maxcores: unknown;
  stiltcluster_docker: unknown;
}
const { V, expr, tmpl } = context<Self & BuiltinVars>();

export default {
  "stiltcluster_username": "stiltcluster",
  "stiltcluster_servicename": "stiltcluster",
  "stiltcluster_home": "/home/stiltcluster",
  "stiltcluster_bindir": tmpl`${V.stiltcluster_home}/bin`,
  "stiltcluster_fetch_host": null,
  "stiltcluster_fetch_path": tmpl`${
    expr(
      "hostvars[stiltcluster_fetch_host].stiltcluster_home\n  | default(stiltcluster_home)",
    )
  }/stiltcluster.jar"`,
  "stiltcluster_hostname": V.inventory_hostname,
  "stiltcluster_stiltweb_hostname": V.inventory_hostname,
  "stiltcluster_stiltweb_port": 2550,
  "stiltcluster_port": 2561,
  "stiltcluster_maxcores": 0,
  "stiltcluster_docker": true,
} satisfies VarsFile;
