// Auto-generated by gen-data.ts from ../devops/roles/icos.stiltcluster/defaults/main.yml
import { hostvars, inventory_hostname } from "../../../../lib/builtins.ts";
import { type Restated } from "../../../../lib/data.ts";
import { type Globals, stiltcluster_fetch_host } from "../../../../lib/globals.ts";
import { jinja, tmpl } from "../../../../lib/template.ts";
import { V, type Vars } from "../../../../roles/icos.stiltcluster/_ctx.ts";

export default {
  "stiltcluster_username": "stiltcluster",
  "stiltcluster_servicename": "stiltcluster",
  "stiltcluster_home": "/home/stiltcluster",
  "stiltcluster_bindir": tmpl`${V.stiltcluster_home}/bin`,
  "stiltcluster_fetch_host": null,
  "stiltcluster_fetch_path": tmpl`${jinja`{{ ${hostvars}[${stiltcluster_fetch_host}].stiltcluster_home
  | default(${V.stiltcluster_home}) }}`}/stiltcluster.jar"`,
  "stiltcluster_hostname": inventory_hostname,
  "stiltcluster_stiltweb_hostname": inventory_hostname,
  "stiltcluster_stiltweb_port": 2550,
  "stiltcluster_port": 2561,
  "stiltcluster_maxcores": 0,
  "stiltcluster_docker": true
} satisfies Vars & Restated<Globals, "stiltcluster_fetch_host" | "stiltcluster_fetch_path" | "stiltcluster_hostname" | "stiltcluster_stiltweb_hostname">;
