// Auto-generated by gen-data.ts from ../devops/roles/icos.rsyncd/defaults/main.yml
import { type Vars } from "../../../../roles/icos.rsyncd/_ctx.ts";

export default {
  "rsyncd_enable": true
} satisfies Vars;
