// Auto-generated by gen-data.ts from ../devops/roles/icos.rsyncd/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "rsyncd_enable": true,
} satisfies VarsFile;
