- name: Get latest borg archive for {{ postgresql_container_name }}
  ansible.builtin.shell:
    cmd: >-
      BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=y
      BORG_RELOCATED_REPO_ACCESS_IS_OK=y
      BORG_REPO={{ postgresql_backup_host }}:{{ postgresql_backup_location }}
      {{ borg_bin }} list --short --last 1
  register: _archive

- name: Restore "{{ postgresql_container_name }}" database from backup
  ansible.builtin.shell:
    cmd: >-
      BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=y
      BORG_RELOCATED_REPO_ACCESS_IS_OK=y
      BORG_REPO={{ postgresql_backup_host }}:{{ postgresql_backup_location }}
      {{ borg_bin }} extract --stdout ::{{ _archive.stdout }}
      {{ "| egrep -v '^(CREATE|ALTER) ROLE'" if postgresql_norole | default(false) else '' }}
      | docker exec -i {{ postgresql_container_name }} psql -U {{ postgresql_user }}
