// Auto-generated by gen-data.ts from ../devops/roles/icos.plausible/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  plausible_home: unknown;
  plausible_port: unknown;
  plausible_domain: unknown;
  plausible_postgres_password: unknown;
  plausible_secret: unknown;
  plausible_google_client_id: unknown;
  plausible_google_client_secret: unknown;
  plausible_mailer_email: unknown;
  plausible_backup_enabled: unknown;
  plausible_totp_key: unknown;
}
const { V, expr } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "plausible_home": "/opt/plausible",
  "plausible_port": 8701,
  "plausible_domain": "plausible.fieldsites.se",
  "plausible_postgres_password": V.vault_plausible_postgres_password,
  "plausible_secret": V.vault_plausible_secret,
  "plausible_google_client_id": V.vault_plausible_google_client_id,
  "plausible_google_client_secret": expr(
    "vault_plausible_google_client_secret",
  ),
  "plausible_mailer_email": V.vault_plausible_mailer_email,
  "plausible_backup_enabled": false,
  "plausible_totp_key": V.vault_plausible_totp_key,
} satisfies VarsFile;
