// Auto-generated by gen-data.ts from ../devops/roles/icos.plausible/defaults/main.yml
import { vault_plausible_google_client_id, vault_plausible_google_client_secret, vault_plausible_mailer_email, vault_plausible_postgres_password, vault_plausible_secret, vault_plausible_totp_key } from "../../../../lib/vaultvars.ts";
import { type Vars } from "../../../../roles/icos.plausible/_ctx.ts";

export default {
  "plausible_home": "/opt/plausible",
  "plausible_port": 8701,
  "plausible_domain": "plausible.fieldsites.se",
  "plausible_postgres_password": vault_plausible_postgres_password,
  "plausible_secret": vault_plausible_secret,
  "plausible_google_client_id": vault_plausible_google_client_id,
  "plausible_google_client_secret": vault_plausible_google_client_secret,
  "plausible_mailer_email": vault_plausible_mailer_email,
  "plausible_backup_enabled": false,
  "plausible_totp_key": vault_plausible_totp_key
} satisfies Vars;
