virtuoso_home: "{{ docker_compose_home | default('/docker') }}/virtuoso"

virtuoso_bind_host: 127.0.0.1
virtuoso_http_port: 8890
virtuoso_isql_port: 1111

virtuoso_host: "{{ virtuoso_bind_host }}"
virtuoso_port: "{{ virtuoso_http_port }}"

virtuoso_image: openlink/virtuoso-opensource-7:7.2

virtuoso_dba_pass: "{{ vault_virtuoso_dba_pass }}"

virtuoso_number_of_buffers: 340000
virtuoso_max_dirty_buffers: 250000
virtuoso_max_client_connections: 10
virtuoso_result_set_max_rows: 1000000
