// Auto-generated by gen-data.ts from ../devops/roles/icos.server/meta/main.yml
import type { Meta } from "../../../../lib/data.ts";

export default {
  "dependencies": [
    {
      "role": "icos.just",
      "tags": "just",
    },
    {
      "role": "icos.uv",
      "tags": "uv",
    },
    {
      "role": "icos.utils",
      "tags": "utils",
    },
    {
      "role": "icos.sysstat",
      "tags": "sysstat",
    },
    {
      "role": "icos.iptables",
      "tags": "iptables",
    },
    {
      "role": "icos.mosh",
      "tags": "mosh",
    },
    {
      "role": "icos.fail2ban",
      "tags": "fail2ban",
    },
  ],
} satisfies Meta;
