// Auto-generated by gen-data.ts from ../devops/roles/icos.podman/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "podman_version": "4.3.1",
  "podman_src_dir": "/tmp/podman_v{{ podman_version }}_src",
  "conmon_min_version": "2.0.24",
  "golang_min_version": 1.16,
  "podman_docker": false,
} satisfies VarsFile;
