// Auto-generated by gen-data.ts from ../devops/production.inventory/borgbackup.yml
import { inventory_hostname_short } from "../../lib/builtins.ts";
import { type Inventory } from "../../lib/data.ts";
import { iptables_ssh_port } from "../../lib/sharedvars.ts";
import { tmpl } from "../../lib/template.ts";

export default {
  "bbservers": {
    "vars": {
      "bbserver_host": tmpl`${inventory_hostname_short}.nebula`,
      "bbserver_user": "bbserver",
      "bbserver_port": iptables_ssh_port
    },
    "hosts": {
      "icos1": {
        "bbserver_home": "/pool/bbserver"
      },
      "cdb": {
        "bbserver_home": "/disk/data/bbserver"
      },
      "fsicos2": {
        "bbserver_home": "/disk/data/bbserver"
      }
    }
  }
} satisfies Inventory;
