// Auto-generated by gen-data.ts from ../devops/production.inventory/core.yml
import { type Inventory } from "../../lib/data.ts";
import { cpauth_cities_domain, cpauth_icos_domain, cpauth_sites_domain, cpdata_icos_domain, cpdata_sites_domain, cpmeta_icos_domain, cpmeta_sites_domain, fsicos2_ip, postgis_icos_db_name, postgis_sites_db_name, restheart_cities_db_name, restheart_cities_domain, restheart_icos_db_name, restheart_sites_db_name } from "../../lib/globals.ts";
import { restheart_bind_port } from "../../lib/sharedvars.ts";
import { tmpl } from "../../lib/template.ts";
import { city_restheart_basic_auth } from "../../lib/vaultvars.ts";

export default {
  "all": {
    "vars": {
      "cpauth_icos_domain": "cpauth.icos-cp.eu",
      "cpauth_sites_domain": "auth.fieldsites.se",
      "cpauth_cities_domain": "cityauth.icos-cp.eu",
      "cpmeta_icos_domain": "meta.icos-cp.eu",
      "cpmeta_sites_domain": "meta.fieldsites.se",
      "cpdata_icos_domain": "data.icos-cp.eu",
      "cpdata_sites_domain": "data.fieldsites.se",
      "cpauth_domains": [
        cpauth_icos_domain,
        cpauth_sites_domain,
        cpauth_cities_domain
      ],
      "cpmeta_domains": [
        cpmeta_icos_domain,
        cpmeta_sites_domain
      ],
      "cpdata_domains": [
        cpdata_icos_domain,
        cpdata_sites_domain
      ],
      "doi_domains": [
        "doi.icos-cp.eu"
      ],
      "stiltweb_domains": [
        "stilt.icos-cp.eu"
      ],
      "cpmeta_bbclient_name": "cpmeta",
      "restheart_bbclient_name": "restheart",
      "postgis_bbclient_name": "postgis",
      "rdflog_bbclient_name": "rdflog",
      "showUnderConstruction": "false",
      "showCarbonBadge": "true"
    },
    "children": {
      "core_host": {
        "hosts": {
          "fsicos2": null
        },
        "vars": {
          "coreapp_bind_addr": "127.0.0.1",
          "cpmeta_filestorage_target": "/disk/data/metaAppStorage",
          "cpmeta_backup_enable": true,
          "cpmeta_config_files": [
            "application_production.conf",
            "application_production_sensitive.conf"
          ],
          "rdflog_backup_enable": true,
          "rdflog_postgres_version": 10,
          "cpdata_filestorage_target": "/disk/data/dataAppStorage",
          "cpdata_config_files": [
            "application_production.conf"
          ],
          "cpauth_config_files": [
            "application_production.conf"
          ],
          "postgis_db_port": 5438,
          "postgis_hostname": "127.0.0.1",
          "postgis_backup_enable": true,
          "stiltweb_statedir": "/disk/data/stiltweb",
          "stiltweb_stiltdir": "/disk/data/stilt",
          "cpauth_envries": [
            {
              "name": "ICOS",
              "restheart_url": tmpl`http://127.0.0.1:${restheart_bind_port}/${restheart_icos_db_name}`
            },
            {
              "name": "SITES",
              "restheart_url": tmpl`http://127.0.0.1:${restheart_bind_port}/${restheart_sites_db_name}`
            },
            {
              "name": "ICOSCities",
              "restheart_url": tmpl`https://${restheart_cities_domain}/${restheart_cities_db_name}`,
              "restheart_username": city_restheart_basic_auth.username,
              "restheart_password": city_restheart_basic_auth.password
            }
          ],
          "data_envries": [
            {
              "name": "ICOS",
              "restheart_url": tmpl`http://127.0.0.1:${restheart_bind_port}/${restheart_icos_db_name}`,
              "postgis_db_name": postgis_icos_db_name
            },
            {
              "name": "SITES",
              "restheart_url": tmpl`http://127.0.0.1:${restheart_bind_port}/${restheart_sites_db_name}`,
              "postgis_db_name": postgis_sites_db_name
            }
          ]
        }
      },
      "core_server": {
        "hosts": {
          "fsicos2": null
        },
        "vars": {
          "coreapp_httpproxy_host": "127.0.0.1",
          "coreapp_host_ip": fsicos2_ip,
          "cpmeta_certbot_name": "meta.icos-cp.eu",
          "cpmeta_nginxsite_name": "cpmeta",
          "cpdata_certbot_name": "data.icos-cp.eu",
          "cpdata_nginxsite_name": "cpdata",
          "cpauth_certbot_name": "cpauth.icos-cp.eu",
          "cpauth_nginxsite_name": "cpauth",
          "restheart_nginxsite_name": "restheart",
          "restheart_certbot_name": "restheart.icos-cp.eu",
          "restheart_domains": [
            "restheart.icos-cp.eu"
          ],
          "restheart_dbs": [
            restheart_icos_db_name,
            restheart_sites_db_name
          ],
          "doi_certbot_name": "doi.icos-cp.eu",
          "doi_nginxsite_name": "doi"
        }
      }
    }
  }
} satisfies Inventory;
