// Auto-generated by gen-data.ts from ../devops/production.inventory/core.yml
import type { Inventory } from "../../lib/data.ts";
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { VarShapes } from "../../lib/shapes.ts";

const { V, tmpl } = context<Globals & AllVars & VarShapes>();

export default {
  "all": {
    "vars": {
      "cpauth_icos_domain": "cpauth.icos-cp.eu",
      "cpauth_sites_domain": "auth.fieldsites.se",
      "cpauth_cities_domain": "cityauth.icos-cp.eu",
      "cpmeta_icos_domain": "meta.icos-cp.eu",
      "cpmeta_sites_domain": "meta.fieldsites.se",
      "cpdata_icos_domain": "data.icos-cp.eu",
      "cpdata_sites_domain": "data.fieldsites.se",
      "cpauth_domains": [
        V.cpauth_icos_domain,
        V.cpauth_sites_domain,
        V.cpauth_cities_domain,
      ],
      "cpmeta_domains": [
        V.cpmeta_icos_domain,
        V.cpmeta_sites_domain,
      ],
      "cpdata_domains": [
        V.cpdata_icos_domain,
        V.cpdata_sites_domain,
      ],
      "doi_domains": [
        "doi.icos-cp.eu",
      ],
      "stiltweb_domains": [
        "stilt.icos-cp.eu",
      ],
      "cpmeta_bbclient_name": "cpmeta",
      "restheart_bbclient_name": "restheart",
      "postgis_bbclient_name": "postgis",
      "rdflog_bbclient_name": "rdflog",
      "showUnderConstruction": "false",
      "showCarbonBadge": "true",
    },
    "children": {
      "core_host": {
        "hosts": {
          "fsicos2": null,
        },
        "vars": {
          "coreapp_bind_addr": "127.0.0.1",
          "cpmeta_filestorage_target": "/disk/data/metaAppStorage",
          "cpmeta_backup_enable": true,
          "cpmeta_config_files": [
            "application_production.conf",
            "application_production_sensitive.conf",
          ],
          "rdflog_backup_enable": true,
          "rdflog_postgres_version": 10,
          "cpdata_filestorage_target": "/disk/data/dataAppStorage",
          "cpdata_config_files": [
            "application_production.conf",
          ],
          "cpauth_config_files": [
            "application_production.conf",
          ],
          "postgis_db_port": 5438,
          "postgis_hostname": "127.0.0.1",
          "postgis_backup_enable": true,
          "stiltweb_statedir": "/disk/data/stiltweb",
          "stiltweb_stiltdir": "/disk/data/stilt",
          "cpauth_envries": [
            {
              "name": "ICOS",
              "restheart_url":
                tmpl`http://127.0.0.1:${V.restheart_bind_port}/${V.restheart_icos_db_name}`,
            },
            {
              "name": "SITES",
              "restheart_url":
                tmpl`http://127.0.0.1:${V.restheart_bind_port}/${V.restheart_sites_db_name}`,
            },
            {
              "name": "ICOSCities",
              "restheart_url":
                tmpl`https://${V.restheart_cities_domain}/${V.restheart_cities_db_name}`,
              "restheart_username": V.city_restheart_basic_auth.username,
              "restheart_password": V.city_restheart_basic_auth.password,
            },
          ],
          "data_envries": [
            {
              "name": "ICOS",
              "restheart_url":
                tmpl`http://127.0.0.1:${V.restheart_bind_port}/${V.restheart_icos_db_name}`,
              "postgis_db_name": V.postgis_icos_db_name,
            },
            {
              "name": "SITES",
              "restheart_url":
                tmpl`http://127.0.0.1:${V.restheart_bind_port}/${V.restheart_sites_db_name}`,
              "postgis_db_name": V.postgis_sites_db_name,
            },
          ],
        },
      },
      "core_server": {
        "hosts": {
          "fsicos2": null,
        },
        "vars": {
          "coreapp_httpproxy_host": "127.0.0.1",
          "coreapp_host_ip": V.fsicos2_ip,
          "cpmeta_certbot_name": "meta.icos-cp.eu",
          "cpmeta_nginxsite_name": "cpmeta",
          "cpdata_certbot_name": "data.icos-cp.eu",
          "cpdata_nginxsite_name": "cpdata",
          "cpauth_certbot_name": "cpauth.icos-cp.eu",
          "cpauth_nginxsite_name": "cpauth",
          "restheart_nginxsite_name": "restheart",
          "restheart_certbot_name": "restheart.icos-cp.eu",
          "restheart_domains": [
            "restheart.icos-cp.eu",
          ],
          "restheart_dbs": [
            V.restheart_icos_db_name,
            V.restheart_sites_db_name,
          ],
          "doi_certbot_name": "doi.icos-cp.eu",
          "doi_nginxsite_name": "doi",
        },
      },
    },
  },
} satisfies Inventory;
