// Auto-generated by gen-data.ts from ../devops/production.inventory/hosts.yml
import type { Inventory } from "../../lib/data.ts";
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

type Self = Record<never, never>;
const { V, expr } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "all": {
    "vars": {
      "nginx_testing_users": expr("vault_nginx_testing_users"),
      "root_keys": expr("vault_root_keys"),
      "lxd_guest_root_keys": V.root_keys,
      "lxd_vm_root_keys": V.root_keys,
      "ansible_user": "root",
      "quince_ext_port": 60522,
      "icos1_ip": "130.235.74.215",
      "fsicos1_ip": "194.47.223.133",
      "fsicos2_ip": "194.47.223.139",
      "fsicos3_ip": "194.47.223.137",
      "fsicos4_ip": "130.235.98.147",
      "cdb_ip": "130.235.99.237",
      "rdflog_db_pass": expr("vault_rdflog_db_pass"),
      "registry_domain": "registry.icos-cp.eu",
    },
    "hosts": {
      "fsicos4": {
        "external_ip": "130.235.98.147",
      },
    },
    "children": {
      "staging_server": {
        "hosts": {
          "fsicos2": null,
        },
      },
      "postgis_server": {
        "hosts": {
          "fsicos2": null,
        },
      },
      "physical_servers": {
        "vars": {
          "iptables_forward": true,
        },
        "hosts": {
          "fsicos4": {
            "firewall_enabled": false,
          },
          "cdb": {
            "root_keys": expr("vault_cdb_root_keys"),
          },
          "icos1": {
            "ansible_port": 60022,
          },
          "fsicos2": {
            "root_keys": expr("vault_fsicos2_root_keys"),
            "ansible_port": 60022,
          },
          "fsicos3": null,
        },
      },
      "fsicos4_vms": {
        "vars": {
          "ansible_user": "debian",
          "ansible_become": true,
          "ansible_host": "fsicos4",
          "root_keys": expr("vault_fsicos4_vms_root_keys"),
        },
        "hosts": {
          "cupcake": {
            "ansible_port": 60603,
            "user_conf": expr("vault_cupcake_user_conf"),
          },
          "pancake": {
            "ansible_port": 60605,
            "ansible_user": "root",
            "user_conf": expr("vault_pancake_user_conf"),
          },
          "fsicos4-stiltcluster": {
            "ansible_port": 60601,
          },
          "fdp": {
            "ansible_port": 60606,
            "ansible_user": "fdp",
          },
          "test-fs4": {
            "ansible_port": 60608,
          },
        },
      },
      "cdb_vms": {
        "vars": {
          "ansible_host": "cdb",
        },
        "hosts": {
          "pgrep2": {
            "ansible_port": 60550,
          },
        },
      },
      "fsicos2_vms": {
        "vars": {
          "ansible_host": "fsicos2",
        },
        "hosts": {
          "build": {
            "ansible_port": 60525,
          },
          "staging": {
            "ansible_port": 60520,
          },
          "erddap": {
            "ansible_port": 60580,
            "root_keys": expr("vault_erddap_root_keys"),
          },
          "flexextract": {
            "ansible_port": 60526,
            "user_conf": expr("vault_flexextract_user_conf"),
          },
          "postgis": {
            "ansible_port": 60590,
            "user_conf": expr("vault_postgis_user_conf"),
          },
          "quince3": {
            "ansible_port": 60600,
            "quince_jdk_version": 17,
            "user_conf": expr("vault_quince3_user_conf"),
          },
          "rspamd": {
            "ansible_port": 60585,
          },
          "wordpress": {
            "ansible_port": 60552,
          },
          "cities": {
            "ansible_port": 60565,
          },
        },
      },
      "fsicos3_vms": {
        "vars": {
          "ansible_host": "fsicos3",
        },
        "hosts": {
          "amalthea": {
            "ansible_port": 60560,
          },
          "callisto": {
            "ansible_port": 60510,
            "docker_prevent_upgrade": true,
          },
          "exploredata": {
            "ansible_port": 60555,
            "docker_prevent_upgrade": true,
            "root_keys": expr("vault_exploredata_root_keys"),
          },
          "flexpart": {
            "ansible_port": 60530,
            "docker_prevent_upgrade": true,
          },
          "ganymede": {
            "ansible_port": 60540,
            "docker_prevent_upgrade": true,
            "python3_version_list": [
              "3.10",
              "3.11",
            ],
          },
          "jupyter": {
            "root_keys": expr("vault_jupyter_root_keys"),
            "ansible_port": 60535,
            "docker_prevent_upgrade": true,
            "bbclient_name": "jupyter",
            "jupyter_backup_enable": true,
            "python3_version_list": [
              "3.10",
              "3.11",
            ],
          },
          "molefractions": {
            "ansible_port": 60515,
          },
          "registry": {
            "ansible_port": 60545,
          },
          "pgrep1": {
            "ansible_port": 60570,
          },
          "ctehires": {
            "ansible_port": 60575,
          },
          "dokku": {
            "root_keys": expr("vault_dokku_root_keys"),
            "ansible_port": 60595,
          },
        },
      },
    },
  },
} satisfies Inventory;
