// Auto-generated by gen-data.ts from ../devops/production.inventory/nebula.yml
import { hostvars } from "../../lib/builtins.ts";
import { type Inventory } from "../../lib/data.ts";
import { nebula_interface } from "../../lib/globals.ts";
import { jinja, tmpl } from "../../lib/template.ts";

export default {
  "nebula_hosts": {
    "vars": {
      "nebula_interfaces": {
        "interfaces": {
          "wg-*": false
        }
      },
      "nebula_host": "0.0.0.0",
      "nebula_ssh_enable": true,
      "nebula_cert_sign": "files/nebula/ca.crt",
      "nebula_cert_copy": "files/nebula/combined.crt",
      "nebula_config_file": "files/nebula/config.yml.j2",
      "nebula_ping_host": tmpl`fsicos4.${nebula_interface}`,
      "nebula_interface": "nebula",
      "nebula_port": 60422,
      "nebula_netmask": "/22",
      "nebula_static_host_map": {
        "100.100.4.1": [
          "fsicos4.icos-cp.eu:60422"
        ],
        "100.100.4.2": [
          "fsicos3.icos-cp.eu:60422"
        ],
        "100.100.4.4": [
          "fsicos2.icos-cp.eu:60422"
        ],
        "100.100.4.5": [
          "icos1.icos-cp.eu:60422"
        ],
        "100.100.4.7": [
          "cdb.nateko.lu.se:60422"
        ]
      },
      "nebula_hosts_block": tmpl`${jinja`{% for host in query('hosts', 'nebula_hosts',
                     var='nebula_ip', how='version') %}`}
${jinja`{{ ${hostvars}[host]['nebula_ip'] }}`}	${jinja`{{ ${hostvars}[host]['inventory_hostname_short'] }}`}.nebula
${jinja`{% endfor %}`}
`
    },
    "hosts": {
      "icos1": {
        "ansible_python_interpreter": "/usr/bin/python3",
        "nebula_ip": "100.100.4.5",
        "nebula_is_lighthouse": true
      },
      "fsicos2": {
        "nebula_ip": "100.100.4.4",
        "nebula_is_lighthouse": true
      },
      "fsicos3": {
        "nebula_ip": "100.100.4.2",
        "nebula_is_lighthouse": true
      },
      "fsicos4": {
        "nebula_ip": "100.100.4.1",
        "nebula_is_lighthouse": true,
        "nebula_fw_enable": false
      },
      "cdb": {
        "nebula_ip": "100.100.4.7",
        "nebula_is_lighthouse": true,
        "nebula_fw_enable": true
      },
      "cupcake": {
        "nebula_ip": "100.100.4.3",
        "nebula_port": 60703
      },
      "fsicos4-stiltcluster": {
        "nebula_ip": "100.100.4.8",
        "nebula_port": 60705
      },
      "pancake": {
        "nebula_ip": "100.100.4.9",
        "nebula_port": 60706
      }
    }
  }
} satisfies Inventory;
