// Auto-generated by gen-data.ts from ../devops/production.inventory/rdflog.yml
import type { Inventory } from "../../lib/data.ts";
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { ParamVars } from "../../lib/paramvars.ts";
import type { VaultVars } from "../../lib/vaultvars.ts";
import type { VarShapes } from "../../lib/shapes.ts";

type Self = Record<never, never>;
const { V } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "all": {
    "vars": {
      "rdflog_ext_port": 60002,
    },
  },
  "rdflog_server": {
    "hosts": {
      "fsicos2": null,
    },
  },
  "pgrep_rdflog_server": {
    "hosts": {
      "fsicos3": {
        "rdflog_vm_name": "pgrep1",
      },
      "cdb": {
        "rdflog_vm_name": "pgrep2",
      },
    },
  },
  "pgrep_rdflog": {
    "vars": {
      "pgrep_name": "rdflog",
      "pgrep_peer_user": "pgrepuser",
      "pgrep_peer_host": "fsicos2",
      "pgrep_peer_port": V.rdflog_ext_port,
      "pgrep_peer_pass": V.vault_rdflog_rep_pass,
      "pgrep_peer_cert": "roles/icos.rdflog/files/server.crt",
    },
    "hosts": {
      "pgrep2": {
        "pgrep_peer_slot": "cdb",
      },
      "pgrep1": {
        "pgrep_peer_slot": "fsicos3",
      },
    },
  },
} satisfies Inventory;
