// Auto-generated by gen-data.ts from ../devops/production.inventory/rdflog.yml
import type { Inventory } from "../../lib/data.ts";
import { tmpl } from "../../lib/ansible.ts";

export default {
  "all": {
    "vars": {
      "rdflog_ext_port": 60002,
    },
  },
  "rdflog_server": {
    "hosts": {
      "fsicos2": null,
    },
  },
  "pgrep_rdflog_server": {
    "hosts": {
      "fsicos3": {
        "rdflog_vm_name": "pgrep1",
      },
      "cdb": {
        "rdflog_vm_name": "pgrep2",
      },
    },
  },
  "pgrep_rdflog": {
    "vars": {
      "pgrep_name": "rdflog",
      "pgrep_peer_user": "pgrepuser",
      "pgrep_peer_host": "fsicos2",
      "pgrep_peer_port": tmpl("{{ rdflog_ext_port }}"),
      "pgrep_peer_pass": tmpl("{{ vault_rdflog_rep_pass }}"),
      "pgrep_peer_cert": "roles/icos.rdflog/files/server.crt",
    },
    "hosts": {
      "pgrep2": {
        "pgrep_peer_slot": "cdb",
      },
      "pgrep1": {
        "pgrep_peer_slot": "fsicos3",
      },
    },
  },
} satisfies Inventory;
