// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.golang/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  golang_apt_version_ok: string;
  golang_bin_dir: string;
  golang_local_version_ok: string;
  golang_min_version: string;
  golang_opt_dir: string;
  golang_url: string;
  golang_version_install: string;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
