// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.golang/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  golang_apt_version_ok: Tmpl;
  golang_bin_dir: Tmpl;
  golang_local_version_ok: Tmpl;
  golang_min_version: Tmpl;
  golang_opt_dir: Tmpl;
  golang_url: Tmpl;
  golang_version_install: string;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
