// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.golang/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  golang_apt_version_ok: unknown;
  golang_bin_dir: unknown;
  golang_local_version_ok: unknown;
  golang_min_version: unknown;
  golang_opt_dir: unknown;
  golang_url: unknown;
  golang_version_install: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & BuiltinVars
>();
