// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.timer2/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  _timer_sysd_service: Tmpl;
  _timer_sysd_timer: Tmpl;
  timer_dest: Tmpl;
  timer_home: string;
  timer_state: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const _timer_sysd_service = vref("_timer_sysd_service");
export const _timer_sysd_timer = vref("_timer_sysd_timer");
export const timer_dest = vref("timer_dest");
export const timer_home = vref("timer_home");
export const timer_state = vref("timer_state");
