// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.timer2/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  _timer_sysd_service: Tmpl;
  _timer_sysd_timer: Tmpl;
  timer_dest: Tmpl;
  timer_home: string;
  timer_state: string;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
