// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.timer2/{defaults,vars}/*.yml
// Per-role variable context: 5 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  _timer_sysd_service: string;
  _timer_sysd_timer: string;
  timer_dest: string;
  timer_home: string;
  timer_state: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
