// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.wireguard/{defaults,vars}/*.yml
// Per-role variable context: 3 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  _wg_is_installed: boolean;
  wireguard_reresolve_script: string;
  wireguard_update: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
