// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.rdflog/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, widened with
// only the registries this role's task/handler files reference.
import type { Tmpl } from "../../lib/template.ts";
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  rdflog_db_name: string;
  rdflog_db_port: number;
  rdflog_db_user: string;
  rdflog_home: string;
  rdflog_rep_pass: Tmpl;
  rdflog_rep_user: string;
}

export const { V, tmpl } = context<
  Vars & Globals & BuiltinVars & ParamVars
>();
