// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.rdflog/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  rdflog_db_name: string;
  rdflog_db_port: number;
  rdflog_db_user: string;
  rdflog_home: string;
  rdflog_rep_pass: Tmpl;
  rdflog_rep_user: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const rdflog_db_name = vref("rdflog_db_name");
export const rdflog_db_port = vref("rdflog_db_port");
export const rdflog_db_user = vref("rdflog_db_user");
export const rdflog_home = vref("rdflog_home");
export const rdflog_rep_pass = vref("rdflog_rep_pass");
export const rdflog_rep_user = vref("rdflog_rep_user");
