// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.rdflog/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  rdflog_db_name: unknown;
  rdflog_db_port: unknown;
  rdflog_db_user: unknown;
  rdflog_home: unknown;
  rdflog_rep_pass: unknown;
  rdflog_rep_user: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & ParamVars
>();
