// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.onlyoffice/{defaults,vars}/*.yml
// Per-role variable context: 5 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  onlyoffice_build_dir: string;
  onlyoffice_domain: string;
  onlyoffice_home: string;
  onlyoffice_port: number;
  onlyoffice_version: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
