// Auto-generated by gen-data.ts from ../devops/roles/icos.maps/defaults/main.yml
import type { Vars } from "../../../../roles/icos.maps/_ctx.ts";
import { context } from "../../../../lib/context.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";

const { V } = context<VaultVars>();

export default {
  "maps_domains": [
    "maps.icos-cp.eu",
    "maps.fieldsites.se",
  ],
  "maps_lantmateriet_loc": "lm",
  "maps_lantmateriet_url": "https://maps.lantmateriet.se/",
  "maps_lantmateriet_auth": V.vault_maps_lantmateriet_auth,
} satisfies Vars;
