// Auto-generated by gen-data.ts from ../devops/roles/icos.maps/defaults/main.yml
import { vault_maps_lantmateriet_auth } from "../../../../lib/vaultvars.ts";
import { type Vars } from "../../../../roles/icos.maps/_ctx.ts";

export default {
  "maps_domains": [
    "maps.icos-cp.eu",
    "maps.fieldsites.se",
  ],
  "maps_lantmateriet_loc": "lm",
  "maps_lantmateriet_url": "https://maps.lantmateriet.se/",
  "maps_lantmateriet_auth": vault_maps_lantmateriet_auth,
} satisfies Vars;
