// Auto-generated by gen-data.ts from ../devops/roles/icos.maps/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr } from "../../../../lib/ansible.ts";

export default {
  "maps_domains": [
    "maps.icos-cp.eu",
    "maps.fieldsites.se",
  ],
  "maps_lantmateriet_loc": "lm",
  "maps_lantmateriet_url": "https://maps.lantmateriet.se/",
  "maps_lantmateriet_auth": expr("vault_maps_lantmateriet_auth"),
} satisfies VarsFile;
