// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nfs4/{defaults,vars}/*.yml
// Per-role variable context: 2 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  nfs4_host: null;
  nfs4_interface: null;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const nfs4_host = vref("nfs4_host");
export const nfs4_interface = vref("nfs4_interface");
