// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nfs4/{defaults,vars}/*.yml
// Per-role variable context: 2 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  nfs4_host: unknown;
  nfs4_interface: unknown;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
