// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nfs4/{defaults,vars}/*.yml
// Per-role variable context: 2 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  nfs4_host: unknown;
  nfs4_interface: unknown;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
