// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.lxd_guest/{defaults,vars}/*.yml
// Per-role variable context: 0 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

// deno-lint-ignore no-empty-interface
export interface Vars {}

export const { V, tmpl } = context<
  Globals & BuiltinVars
>();
