// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.lxd_guest/{defaults,vars}/*.yml
// Per-role variable context: 1 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  lxd_guest_root_keys: unknown;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
