- name: Copy ops-nfs
  template:
    src: ops-nfs
    dest: /usr/local/bin/
    mode: +x
    variable_start_string: "{{ '{{{' }}"
    variable_end_string: "{{ '}}}' }}"
    lstrip_blocks: yes
  register: _justfile

- name: Check that the justfile is executable
  shell: "{{ _justfile.dest }}"
  changed_when: no
