# https://hub.docker.com/_/nextcloud/
nextcloud_nextcloud_version: 29.0.11

# https://hub.docker.com/_/postgres/
nextcloud_postgres_version: 13.18

nextcloud_port: 9000

nextcloud_user: nextcloud
nextcloud_home: /docker/nextcloud
nextcloud_domain: fileshare.icos-cp.eu

nextcloud_certbot_enable: true
certbot_domains: ["{{ nextcloud_domain }}"]
certbot_name: nextcloud

nextcloud_volume_nextcloud: "{{ nextcloud_home }}/volumes/nextcloud"
nextcloud_volume_postgres: "{{ nextcloud_home }}/volumes/postgres"

nextcloud_db_name: nextcloud
nextcloud_db_user: nextcloud
nextcloud_db_host: db

# Config file for prometheus exporter
# (https://github.com/xperimental/nextcloud-exporter).
nextcloud_exporter_conf_host: "{{ nextcloud_home }}/nextcloud-exporter.conf"
# The exporter will login to nextcloud using this username.
nextcloud_exporter_user: nextcloud-exporter

# The external port that'll forward traffic to/from the exporter container.
nextcloud_exporter_port: 9205

nextcloud_volumes: []
