// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.bbserver/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  bbserver_home: string;
  bbserver_monitor_home: Tmpl;
  bbserver_repo_home: Tmpl;
  bbserver_textfiles: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const bbserver_home = vref("bbserver_home");
export const bbserver_monitor_home = vref("bbserver_monitor_home");
export const bbserver_repo_home = vref("bbserver_repo_home");
export const bbserver_textfiles = vref("bbserver_textfiles");
