// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.bbserver/{defaults,vars}/*.yml
// Per-role variable context: 5 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  bbserver_home: string;
  bbserver_monitor_home: string;
  bbserver_repo_home: string;
  bbserver_textfiles: string;
  bbserver_user: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
