// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.matomo/{defaults,vars}/*.yml
// Per-role variable context: 9 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  matomo_backup_enable: boolean;
  matomo_domain: string;
  matomo_home: string;
  matomo_mysql_database_password: Tmpl;
  matomo_mysql_database_user: Tmpl;
  matomo_mysql_password: Tmpl;
  matomo_mysql_root_password: Tmpl;
  matomo_mysql_user: Tmpl;
  matomo_port: number;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const matomo_backup_enable = vref("matomo_backup_enable");
export const matomo_domain = vref("matomo_domain");
export const matomo_home = vref("matomo_home");
export const matomo_mysql_database_password = vref(
  "matomo_mysql_database_password",
);
export const matomo_mysql_database_user = vref("matomo_mysql_database_user");
export const matomo_mysql_password = vref("matomo_mysql_password");
export const matomo_mysql_root_password = vref("matomo_mysql_root_password");
export const matomo_mysql_user = vref("matomo_mysql_user");
export const matomo_port = vref("matomo_port");
