// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.matomo/{defaults,vars}/*.yml
// Per-role variable context: 9 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  matomo_backup_enable: boolean;
  matomo_domain: string;
  matomo_home: string;
  matomo_mysql_database_password: Tmpl;
  matomo_mysql_database_user: Tmpl;
  matomo_mysql_password: Tmpl;
  matomo_mysql_root_password: Tmpl;
  matomo_mysql_user: Tmpl;
  matomo_port: number;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } = new Proxy(
  {},
  { get: (_t, name: string) => varProxy(name) },
) as { readonly [K in keyof Vars]: VarRef<Vars[K]> };
