// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.stiltrun/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";

export interface Vars {
  stiltrun_image_id: unknown;
  stiltrun_image_name: unknown;
  stiltrun_image_url: unknown;
  stiltrun_input_dir: unknown;
  stiltrun_user: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars
>();
