// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.stiltrun/{defaults,vars}/*.yml
// Per-role variable context: 5 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, type VarRef, varProxy } from "../../lib/template.ts";

export interface Vars {
  stiltrun_image_id: string;
  stiltrun_image_name: string;
  stiltrun_image_url: Tmpl;
  stiltrun_input_dir: Tmpl;
  stiltrun_user: string;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } =
  new Proxy({}, { get: (_t, name: string) => varProxy(name) }) as
    { readonly [K in keyof Vars]: VarRef<Vars[K]> };
