// Auto-generated by gen-data.ts from ../devops/roles/icos.nexus/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  nexus_home: unknown;
  nexus_host_port: unknown;
  nexus_domains: unknown;
  nexus_version: unknown;
  certbot_name: unknown;
  certbot_domains: unknown;
  nginxsite_name: unknown;
  nginxsite_file: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "nexus_home": tmpl`${V.docker_compose_home.default("/docker")}/nexus`,
  "nexus_host_port": 8881,
  "nexus_domains": [
    "repo.icos-cp.eu",
  ],
  "nexus_version": "2.15.2",
  "certbot_name": "nexus",
  "certbot_domains": V.nexus_domains,
  "nginxsite_name": "nexus",
  "nginxsite_file": "nexus-nginx.conf",
} satisfies VarsFile;
