// Auto-generated by gen-data.ts from ../devops/roles/icos.stiltweb/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";

interface Self {
  stiltweb_username: unknown;
  stiltweb_home: unknown;
  stiltweb_bindir: unknown;
  stiltweb_akka_port: unknown;
  stiltweb_akka_hostname: unknown;
  stiltweb_java: unknown;
  stiltweb_jre_package: unknown;
  stiltweb_certbot_name: unknown;
  stiltweb_nginxsite_name: unknown;
}
const { V, tmpl } = context<Self & BuiltinVars>();

export default {
  "stiltweb_username": "stiltweb",
  "stiltweb_home": tmpl`/home/${V.stiltweb_username}`,
  "stiltweb_bindir": tmpl`${V.stiltweb_home}/bin`,
  "stiltweb_akka_port": 2550,
  "stiltweb_akka_hostname": V.inventory_hostname,
  "stiltweb_java": "/usr/bin/java",
  "stiltweb_jre_package": "openjdk-11-jre-headless",
  "stiltweb_certbot_name": "stiltweb",
  "stiltweb_nginxsite_name": "stiltweb",
} satisfies VarsFile;
