// Auto-generated by gen-data.ts from ../devops/roles/icos.stiltweb/defaults/main.yml
import { inventory_hostname } from "../../../../lib/builtins.ts";
import { tmpl } from "../../../../lib/template.ts";
import { V, type Vars } from "../../../../roles/icos.stiltweb/_ctx.ts";

export default {
  "stiltweb_username": "stiltweb",
  "stiltweb_home": tmpl`/home/${V.stiltweb_username}`,
  "stiltweb_bindir": tmpl`${V.stiltweb_home}/bin`,
  "stiltweb_akka_port": 2550,
  "stiltweb_akka_hostname": inventory_hostname,
  "stiltweb_java": "/usr/bin/java",
  "stiltweb_jre_package": "openjdk-11-jre-headless",
  "stiltweb_certbot_name": "stiltweb",
  "stiltweb_nginxsite_name": "stiltweb"
} satisfies Vars;
