// Auto-generated by gen-data.ts from ../devops/roles/icos.stiltweb/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "stiltweb_username": "stiltweb",
  "stiltweb_home": tmpl`/home/${expr("stiltweb_username")}`,
  "stiltweb_bindir": tmpl`${expr("stiltweb_home")}/bin`,
  "stiltweb_akka_port": 2550,
  "stiltweb_akka_hostname": expr("inventory_hostname"),
  "stiltweb_java": "/usr/bin/java",
  "stiltweb_jre_package": "openjdk-11-jre-headless",
  "stiltweb_certbot_name": "stiltweb",
  "stiltweb_nginxsite_name": "stiltweb",
} satisfies VarsFile;
