// Auto-generated by gen-data.ts from ../devops/roles/icos.restheart/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  restheart_user: unknown;
  restheart_home: unknown;
  restheart_bind_port: unknown;
  restheart_port: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "restheart_user": "restheart",
  "restheart_home": tmpl`${V.docker_compose_home.default("/docker")}/restheart`,
  "restheart_bind_host": "127.0.0.1",
  "restheart_bind_port": 8088,
  "restheart_host": V.restheart_bind_host,
  "restheart_port": V.restheart_bind_port,
  "restheart_nginxsite_name": "restheart",
} satisfies VarsFile;
