// Auto-generated by gen-data.ts from ../devops/roles/icos.restheart/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "restheart_user": "restheart",
  "restheart_home": "{{ docker_compose_home | default('/docker') }}/restheart",
  "restheart_bind_host": "127.0.0.1",
  "restheart_bind_port": 8088,
  "restheart_host": "{{ restheart_bind_host }}",
  "restheart_port": "{{ restheart_bind_port }}",
  "restheart_nginxsite_name": "restheart",
} satisfies VarsFile;
