// Auto-generated by gen-data.ts from ../devops/test-fs4.inventory/group_vars/core_host/vars.yml
import { type Inventory } from "../../../../lib/data.ts";
import { vault_doi_admins, vault_postgis_admin_pass, vault_postgis_reader_pass, vault_postgis_writer_pass, vault_rdflog_db_pass, vault_virtuoso_dba_pass } from "../../../../lib/vaultvars.ts";

export default {
  "virtuoso_enable": true,
  "postgis_admin_pass": vault_postgis_admin_pass,
  "postgis_writer_pass": vault_postgis_writer_pass,
  "postgis_reader_pass": vault_postgis_reader_pass,
  "rdflog_db_pass": vault_rdflog_db_pass,
  "virtuoso_dba_pass": vault_virtuoso_dba_pass,
  "doi_admins": vault_doi_admins
} satisfies Inventory;
