// Auto-generated by gen-data.ts from ../devops/test-fs4.inventory/group_vars/core_host/vars.yml
import type { Inventory } from "../../../../lib/data.ts";
import { expr } from "../../../../lib/ansible.ts";

export default {
  "virtuoso_enable": true,
  "postgis_admin_pass": expr("vault_postgis_admin_pass"),
  "postgis_writer_pass": expr("vault_postgis_writer_pass"),
  "postgis_reader_pass": expr("vault_postgis_reader_pass"),
  "rdflog_db_pass": expr("vault_rdflog_db_pass"),
  "virtuoso_dba_pass": expr("vault_virtuoso_dba_pass"),
  "doi_admins": expr("vault_doi_admins"),
} satisfies Inventory;
