// Auto-generated by gen-data.ts from ../devops/test-fs4.inventory/group_vars/core_host/vars.yml
import type { Inventory } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";

const { V } = context<VaultVars>();

export default {
  "virtuoso_enable": true,
  "postgis_admin_pass": V.vault_postgis_admin_pass,
  "postgis_writer_pass": V.vault_postgis_writer_pass,
  "postgis_reader_pass": V.vault_postgis_reader_pass,
  "rdflog_db_pass": V.vault_rdflog_db_pass,
  "virtuoso_dba_pass": V.vault_virtuoso_dba_pass,
  "doi_admins": V.vault_doi_admins,
} satisfies Inventory;
