// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.sitesaquanetform/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  certbot_conf_name: string;
  certbot_domains: unknown[];
  nginx_conf_name: string;
  project_dir: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
