// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.sitesaquanetform/{defaults,vars}/*.yml
// Per-role variable context: 4 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  certbot_conf_name: string;
  certbot_domains: unknown[];
  nginx_conf_name: string;
  project_dir: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
