// Auto-generated by gen-data.ts from ../devops/roles/icos.sftp_user/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "sftp_user_owner": "{{ sftp_user_login }}",
  "sftp_user_group": "{{ sftp_user_owner }}",
  "sftp_user_password": null,
  "sftp_user_pubkey": null,
  "sftp_user_hostdesc": "{{ inventory_hostname }}",
  "_sftp_parent_dir": "{{ sftp_user_dir | dirname }}",
  "_sftp_create_home": "{{ sftp_authorized_keys | bool }}",
} satisfies VarsFile;
