// Auto-generated by gen-data.ts from ../devops/roles/icos.sftp_user/defaults/main.yml
import type { Vars } from "../../../../roles/icos.sftp_user/_ctx.ts";
import { context } from "../../../../lib/context.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";

interface Self {
  _sftp_create_home: unknown;
  _sftp_parent_dir: unknown;
  sftp_user_group: unknown;
  sftp_user_hostdesc: unknown;
  sftp_user_owner: unknown;
  sftp_user_password: unknown;
  sftp_user_pubkey: unknown;
}
const { V } = context<Self & BuiltinVars & ParamVars>();

export default {
  "sftp_user_owner": V.sftp_user_login,
  "sftp_user_group": V.sftp_user_owner,
  "sftp_user_password": null,
  "sftp_user_pubkey": null,
  "sftp_user_hostdesc": V.inventory_hostname,
  "_sftp_parent_dir": V.sftp_user_dir.dirname(),
  "_sftp_create_home": V.sftp_authorized_keys.bool(),
} satisfies Vars;
