// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nginxsite/{defaults,vars}/*.yml
// Per-role variable context: 8 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  certbot_domains: string;
  certbot_name: string;
  nginxauth_name: string;
  nginxauth_users: string;
  nginxsite_path_available: string;
  nginxsite_path_confd: string;
  nginxsite_path_enable: string;
  nginxsite_state: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
