// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.podman/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  conmon_min_version: unknown;
  golang_min_version: unknown;
  podman_arch: unknown;
  podman_docker: unknown;
  podman_src_dir: unknown;
  podman_version: unknown;
}

export const { V, tmpl } = context<
  AllVars & ParamVars
>();
