// Auto-generated by gen-data.ts from ../devops/roles/icos.drupal/vars/drupal.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "project_dir": "{{ drupal_home }}/{{ website }}/drupal",
  "certbot_domains": "{{ ssl_domains | default([domain]) }}",
  "certbot_conf_name": "{{ nginx_conf_name }}",
} satisfies VarsFile;
