// Auto-generated by gen-data.ts from ../devops/roles/icos.drupal/vars/drupal.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "project_dir": tmpl("{{ drupal_home }}/{{ website }}/drupal"),
  "certbot_domains": tmpl("{{ ssl_domains | default([domain]) }}"),
  "certbot_conf_name": tmpl("{{ nginx_conf_name }}"),
} satisfies VarsFile;
