// Auto-generated by gen-data.ts from ../devops/roles/icos.drupal/vars/drupal.yml
import { type VarsFile } from "../../../../lib/data.ts";
import { website } from "../../../../lib/paramvars.ts";
import { jinja, tmpl } from "../../../../lib/template.ts";
import { V } from "../../../../roles/icos.drupal/_ctx.ts";

export default {
  "project_dir": tmpl`${V.drupal_home}/${website}/drupal`,
  "certbot_domains": jinja`{{ ${V.ssl_domains} | default([${V.domain}]) }}`,
  "certbot_conf_name": V.nginx_conf_name,
} satisfies VarsFile;
