// Auto-generated by gen-data.ts from ../devops/roles/icos.drupal/vars/nl-vars.yml
import { type VarsFile } from "../../../../lib/data.ts";

export default {
  "nginx_conf_name": "icosnl",
  "drupal_docker_port": 8121,
  "mysql_docker_port": 3343,
  "domain": "www.icos-netherlands.nl",
  "trusted_host": "^www\\.icos-netherlands\\.nl$",
  "ssl_domains": [
    "icos-netherlands.nl",
    "www.icos-netherlands.nl"
  ],
  "drupal_modules": [
    "bartik"
  ]
} satisfies VarsFile;
