// Auto-generated by gen-data.ts from ../devops/roles/icos.drupal/vars/otc-vars.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "nginx_conf_name": "icosotc",
  "drupal_docker_port": 8109,
  "mysql_docker_port": 3336,
  "domain": "www.icos-otc.org",
  "trusted_host": "^www\\.icos-otc\\.org$",
  "ssl_domains": [
    "otc.icos-cp.eu",
    "icos-otc.org",
    "www.icos-otc.org",
  ],
  "drupal_modules": [
    "bartik",
    "redirect",
  ],
} satisfies VarsFile;
