// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_vm/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";

interface Self {
  lxd_vm_ip: string;
  lxd_vm_port: string;
  lxd_vm_inventory_hostname: string;
  lxd_vm_forward: string;
  lxd_vm_root_size: string;
  lxd_vm_root_pool: string;
  lxd_vm_docker: string;
  lxd_vm_docker_size: string;
  lxd_vm_profiles: string;
  lxd_vm_devices: string;
  lxd_vm_config: string;
  __lxd_vm_profiles: string;
  __lxd_vm_devices: string;
  __lxd_vm_config: string;
  lxd_vm_ubuntu_version: string;
  lxd_source: string;
  zfsdocker_name: string;
}
const { V, expr, rawTmpl } = context<Self & Globals & BuiltinVars>();

export default {
  "lxd_vm_ip": expr("_lxd_static_ip.ip"),
  "lxd_vm_port": expr("hostvars[lxd_vm_inventory_hostname].ansible_port"),
  "lxd_vm_inventory_hostname": expr("lxd_vm_name"),
  "lxd_vm_forward": true,
  "lxd_vm_root_keys": null,
  "lxd_vm_root_size": "50GB",
  "lxd_vm_root_pool": expr("lxd_vm_name"),
  "lxd_vm_docker": false,
  "lxd_vm_docker_size": "50G",
  "lxd_vm_profiles": [],
  "lxd_vm_devices": {},
  "lxd_vm_config": {},
  "__lxd_vm_profiles": expr("lxd_vm_default_profiles + lxd_vm_profiles"),
  "__lxd_vm_devices": rawTmpl(
    "{{ lxd_vm_default_devices | combine(_static_ip_info.devices) | combine(lxd_vm_devices)  }}",
  ),
  "__lxd_vm_config": rawTmpl(
    "{{ lxd_vm_default_config | combine(lxd_vm_config)  }}",
  ),
  "lxd_vm_ubuntu_version": "22.04",
  "lxd_source": {
    "type": "image",
    "mode": "pull",
    "server": "https://cloud-images.ubuntu.com/releases",
    "protocol": "simplestreams",
    "alias": V.lxd_vm_ubuntu_version,
  },
  "zfsdocker_name": expr("lxd_vm_name"),
} satisfies VarsFile;
