// Auto-generated by gen-data.ts from ../devops/roles/icos.lxd_vm/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { tmpl } from "../../../../lib/ansible.ts";

export default {
  "lxd_vm_ip": tmpl("{{ _lxd_static_ip.ip }}"),
  "lxd_vm_port": tmpl("{{ hostvars[lxd_vm_inventory_hostname].ansible_port }}"),
  "lxd_vm_inventory_hostname": tmpl("{{ lxd_vm_name }}"),
  "lxd_vm_forward": true,
  "lxd_vm_root_keys": null,
  "lxd_vm_root_size": "50GB",
  "lxd_vm_root_pool": tmpl("{{ lxd_vm_name }}"),
  "lxd_vm_docker": false,
  "lxd_vm_docker_size": "50G",
  "lxd_vm_profiles": [],
  "lxd_vm_devices": {},
  "lxd_vm_config": {},
  "__lxd_vm_profiles": tmpl("{{ lxd_vm_default_profiles + lxd_vm_profiles }}"),
  "__lxd_vm_devices": tmpl(
    "{{ lxd_vm_default_devices | combine(_static_ip_info.devices) | combine(lxd_vm_devices)  }}",
  ),
  "__lxd_vm_config": tmpl(
    "{{ lxd_vm_default_config | combine(lxd_vm_config)  }}",
  ),
  "lxd_vm_ubuntu_version": "22.04",
  "lxd_source": {
    "type": "image",
    "mode": "pull",
    "server": "https://cloud-images.ubuntu.com/releases",
    "protocol": "simplestreams",
    "alias": tmpl("{{ lxd_vm_ubuntu_version }}"),
  },
  "zfsdocker_name": tmpl("{{ lxd_vm_name }}"),
} satisfies VarsFile;
