// Auto-generated by gen-data.ts from ../devops/roles/icos.onlyoffice/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";

interface Self {
  onlyoffice_version: string;
  onlyoffice_port: string;
  onlyoffice_home: string;
  onlyoffice_build_dir: string;
  onlyoffice_domain: string;
}
const { V, tmpl } = context<Self & Globals & BuiltinVars & AllVars>();

export default {
  "onlyoffice_version": "9.0.4",
  "onlyoffice_port": 8201,
  "onlyoffice_home": "/docker/onlyoffice",
  "onlyoffice_build_dir": tmpl`${V.onlyoffice_home}/build`,
  "onlyoffice_domain": "onlyoffice.icos-cp.eu",
} satisfies VarsFile;
