// Auto-generated by gen-data.ts from ../devops/roles/icos.onlyoffice/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";

export default {
  "onlyoffice_version": "9.0.4",
  "onlyoffice_port": 8201,
  "onlyoffice_home": "/docker/onlyoffice",
  "onlyoffice_build_dir": "{{ onlyoffice_home }}/build",
  "onlyoffice_domain": "onlyoffice.icos-cp.eu",
} satisfies VarsFile;
