// Auto-generated by gen-data.ts from ../devops/roles/icos.onlyoffice/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";
import type { AllVars } from "../../../../lib/allvars.ts";
import type { ParamVars } from "../../../../lib/paramvars.ts";
import type { VaultVars } from "../../../../lib/vaultvars.ts";
import type { VarShapes } from "../../../../lib/shapes.ts";

interface Self {
  onlyoffice_version: unknown;
  onlyoffice_port: unknown;
  onlyoffice_home: unknown;
  onlyoffice_build_dir: unknown;
  onlyoffice_domain: unknown;
}
const { V, tmpl } = context<
  Self & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();

export default {
  "onlyoffice_version": "9.0.4",
  "onlyoffice_port": 8201,
  "onlyoffice_home": "/docker/onlyoffice",
  "onlyoffice_build_dir": tmpl`${V.onlyoffice_home}/build`,
  "onlyoffice_domain": "onlyoffice.icos-cp.eu",
} satisfies VarsFile;
