// Auto-generated by gen-data.ts from ../devops/roles/ops.zfs/defaults/main.yml
import { ansible_architecture } from "../../../../lib/builtins.ts";
import { fake_architecture } from "../../../../lib/paramvars.ts";
import { upgrade_everything } from "../../../../lib/sharedvars.ts";
import { tmpl } from "../../../../lib/template.ts";
import { hostvar } from "../../../../lib/vars.ts";
import { V, type Vars } from "../../../../roles/ops.zfs/_ctx.ts";

export default {
  "httm_upgrade": upgrade_everything.default(false).bool(),
  "httm_architecture": fake_architecture.default(ansible_architecture),
  "httm_version": hostvar("localhost").httm_version,
  "httm_url_map": {
    "x86_64":
      tmpl`https://github.com/kimono-koans/httm/releases/download/${V.httm_version}/httm_${V.httm_version}-1_amd64.deb`,
  },
} satisfies Vars;
