// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/ops.zfs/{defaults,vars}/*.yml
// Per-role variable context: 4 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  httm_architecture: string;
  httm_upgrade: string;
  httm_url_map: Record<string, unknown>;
  httm_version: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
