// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/ops.zfs/{defaults,vars}/*.yml
// Per-role variable context: 4 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  httm_architecture: string;
  httm_upgrade: string;
  httm_url_map: Record<string, unknown>;
  httm_version: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
