// Auto-generated by gen-data.ts from ../devops/roles/icos.eurocom/defaults/main.yml
import { type Vars } from "../../../../roles/icos.eurocom/_ctx.ts";

export default {
  "eurocom_domain": "eurocom.icos-cp.eu",
  "eurocom_web_root": "/usr/share/nginx/eurocom",
  "eurocom_data_home": "/pool/ute/eurocom",
  "eurocom_auth_file": "/etc/nginx/auth/eurocom",
} satisfies Vars;
