// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.docker/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { Builtins } from "../../lib/builtins.ts";

export interface Vars {
  docker_periodic_cleanup: boolean;
  docker_prevent_upgrade: boolean;
  docker_upgrade: boolean;
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & Builtins
>();
