// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.docker/{defaults,vars}/*.yml
// Per-role variable context: 3 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  docker_periodic_cleanup: boolean;
  docker_prevent_upgrade: boolean;
  docker_upgrade: boolean;
}

export const { V } = context<
  Vars & BuiltinVars
>();
