// Auto-generated by gen-data.ts from ../devops/roles/icos.cpauth/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";

interface Self {
  cpauth_user: string;
  cpauth_home: string;
  cpauth_oauth_conf: string;
  cpauth_mailing_smtp: string;
  cpauth_mailing_pass: string;
  cpauth_masteradmin_pass: string;
  cpauth_user_secret_salt: string;
  cpauth_port: string;
  cpauth_bind_addr: string;
  cpauth_host: string;
}
const { V, expr } = context<Self & Globals & BuiltinVars>();

export default {
  "cpauth_user": "cpauth",
  "cpauth_home": "/home/cpauth",
  "cpauth_oauth_conf": expr("vault_cpauth_oauth_conf"),
  "cpauth_mailing_smtp": expr("vault_cpauth_mailing_smtp"),
  "cpauth_mailing_pass": expr("vault_cpauth_mailing_pass"),
  "cpauth_masteradmin_pass": expr("vault_cpauth_masteradmin_pass"),
  "cpauth_user_secret_salt": expr("vault_cpauth_user_secret_salt"),
  "cpauth_port": 8080,
  "cpauth_bind_addr": V.coreapp_bind_addr,
  "cpauth_host": V.coreapp_httpproxy_host,
} satisfies VarsFile;
