// Auto-generated by gen-data.ts from ../devops/roles/icos.cpauth/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr } from "../../../../lib/ansible.ts";

export default {
  "cpauth_user": "cpauth",
  "cpauth_home": "/home/cpauth",
  "cpauth_oauth_conf": expr("vault_cpauth_oauth_conf"),
  "cpauth_mailing_smtp": expr("vault_cpauth_mailing_smtp"),
  "cpauth_mailing_pass": expr("vault_cpauth_mailing_pass"),
  "cpauth_masteradmin_pass": expr("vault_cpauth_masteradmin_pass"),
  "cpauth_user_secret_salt": expr("vault_cpauth_user_secret_salt"),
  "cpauth_port": 8080,
  "cpauth_bind_addr": expr("coreapp_bind_addr"),
  "cpauth_host": expr("coreapp_httpproxy_host"),
} satisfies VarsFile;
