// Auto-generated by gen-data.ts from ../devops/roles/icos.stiltrun/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { expr, tmpl } from "../../../../lib/ansible.ts";

export default {
  "stiltrun_image_id": "721eb2cdb9b5",
  "stiltrun_image_name": "stiltcustom",
  "stiltrun_image_url":
    tmpl`https://static.icos-cp.eu/share/docker/stilt/stiltcustom-${
      expr("stiltrun_image_id")
    }.tgz`,
  "stiltrun_input_dir": expr("stilt_input_dir"),
  "stiltrun_user": "stiltcluster",
} satisfies VarsFile;
