services:
  nexus:
    # https://hub.docker.com/r/sonatype/nexus/tags
    image: sonatype/nexus:{{ nexus_version }}
    container_name: nexus
    ports:
      - "127.0.0.1:{{ nexus_host_port }}:8081"
    environment:
      CONTEXT_PATH: /
    volumes:
      - ./volumes/storage:/sonatype-work
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
