// Auto-generated by gen-data.ts from ../devops/roles/icos.node_exporter/defaults/main.yml
import type { VarsFile } from "../../../../lib/data.ts";
import { context } from "../../../../lib/context.ts";
import type { Globals } from "../../../../lib/globals.ts";
import type { BuiltinVars } from "../../../../lib/builtins.ts";

interface Self {
  node_exporter_user: string;
  node_exporter_home: string;
  node_exporter_download: string;
  node_exporter_textfiles: string;
  node_exporter_environ: string;
  node_exporter_bin: string;
  node_exporter_listen: string;
  node_exporter_bindto: string;
  node_exporter_allow: string;
  node_exporter_arch: string;
  node_exporter_arch_map: string;
  dirsize_home: string;
  dirsize_sh: string;
  dirsize_dirnames: string;
  dirsize_prom: string;
  dirsize_initial: string;
  dockermon_enable: string;
  dockermon_home: string;
  dockermon_prom: string;
  lxdmon_enable: string;
}
const { V, expr, tmpl } = context<Self & Globals & BuiltinVars>();

export default {
  "node_exporter_user": "node_exporter",
  "node_exporter_home": "/opt/node_exporter",
  "node_exporter_download": tmpl`${V.node_exporter_home}/download`,
  "node_exporter_textfiles": tmpl`${V.node_exporter_home}/textfiles`,
  "node_exporter_environ": tmpl`${V.node_exporter_home}/environ`,
  "node_exporter_bin": "/usr/local/sbin/node_exporter",
  "node_exporter_listen": 9100,
  "node_exporter_bindto": "lo",
  "node_exporter_allow": false,
  "node_exporter_arch": expr(
    "node_exporter_arch_map[ansible_architecture] |\n   default(ansible_architecture)",
  ),
  "node_exporter_arch_map": {
    "armv6l": "armv6",
    "armv7l": "armv7",
    "x86_64": "amd64",
  },
  "dirsize_enable": false,
  "dirsize_home": tmpl`${V.node_exporter_home}/directory-size`,
  "dirsize_sh": tmpl`${expr("node_exporter_scripts")}/directory-size.sh`,
  "dirsize_dirnames": tmpl`${V.dirsize_home}/dirnames.txt`,
  "dirsize_prom": tmpl`${V.node_exporter_textfiles}/directory-size.prom`,
  "dirsize_initial": [],
  "dockermon_enable": false,
  "dockermon_home": tmpl`${V.node_exporter_home}/dockermon`,
  "dockermon_prom": tmpl`${V.node_exporter_textfiles}/dockermon.prom`,
  "lxdmon_enable": false,
} satisfies VarsFile;
