// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.wg_hub/{defaults,vars}/*.yml
// Per-role variable context: 10 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  wg_hub_addr: string;
  wg_hub_allow_all: string;
  wg_hub_intf: string;
  wg_hub_ishub: string;
  wg_hub_key: string;
  wg_hub_key_dir: string;
  wg_hub_peer: string;
  wg_hub_port: string;
  wg_hub_reresolve: string;
  wg_hub_self: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
