// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.wg_hub/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { ParamVars } from "../../lib/paramvars.ts";
import type { VaultVars } from "../../lib/vaultvars.ts";
import type { VarShapes } from "../../lib/shapes.ts";

export interface Vars {
  wg_hub_addr: unknown;
  wg_hub_allow_all: unknown;
  wg_hub_intf: unknown;
  wg_hub_ishub: unknown;
  wg_hub_key: unknown;
  wg_hub_key_dir: unknown;
  wg_hub_peer: unknown;
  wg_hub_port: unknown;
  wg_hub_reresolve: unknown;
  wg_hub_self: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();
