// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.fail2ban/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  fail2ban_config_files: unknown[];
}

export const { V, tmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
