// Auto-generated by gen-data.ts from ../devops/staging.inventory/core.yml
import type { Inventory } from "../../lib/data.ts";
import { expr, rawTmpl, tmpl } from "../../lib/ansible.ts";

export default {
  "all": {
    "vars": {
      "fsicos2_ip": "194.47.223.139",
      "staging_lxd_ip": "10.189.225.88",
      "cpauth_icos_domain": "cpauthstaging.icos-cp.eu",
      "cpauth_sites_domain": "authstaging.fieldsites.se",
      "cpauth_cities_domain": "cityauthstaging.icos-cp.eu",
      "cpmeta_icos_domain": "metastaging.icos-cp.eu",
      "cpmeta_sites_domain": "metastaging.fieldsites.se",
      "cpmeta_cities_domain": "citymetastaging.icos-cp.eu",
      "cpdata_icos_domain": "datastaging.icos-cp.eu",
      "cpdata_sites_domain": "datastaging.fieldsites.se",
      "cpdata_cities_domain": "citydatastaging.icos-cp.eu",
      "cpauth_domains": [
        expr("cpauth_icos_domain"),
        expr("cpauth_sites_domain"),
        expr("cpauth_cities_domain"),
      ],
      "cpmeta_domains": [
        expr("cpmeta_icos_domain"),
        expr("cpmeta_sites_domain"),
        expr("cpmeta_cities_domain"),
      ],
      "cpdata_domains": [
        expr("cpdata_icos_domain"),
        expr("cpdata_sites_domain"),
        expr("cpdata_cities_domain"),
      ],
      "doi_domains": [
        "doistaging.icos-cp.eu",
      ],
      "postgis_dbs": [
        expr("postgis_icos_db_name"),
        expr("postgis_sites_db_name"),
        expr("postgis_cities_db_name"),
      ],
      "restheart_dbs": [
        expr("restheart_icos_db_name"),
        expr("restheart_sites_db_name"),
        expr("restheart_cities_db_name"),
      ],
      "activity_log_ignore_ips": [],
      "showUnderConstruction": "true",
      "showCarbonBadge": "false",
      "environmentName": "staging",
    },
    "children": {
      "core_host": {
        "hosts": {
          "staging": null,
        },
        "vars": {
          "coreapp_bind_addr": "0.0.0.0",
          "cpmeta_filestorage_target": tmpl`${expr("cpmeta_home")}/filestorage`,
          "cpmeta_backup_enable": false,
          "cpmeta_config_files": [
            "application_production.conf",
            "application_production_sensitive.conf",
            "application_staging_amendment.conf",
          ],
          "cpdata_filestorage_target": "/data/dataAppStorage",
          "cpdata_b2safe_dry_run": true,
          "cpdata_config_files": [
            "application_production.conf",
            "application_staging_amendment.conf",
          ],
          "cpauth_config_files": [
            "application_production.conf",
            "application_staging_amendment.conf",
          ],
          "postgis_db_port": 5438,
          "postgis_hostname": "127.0.0.1",
          "rdflog_postgres_version": 10,
          "cpauth_envries": [
            {
              "name": "ICOS",
              "restheart_url": tmpl`http://127.0.0.1:${
                expr("restheart_bind_port")
              }/${rawTmpl("{{ restheart_icos_db_name}}")}`,
            },
            {
              "name": "SITES",
              "restheart_url": tmpl`http://127.0.0.1:${
                expr("restheart_bind_port")
              }/${rawTmpl("{{ restheart_sites_db_name}}")}`,
            },
            {
              "name": "ICOSCities",
              "restheart_url": tmpl`http://127.0.0.1:${
                expr("restheart_bind_port")
              }/${expr("restheart_cities_db_name")}`,
              "restheart_username": expr("city_restheart_basic_auth.username"),
              "restheart_password": expr("city_restheart_basic_auth.password"),
            },
          ],
          "data_envries": [
            {
              "name": "ICOS",
              "restheart_url": tmpl`http://127.0.0.1:${
                expr("restheart_bind_port")
              }/${rawTmpl("{{ restheart_icos_db_name}}")}`,
              "postgis_db_name": expr("postgis_icos_db_name"),
            },
            {
              "name": "SITES",
              "restheart_url": tmpl`http://127.0.0.1:${
                expr("restheart_bind_port")
              }/${rawTmpl("{{ restheart_sites_db_name}}")}`,
              "postgis_db_name": expr("postgis_sites_db_name"),
            },
            {
              "name": "ICOSCities",
              "restheart_url": tmpl`http://127.0.0.1:${
                expr("restheart_bind_port")
              }/${expr("restheart_cities_db_name")}`,
              "postgis_db_name": expr("postgis_cities_db_name"),
            },
          ],
        },
      },
      "core_server": {
        "hosts": {
          "fsicos2": {
            "ansible_port": 60022,
          },
        },
        "vars": {
          "coreapp_httpproxy_host": "staging.lxd",
          "coreapp_host_ip": expr("staging_lxd_ip"),
          "cpmeta_nginxsite_name": "cpmeta-staging",
          "cpmeta_certbot_name": "cpmeta-staging",
          "cpdata_certbot_name": "cpdata-staging",
          "cpdata_nginxsite_name": "cpdata-staging",
          "cpauth_certbot_name": "cpauth-staging",
          "cpauth_nginxsite_name": "cpauth-staging",
          "restheart_host": "staging.lxd",
          "restheart_nginxsite_name": "restheart-staging",
          "restheart_certbot_name": "restheart-staging",
          "restheart_domains": [
            "restheartstaging.icos-cp.eu",
          ],
          "doi_certbot_name": "doi-staging",
          "doi_nginxsite_name": "doi-staging",
        },
      },
    },
  },
} satisfies Inventory;
