all:
  children:
    core_host:
      hosts:
        localhost:

      vars:
        corebackup_host: cdb

        borg_bin: ~/.local/bin/borg
        borg_install_ops_borg: false

        docker_compose_home: "{{ ansible_env.HOME }}/docker"
        rdflog_home: "{{ ansible_env.HOME }}/docker/rdflog"
        restheart_become: false
        restheart_restore_script_dir: "{{ ansible_env.HOME }}/.local/bin"

        postgis_container_name: postgis
        postgis_init_db: false
        postgis_backup_location: ~bbserver/repos/postgis.repo
        postgis_user: postgres
        postgis_db_port: 5438

        rdflog_backup_location: ~bbserver/repos/rdflog.repo
        rdflog_user: rdflog

        restheart_backup_location: ~bbserver/repos/restheart.repo
        restheart_container_name: restheart-mongodb-1
        restheart_dbs:
          - "{{ restheart_icos_db_name }}"
          - "{{ restheart_sites_db_name }}"
          - "{{ restheart_cities_db_name }}"
        bbclient_home: ~/.local/bin/borg
        rdflog_postgres_version: 15

    core_server:
      hosts:
        localhost:

      vars:
