// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.zrepl/{defaults,vars}/*.yml
// Per-role variable context: 1 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  zrepl_port: number;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const zrepl_port = vref("zrepl_port");
