// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.doi/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  doi_bind_addr: Tmpl;
  doi_home: string;
  doi_host: Tmpl;
  doi_meta_domain: Tmpl;
  doi_port: number;
  doi_servicename: string;
  doi_user: string;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const doi_bind_addr = vref("doi_bind_addr");
export const doi_home = vref("doi_home");
export const doi_host = vref("doi_host");
export const doi_meta_domain = vref("doi_meta_domain");
export const doi_port = vref("doi_port");
export const doi_servicename = vref("doi_servicename");
export const doi_user = vref("doi_user");
