// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.doi/{defaults,vars}/*.yml
// Per-role variable context: 7 variables.
import { context } from "../../lib/context.ts";

export interface Vars {
  doi_bind_addr: string;
  doi_home: string;
  doi_host: string;
  doi_meta_domain: string;
  doi_port: number;
  doi_servicename: string;
  doi_user: string;
}

export const { V, tmpl, isDef, notVar } = context<Vars>();
