// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.doi/{defaults,vars}/*.yml
// Per-role variable context: 7 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { ParamVars } from "../../lib/paramvars.ts";
import type { VaultVars } from "../../lib/vaultvars.ts";
import type { VarShapes } from "../../lib/shapes.ts";

export interface Vars {
  doi_bind_addr: unknown;
  doi_home: unknown;
  doi_host: unknown;
  doi_meta_domain: unknown;
  doi_port: unknown;
  doi_servicename: unknown;
  doi_user: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();
