// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.telegraf/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  telegraf_config: string;
  telegraf_config_file: string;
  telegraf_config_root: string;
  telegraf_config_state: string;
  telegraf_smart_enable: boolean;
  telegraf_upgrade: Tmpl;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const telegraf_config = vref("telegraf_config");
export const telegraf_config_file = vref("telegraf_config_file");
export const telegraf_config_root = vref("telegraf_config_root");
export const telegraf_config_state = vref("telegraf_config_state");
export const telegraf_smart_enable = vref("telegraf_smart_enable");
export const telegraf_upgrade = vref("telegraf_upgrade");
