// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.telegraf/{defaults,vars}/*.yml
// Per-role variable context: 6 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  telegraf_config: unknown;
  telegraf_config_file: unknown;
  telegraf_config_root: unknown;
  telegraf_config_state: unknown;
  telegraf_smart_enable: unknown;
  telegraf_upgrade: unknown;
}

export const { V, tmpl } = context<
  Vars & BuiltinVars
>();
