// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.victoriametrics/{defaults,vars}/*.yml
// Per-role variable context: 9 own variables, each exported as
// a named binding. Reference Ansible variables by importing them (no V
// proxy); the Vars interface is the type this role's data satisfies.
import { type Tmpl, varProxy, type VarRef } from "../../lib/template.ts";

export interface Vars {
  vm_graf_image: string;
  vm_graf_plugins: Tmpl;
  vm_graf_port: number;
  vm_graf_url: string;
  vm_home: string;
  vm_promlens_port: number;
  vm_scrape_conf: string;
  vm_upgrade: Tmpl;
  vm_vm_port: number;
}

const vref = <K extends keyof Vars>(k: K): VarRef<Vars[K]> =>
  varProxy(k) as VarRef<Vars[K]>;

export const vm_graf_image = vref("vm_graf_image");
export const vm_graf_plugins = vref("vm_graf_plugins");
export const vm_graf_port = vref("vm_graf_port");
export const vm_graf_url = vref("vm_graf_url");
export const vm_home = vref("vm_home");
export const vm_promlens_port = vref("vm_promlens_port");
export const vm_scrape_conf = vref("vm_scrape_conf");
export const vm_upgrade = vref("vm_upgrade");
export const vm_vm_port = vref("vm_vm_port");
