// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.victoriametrics/{defaults,vars}/*.yml
// Per-role variable context: 9 own variables, widened with
// only the registries this role's task/handler files reference.
import { context } from "../../lib/context.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { ParamVars } from "../../lib/paramvars.ts";

export interface Vars {
  vm_graf_image: unknown;
  vm_graf_plugins: unknown;
  vm_graf_port: unknown;
  vm_graf_url: unknown;
  vm_home: unknown;
  vm_promlens_port: unknown;
  vm_scrape_conf: unknown;
  vm_upgrade: unknown;
  vm_vm_port: unknown;
}

export const { V, tmpl, rawTmpl } = context<
  Vars & BuiltinVars & ParamVars
>();
