// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nginxforward/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";

export interface Vars {
  nginxforward_cert_conf: string;
  nginxforward_cert_path: string;
  nginxforward_enable: string;
  nginxforward_file: string;
  nginxforward_host: string;
  nginxforward_key_path: string;
  nginxforward_path_available: string;
  nginxforward_path_enabled: string;
  nginxforward_site_path: string;
  nginxforward_user_file: string;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars
>();
