// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.nginxforward/{defaults,vars}/*.yml
// Per-role variable context: 10 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, type VarRef, varProxy } from "../../lib/template.ts";

export interface Vars {
  nginxforward_cert_conf: Tmpl;
  nginxforward_cert_path: Tmpl;
  nginxforward_enable: boolean;
  nginxforward_file: string;
  nginxforward_host: string;
  nginxforward_key_path: Tmpl;
  nginxforward_path_available: Tmpl;
  nginxforward_path_enabled: Tmpl;
  nginxforward_site_path: Tmpl;
  nginxforward_user_file: Tmpl;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } =
  new Proxy({}, { get: (_t, name: string) => varProxy(name) }) as
    { readonly [K in keyof Vars]: VarRef<Vars[K]> };
