// Names-only registry of role caller-parameters and play-, include- and
// task-level variables: names a playbook or play supplies (role vars,
// include_tasks vars, task `vars:` blocks, `-e` extra vars) and tasks read,
// that no defaults/vars file defines — so gen-contexts.ts cannot discover
// them and they are hand-curated here. Ansible variable names form a single
// flat namespace, so declaring a name makes it a checked `V.x` everywhere.
// Names only: the V accessor maps every key to a Ref, so the uniform
// `string` type is never consulted.
//
// The generated lib/role-coverage.ts forces every parameter declared in a
// lib/roles.ts schema to be reachable as `V.x` from that role — covered by the
// role's own `Vars` (its _ctx) or a shared registry (this one, Globals, …).

export interface ParamVars {
  _builtin_version: string;
  _ssh_user: string;
  _version: string;
  admin_users: string;
  amalthea_ip: string;
  bbclient_coldbackup: string;
  bbclient_key_data: string;
  bbclient_remote: string;
  bbclient_remote_keys: string;
  bbclient_remotes: string;
  bbclient_timer_content: string;
  block: string;
  caddy_conf: string;
  caddy_name: string;
  callisto_ip: string;
  configfile: string;
  conmon_local_version: string;
  cpauth_jar_file: string;
  cpdata_jar_file: string;
  cpdata_netcdf_folder: string;
  cpmeta_jar_file: string;
  cpu_limit: string;
  data_fast_path: string;
  data_path: string;
  db_name: string;
  dbin_path: string;
  dbin_repo: string;
  dbin_unar: string;
  dbin_url: string;
  dbin_user: string;
  deb_arch: string;
  destjarfile: string;
  dnsmasq_config: string;
  dnsmasq_instance: string;
  dnsmasq_interface: string;
  docker_compose_home: string;
  docker_path: string;
  doi_jar_file: string;
  dokku_proxy_host: string;
  dokku_proxy_port: string;
  dokku_redirect_domains: string;
  dokku_static_domains: string;
  dovecot_domains: string;
  eurocom_users: string;
  exploredata_ip: string;
  exploredata_type: string;
  fake_architecture: string;
  fdp_jar_file: string;
  file: string;
  file_var: string;
  filedrop_data_home: string;
  filedrop_domain: string;
  filedrop_jar_file: string;
  flexextract_src_dir: string;
  flexpart_install_run: string;
  flexpart_ssh_remote_host: string;
  flexpart_ssh_remote_ip: string;
  flexpart_ssh_users: string;
  fsd_name: string;
  ganymede_domains: string;
  fsd_path: string;
  fsd_target: string;
  geoip_docker_build: string;
  git_version: string;
  golang_local_version: string;
  grafana_datasource_version: string;
  groupfolder_dir: string;
  groupfolder_id: string;
  groupfolder_name: string;
  host_uid: string;
  icosdata_bind_mounts: string;
  icosdata_mkdirs: string;
  jarfile: string;
  jarservice_check: string;
  jarservice_githash: string;
  jarservice_home: string;
  jarservice_local: string;
  jarservice_name: string;
  jarservice_state: string;
  jarservice_unit: string;
  jbuild_edctl_host: string;
  jbuild_force: string;
  jbuild_jyctl_host: string;
  jbuild_registry_pass: string;
  jbuild_rsync_host: string;
  jbuild_users: string;
  jupyter_admins: string;
  jupyter_backup_enable: string;
  jupyter_cert_name: string;
  jupyter_domain: string;
  jupyter_domains: string;
  jupyter_ip: string;
  jupyter_port: string;
  jupyter_user_volumes: string;
  kc_hostname: string;
  keys: string;
  lazydocker_arch: string;
  local_cert_dir: string;
  local_conf_dir: string;
  local_tmp: string;
  lockuser: string;
  lxd_forward_ip: string;
  lxd_forward_name: string;
  lxd_vm_name: string;
  mailman_domains: string;
  mailman_rest_pass: string;
  marker: string;
  mem_limit: string;
  nebula_cert_files: string;
  nebula_ip: string;
  nebula_passphrase: string;
  new_name: string;
  nextcloud_admin_password: string;
  nextcloud_exporter_pass: string;
  nginxforward_cert: string;
  nginxforward_domains: string;
  nginxforward_name: string;
  nginxforward_port: string;
  nginxforward_users: string;
  node_exporter_scripts: string;
  old_name: string;
  onlyoffice_domain: string;
  onlyoffice_secret: string;
  opendkim_domains: string;
  pool_name: string;
  pool_path: string;
  postgis_cplog_users: string;
  postgresql_backup_host: string;
  postgresql_backup_location: string;
  postgresql_container_name: string;
  postgresql_hba_file: string;
  postgresql_version: string;
  python_util_src: string;
  quince_domains: string;
  quince_name: string;
  quince_tomcat_dir: string;
  rdflog_restore_file: string;
  rdflog_vm_name: string;
  registry_allow: string;
  registry_cert: string;
  registry_host: string;
  registry_users: string;
  remove_keys: string;
  restheart_backup_host: string;
  rspamd_admin_password: string;
  rspamd_domain: string;
  rsyncd_conf: string;
  rsyncd_users: string;
  servicename: string;
  servicetemplate: string;
  set_fact: string;
  sexp_block: string;
  sexp_config: string;
  sexp_exporters: string;
  sexp_marker: string;
  sexp_state: string;
  sftp_authorized_keys: string;
  sftp_dirs: string;
  sftp_exec: string;
  sftp_user: string;
  sftp_user_dir: string;
  sftp_user_login: string;
  ssh_port: string;
  sshlogin_dst: string;
  sshlogin_dst_home: string;
  sshlogin_dst_host_keys: string;
  sshlogin_dst_user: string;
  sshlogin_src_home: string;
  sshlogin_src_ip: string;
  sshlogin_src_user: string;
  sshlogin_user: string;
  state: string;
  stilt_input_dir: string;
  stiltcluster_jar_file: string;
  stiltweb_jar_file: string;
  superuser_disable_coredump: string;
  superuser_list: string;
  telegraf_conf: string;
  timer_config: string;
  timer_content: string;
  timer_name: string;
  timer_service: string;
  user_disable_coredump: string;
  username: string;
  vm_graf_domain: string;
  vm_graf_pass: string;
  vm_promlens_token: string;
  vmagent_config_content: string;
  vmagent_config_dest: string;
  website: string;
  where: string;
  virtualenv_recreate: string;
  nexus_certbot_enable: string;
  jarservice_conf_only: string;
  lxd_vm_variant: string;
  _restart_needed: string;
  nebula_ssh_public: string;
  nginxconfig: string;
  lxd_is_snap: string;
  flexextract_docker_build: string;
  stiltcluster_fetch_host: string;
  wordpress_domains: string;
  zrepl_config: string;
}

// The role-parameter completeness check moved to the generated
// lib/role-coverage.ts: each role's `roles.ts` parameters must be covered by
// that role's OWN `Vars` (its _ctx) or a shared registry — a per-role check
// (no flat all-role-vars union needed).

// === auto-generated variable bindings (gen-bindings.ts); do not edit below ===
import { type VarRef, varProxy } from "./template.ts";
const vref = <K extends keyof ParamVars>(k: K): VarRef<ParamVars[K]> =>
  varProxy(k) as VarRef<ParamVars[K]>;

export const _builtin_version = vref("_builtin_version");
export const _restart_needed = vref("_restart_needed");
export const _ssh_user = vref("_ssh_user");
export const _version = vref("_version");
export const admin_users = vref("admin_users");
export const amalthea_ip = vref("amalthea_ip");
export const bbclient_coldbackup = vref("bbclient_coldbackup");
export const bbclient_key_data = vref("bbclient_key_data");
export const bbclient_remote = vref("bbclient_remote");
export const bbclient_remote_keys = vref("bbclient_remote_keys");
export const bbclient_remotes = vref("bbclient_remotes");
export const bbclient_timer_content = vref("bbclient_timer_content");
export const block = vref("block");
export const caddy_conf = vref("caddy_conf");
export const caddy_name = vref("caddy_name");
export const callisto_ip = vref("callisto_ip");
export const configfile = vref("configfile");
export const conmon_local_version = vref("conmon_local_version");
export const cpauth_jar_file = vref("cpauth_jar_file");
export const cpdata_jar_file = vref("cpdata_jar_file");
export const cpdata_netcdf_folder = vref("cpdata_netcdf_folder");
export const cpmeta_jar_file = vref("cpmeta_jar_file");
export const cpu_limit = vref("cpu_limit");
export const data_fast_path = vref("data_fast_path");
export const data_path = vref("data_path");
export const db_name = vref("db_name");
export const dbin_path = vref("dbin_path");
export const dbin_repo = vref("dbin_repo");
export const dbin_unar = vref("dbin_unar");
export const dbin_url = vref("dbin_url");
export const dbin_user = vref("dbin_user");
export const deb_arch = vref("deb_arch");
export const destjarfile = vref("destjarfile");
export const dnsmasq_config = vref("dnsmasq_config");
export const dnsmasq_instance = vref("dnsmasq_instance");
export const dnsmasq_interface = vref("dnsmasq_interface");
export const docker_compose_home = vref("docker_compose_home");
export const docker_path = vref("docker_path");
export const doi_jar_file = vref("doi_jar_file");
export const dokku_proxy_host = vref("dokku_proxy_host");
export const dokku_proxy_port = vref("dokku_proxy_port");
export const dokku_redirect_domains = vref("dokku_redirect_domains");
export const dokku_static_domains = vref("dokku_static_domains");
export const dovecot_domains = vref("dovecot_domains");
export const eurocom_users = vref("eurocom_users");
export const exploredata_ip = vref("exploredata_ip");
export const exploredata_type = vref("exploredata_type");
export const fake_architecture = vref("fake_architecture");
export const fdp_jar_file = vref("fdp_jar_file");
export const file = vref("file");
export const file_var = vref("file_var");
export const filedrop_data_home = vref("filedrop_data_home");
export const filedrop_domain = vref("filedrop_domain");
export const filedrop_jar_file = vref("filedrop_jar_file");
export const flexextract_docker_build = vref("flexextract_docker_build");
export const flexextract_src_dir = vref("flexextract_src_dir");
export const flexpart_install_run = vref("flexpart_install_run");
export const flexpart_ssh_remote_host = vref("flexpart_ssh_remote_host");
export const flexpart_ssh_remote_ip = vref("flexpart_ssh_remote_ip");
export const flexpart_ssh_users = vref("flexpart_ssh_users");
export const fsd_name = vref("fsd_name");
export const fsd_path = vref("fsd_path");
export const fsd_target = vref("fsd_target");
export const ganymede_domains = vref("ganymede_domains");
export const geoip_docker_build = vref("geoip_docker_build");
export const git_version = vref("git_version");
export const golang_local_version = vref("golang_local_version");
export const grafana_datasource_version = vref("grafana_datasource_version");
export const groupfolder_dir = vref("groupfolder_dir");
export const groupfolder_id = vref("groupfolder_id");
export const groupfolder_name = vref("groupfolder_name");
export const host_uid = vref("host_uid");
export const icosdata_bind_mounts = vref("icosdata_bind_mounts");
export const icosdata_mkdirs = vref("icosdata_mkdirs");
export const jarfile = vref("jarfile");
export const jarservice_check = vref("jarservice_check");
export const jarservice_conf_only = vref("jarservice_conf_only");
export const jarservice_githash = vref("jarservice_githash");
export const jarservice_home = vref("jarservice_home");
export const jarservice_local = vref("jarservice_local");
export const jarservice_name = vref("jarservice_name");
export const jarservice_state = vref("jarservice_state");
export const jarservice_unit = vref("jarservice_unit");
export const jbuild_edctl_host = vref("jbuild_edctl_host");
export const jbuild_force = vref("jbuild_force");
export const jbuild_jyctl_host = vref("jbuild_jyctl_host");
export const jbuild_registry_pass = vref("jbuild_registry_pass");
export const jbuild_rsync_host = vref("jbuild_rsync_host");
export const jbuild_users = vref("jbuild_users");
export const jupyter_admins = vref("jupyter_admins");
export const jupyter_backup_enable = vref("jupyter_backup_enable");
export const jupyter_cert_name = vref("jupyter_cert_name");
export const jupyter_domain = vref("jupyter_domain");
export const jupyter_domains = vref("jupyter_domains");
export const jupyter_ip = vref("jupyter_ip");
export const jupyter_port = vref("jupyter_port");
export const jupyter_user_volumes = vref("jupyter_user_volumes");
export const kc_hostname = vref("kc_hostname");
export const keys = vref("keys");
export const lazydocker_arch = vref("lazydocker_arch");
export const local_cert_dir = vref("local_cert_dir");
export const local_conf_dir = vref("local_conf_dir");
export const local_tmp = vref("local_tmp");
export const lockuser = vref("lockuser");
export const lxd_forward_ip = vref("lxd_forward_ip");
export const lxd_forward_name = vref("lxd_forward_name");
export const lxd_is_snap = vref("lxd_is_snap");
export const lxd_vm_name = vref("lxd_vm_name");
export const lxd_vm_variant = vref("lxd_vm_variant");
export const mailman_domains = vref("mailman_domains");
export const mailman_rest_pass = vref("mailman_rest_pass");
export const marker = vref("marker");
export const mem_limit = vref("mem_limit");
export const nebula_cert_files = vref("nebula_cert_files");
export const nebula_ip = vref("nebula_ip");
export const nebula_passphrase = vref("nebula_passphrase");
export const nebula_ssh_public = vref("nebula_ssh_public");
export const new_name = vref("new_name");
export const nextcloud_admin_password = vref("nextcloud_admin_password");
export const nextcloud_exporter_pass = vref("nextcloud_exporter_pass");
export const nexus_certbot_enable = vref("nexus_certbot_enable");
export const nginxconfig = vref("nginxconfig");
export const nginxforward_cert = vref("nginxforward_cert");
export const nginxforward_domains = vref("nginxforward_domains");
export const nginxforward_name = vref("nginxforward_name");
export const nginxforward_port = vref("nginxforward_port");
export const nginxforward_users = vref("nginxforward_users");
export const node_exporter_scripts = vref("node_exporter_scripts");
export const old_name = vref("old_name");
export const onlyoffice_domain = vref("onlyoffice_domain");
export const onlyoffice_secret = vref("onlyoffice_secret");
export const opendkim_domains = vref("opendkim_domains");
export const pool_name = vref("pool_name");
export const pool_path = vref("pool_path");
export const postgis_cplog_users = vref("postgis_cplog_users");
export const postgresql_backup_host = vref("postgresql_backup_host");
export const postgresql_backup_location = vref("postgresql_backup_location");
export const postgresql_container_name = vref("postgresql_container_name");
export const postgresql_hba_file = vref("postgresql_hba_file");
export const postgresql_version = vref("postgresql_version");
export const python_util_src = vref("python_util_src");
export const quince_domains = vref("quince_domains");
export const quince_name = vref("quince_name");
export const quince_tomcat_dir = vref("quince_tomcat_dir");
export const rdflog_restore_file = vref("rdflog_restore_file");
export const rdflog_vm_name = vref("rdflog_vm_name");
export const registry_allow = vref("registry_allow");
export const registry_cert = vref("registry_cert");
export const registry_host = vref("registry_host");
export const registry_users = vref("registry_users");
export const remove_keys = vref("remove_keys");
export const restheart_backup_host = vref("restheart_backup_host");
export const rspamd_admin_password = vref("rspamd_admin_password");
export const rspamd_domain = vref("rspamd_domain");
export const rsyncd_conf = vref("rsyncd_conf");
export const rsyncd_users = vref("rsyncd_users");
export const servicename = vref("servicename");
export const servicetemplate = vref("servicetemplate");
export const set_fact = vref("set_fact");
export const sexp_block = vref("sexp_block");
export const sexp_config = vref("sexp_config");
export const sexp_exporters = vref("sexp_exporters");
export const sexp_marker = vref("sexp_marker");
export const sexp_state = vref("sexp_state");
export const sftp_authorized_keys = vref("sftp_authorized_keys");
export const sftp_dirs = vref("sftp_dirs");
export const sftp_exec = vref("sftp_exec");
export const sftp_user = vref("sftp_user");
export const sftp_user_dir = vref("sftp_user_dir");
export const sftp_user_login = vref("sftp_user_login");
export const ssh_port = vref("ssh_port");
export const sshlogin_dst = vref("sshlogin_dst");
export const sshlogin_dst_home = vref("sshlogin_dst_home");
export const sshlogin_dst_host_keys = vref("sshlogin_dst_host_keys");
export const sshlogin_dst_user = vref("sshlogin_dst_user");
export const sshlogin_src_home = vref("sshlogin_src_home");
export const sshlogin_src_ip = vref("sshlogin_src_ip");
export const sshlogin_src_user = vref("sshlogin_src_user");
export const sshlogin_user = vref("sshlogin_user");
export const state = vref("state");
export const stilt_input_dir = vref("stilt_input_dir");
export const stiltcluster_fetch_host = vref("stiltcluster_fetch_host");
export const stiltcluster_jar_file = vref("stiltcluster_jar_file");
export const stiltweb_jar_file = vref("stiltweb_jar_file");
export const superuser_disable_coredump = vref("superuser_disable_coredump");
export const superuser_list = vref("superuser_list");
export const telegraf_conf = vref("telegraf_conf");
export const timer_config = vref("timer_config");
export const timer_content = vref("timer_content");
export const timer_name = vref("timer_name");
export const timer_service = vref("timer_service");
export const user_disable_coredump = vref("user_disable_coredump");
export const username = vref("username");
export const virtualenv_recreate = vref("virtualenv_recreate");
export const vm_graf_domain = vref("vm_graf_domain");
export const vm_graf_pass = vref("vm_graf_pass");
export const vm_promlens_token = vref("vm_promlens_token");
export const vmagent_config_content = vref("vmagent_config_content");
export const vmagent_config_dest = vref("vmagent_config_dest");
export const website = vref("website");
export const where = vref("where");
export const wordpress_domains = vref("wordpress_domains");
export const zrepl_config = vref("zrepl_config");
