// Auto-generated by gen-contexts.ts.
// Role-defined variables that are referenced from OUTSIDE their defining
// role (the cross-role surface). The per-role and data-file context
// widenings intersect this — not the full `AllVars` — so a file declares
// only the shared state it touches. `unknown` (names matter, not types).
export interface SharedVars {
  bbclient_all: unknown;
  bbclient_name: unknown;
  bbclient_repo_file: unknown;
  bbclient_wrapper: unknown;
  bbserver_home: unknown;
  certbot_conf_name: unknown;
  certbot_domains: unknown;
  certbot_name: unknown;
  certbot_nginx_conf: unknown;
  conmon_min_version: unknown;
  cpmeta_home: unknown;
  dbin__down: unknown;
  dbin__vers: unknown;
  dbin_download_base: unknown;
  docker_prevent_upgrade: unknown;
  domain: unknown;
  filedrop_port: unknown;
  iptables_ssh_port: unknown;
  mailman_home: unknown;
  nextcloud_home: unknown;
  nexus_home: unknown;
  nginxauth_name: unknown;
  nginxauth_users: unknown;
  nginxsite_domains: unknown;
  nginxsite_file: unknown;
  nginxsite_name: unknown;
  nginxsite_users: unknown;
  podman_arch: unknown;
  restheart_bind_port: unknown;
  timer_dest: unknown;
  update: unknown;
  upgrade_everything: unknown;
  vm_promlens_port: unknown;
  vm_vm_port: unknown;
  zfsdocker_name: unknown;
  zfsdocker_zvol: unknown;
}
