// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.sysstat/{defaults,vars}/*.yml
// Per-role variable context: 0 own variables, widened with
// only the registries this role's task/handler files reference.

// deno-lint-ignore no-empty-interface
export interface Vars {}
