// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.sysstat/{defaults,vars}/*.yml
// Per-role variable context: 0 variables.
import { context } from "../../lib/context.ts";

// deno-lint-ignore no-empty-interface
export interface Vars {}

export const { V, tmpl, isDef, notVar } = context<Vars>();
