// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.drupal/{defaults,vars}/*.yml
// Per-role variable context: 17 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";
import type { AllVars } from "../../lib/allvars.ts";
import type { ParamVars } from "../../lib/paramvars.ts";
import type { VaultVars } from "../../lib/vaultvars.ts";
import type { VarShapes } from "../../lib/shapes.ts";

export interface Vars {
  certbot_conf_name: unknown;
  certbot_domains: unknown;
  database_name: unknown;
  database_user: unknown;
  domain: unknown;
  drupal_docker_port: unknown;
  drupal_home: unknown;
  drupal_modules: unknown;
  drupal_version: unknown;
  drupal_websites: unknown;
  mysql_docker_port: unknown;
  nginx_conf_name: unknown;
  project_dir: unknown;
  robots_txt: unknown;
  ssl_domains: unknown;
  trusted_host: unknown;
  update: unknown;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars & AllVars & ParamVars & VaultVars & VarShapes
>();
