// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.drupal/{defaults,vars}/*.yml
// Per-role variable context: 17 own variables (+ globals + builtins).
import { context } from "../../lib/context.ts";
import type { Globals } from "../../lib/globals.ts";
import type { BuiltinVars } from "../../lib/builtins.ts";

export interface Vars {
  certbot_conf_name: string;
  certbot_domains: string;
  database_name: string;
  database_user: string;
  domain: string;
  drupal_docker_port: number;
  drupal_home: string;
  drupal_modules: unknown[];
  drupal_version: number;
  drupal_websites: unknown[];
  mysql_docker_port: number;
  nginx_conf_name: string;
  project_dir: string;
  robots_txt: string;
  ssl_domains: unknown[];
  trusted_host: string;
  update: boolean;
}

export const { V, tmpl, expr, rawTmpl, isDef, notVar } = context<
  Vars & Globals & BuiltinVars
>();
