// Auto-generated by gen-contexts.ts from
// ../../../devops/roles/icos.drupal/{defaults,vars}/*.yml
// Per-role variable context: 17 own variables, reached through
// the `V` accessor (typed by the Vars interface). The Vars interface is
// also the type this role's generated data satisfies.
import { type Tmpl, type VarRef, varProxy } from "../../lib/template.ts";

export interface Vars {
  certbot_conf_name: Tmpl;
  certbot_domains: Tmpl;
  database_name: string;
  database_user: string;
  domain: string;
  drupal_docker_port: number;
  drupal_home: string;
  drupal_modules: unknown;
  drupal_version: number;
  drupal_websites: unknown;
  mysql_docker_port: number;
  nginx_conf_name: string;
  project_dir: Tmpl;
  robots_txt: string;
  ssl_domains: unknown;
  trusted_host: string;
  update: boolean;
}

export const V: { readonly [K in keyof Vars]: VarRef<Vars[K]> } =
  new Proxy({}, { get: (_t, name: string) => varProxy(name) }) as
    { readonly [K in keyof Vars]: VarRef<Vars[K]> };
