// Auto-generated by gen-data.ts from ../devops/host_vars/icos1.yml
import { type VarsFile } from "../../lib/data.ts";

export default {
  "caddy_modules": [
    "github.com/caddyserver/replace-response",
  ],
  "caddy_global_conf": "{\n    order replace after encode\n}\n",
  "ansible_hostname": "icos1.gis.lu.se",
  "ansible_port": 60022,
  "iptables_ssh_port": 60022,
  "lxd_vm_variant": "zfs",
  "icosdata_exports": "/pool/flexextract *.nebula(rw)\n",
} satisfies VarsFile;
