// Auto-generated by gen-data.ts from ../devops/host_vars/pancake.yml
import { type VarsFile } from "../../lib/data.ts";

export default {
  "icosdata_exports":
    "/data/avengers                      fsicos3.nebula(ro,no_subtree_check,fsid=1)\n",
  "icosdata_mkdirs": [
    "/data/avengers",
  ],
  "icosdata_nfs_mounts": [
    {
      "src": "fsicos3.nebula:/data/fit_ic",
      "path": "/data/fit_ic",
      "opts": "ro,soft,x-systemd.after=nebula.service",
    },
  ],
} satisfies VarsFile;
