# https://fairdatapoint.readthedocs.io

- name: Create fairdatapoint directory
  file:
    path: "{{ fdp_home }}/"
    state: directory


- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ fdp_home }}"
    lstrip_blocks: yes
  register: _compose


- name: Copy Dockerfile
  template:
    src: Dockerfile
    dest: "{{ fdp_home }}"
  register: _dockerfile


- name: Copy jarfile
  copy:
    src: "{{ fdp_jar_file }}"
    dest: "{{ fdp_home }}/fdp.jar"
  register: _jarfile


- name: Generate JWT secret
  include_role:
    name: icos.password_env_file
  vars:
      file: "{{ item.file }}"
      set_fact: "{{ item.set_fact }}"
      file_var: "{{ item.file_var }}"
  loop:
    - file: "{{ fdp_home }}/jwt-secret"
      set_fact: fdp_jwt_secret
      file_var: FDP_JWT_SECRET


- name: Copy application.yml
  template:
    src: application.yml
    dest: "{{ fdp_home }}/"
    lstrip_blocks: yes
  register: _config


- name: Start fairdatapoint
  icos_docker_compose:
    chdir: "{{ fdp_home }}"
    force_recreate: "{{ _config.changed or _compose.changed or _jarfile.changed or _dockerfile.changed }}"
